##################################################
#     INSTALLATION FOR Ubuntu/Debian
##################################################

#
# Ansible facts of interest:
#
#  ansible_os_family: Debian
#  ansible_distribution_major_version: 11 | 12 | 22 | 24
#  ansible_distribution_release: bullseye | bookworm | jammy | noble
#  ansible_distribution: Debian | Ubuntu
#

- name: Install the GCS repository definitions
  become: yes
  apt:
    deb: https://downloads.globus.org/globus-connect-server/stable/installers/repo/deb/globus-repo_latest_all.deb
    state: present

- name: Update the APT cache
  become: yes
  apt:
    update_cache: yes

- name: Install Globus Connect Server
  become: yes
  apt:
    name: globus-connect-server54
    state: present
