##################################################
#      INSTALLATION FOR OPENSUSE DERIVATIVES.
##################################################

#
# Ansible facts of interest (ansible localhost -m ansible.builtin.setup):
#
#  ansible_os_family: Suse
#  ansible_distribution_major_version: 15
#  ansible_distribution_version: 15.6
#  ansible_distribution: openSUSE Leap | SLES
#

# Import the Globus key explicitly because the Ansible zypper module doesn't
# auto-import keys the way zypper will.
- name: Install the GCS RPM repository key (2024)
  become: yes
  rpm_key:
    key: https://downloads.globus.org/globus-connect-server/stable/installers/keys/GPG-KEY-Globus-2024

- name: Install the GCS repository definitions
  become: yes
  zypper:
    name: https://downloads.globus.org/globus-connect-server/stable/installers/repo/rpm/globus-repo-latest.noarch.rpm
    state: present

- name: Install Globus Connect Server
  become: yes
  zypper:
    name: globus-connect-server54
    state: present
