##################################################
#      INSTALLATION FOR RedHat DERIVATIVES.
##################################################

#
# Ansible facts of interest:
#
#  ansible_os_family: RedHat | Springdale
#  ansible_distribution_major_version: 8 | 9 | 10 | 43 | 44
#  ansible_distribution: AlmaLinux | CentOS | Fedora | OracleLinux | RedHat | Rocky | Springdale
#

# Import the EPEL key explicitly because the Ansible yum module doesn't auto-import
# keys the way yum/dnf will.
- name: Install the EPEL RPM repository key
  become: yes
  rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_facts['distribution_major_version'] }}
  when:
    - ansible_facts['distribution'] != "Fedora"

- name: Install the EPEL repository
  become: yes
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm
    state: present
  when:
    - ansible_facts['distribution'] != "Fedora"

# Explicitly install this even though it is a soft dependency on the EPEL repo rpm because
# auto-installation of soft dependencies is configurable and some distros have it disabled.
- name: Install dnf config-manager
  become: yes
  yum:
    name: dnf-command(config-manager)
    state: present
  when:
    # Fedora 41+ comes with dnf5 and config-manager
    - ansible_facts['distribution_major_version']|int < 41

- name: Install the GCS RPM repository key (2024)
  become: yes
  rpm_key:
    key: https://downloads.globus.org/globus-connect-server/stable/installers/keys/GPG-KEY-Globus-2024

- name: Install the GCS repository definitions
  become: yes
  yum:
    name: https://downloads.globus.org/globus-connect-server/stable/installers/repo/rpm/globus-repo-latest.noarch.rpm
    state: present

- name: Install Globus Connect Server ({{ gcs_version | default('latest') }})
  become: yes
  yum:
    name: "{{ 'globus-connect-server54 = ' + gcs_version if gcs_version is defined else 'globus-connect-server54' }}"
    state: present
