# syntax=docker/dockerfile:1.3-labs

############## STAGE 1 - Prepare the image for GCS installation ################
FROM almalinux:9

# Prereqs
RUN <<EOF
    dnf install -y coreutils-single gzip python3 sudo tar util-linux
EOF

##################### STAGE 2 - Install GCS using Ansible ######################
# This is the base64 compressed tar of the ansible repo directory
COPY <<EOF /ansible.64
H4sIAAAAAAAAA+0ca3PbNjKf9Stw8nWUpCUp6mG3quU7N3ESz7mxx3Y61/HlFIiEJNQUwRKkHTbp
f79dgNSbluTISnrhZiJRBLDYXSz2BdLUl7zrMevRA0IVYK/ZVN8As9/q2m5W7eZuvdqoQz/btvfq
j0jzIYnKIJYRDQl5FAoR3dVvWftfFGi6/qHwmHwgLVhp/Rt7zb36brVea8D61+r1arH+24Dp9e97
ohtLwxG+z5zIkCy8YeEna8X667/bbO4W678NWGX9XdajsRfd2zysaP/rTVCBarP2qFqr1ncL+78V
WGv9h5T7ZjL01pwDF3i30chf/93d6f1fQwV4RKoPwvEMfOXrv0OAf1CAj7GfXkRMRtzvfwxCZuhb
pb4jOyELRCvtXPrcVBewKVhl/0dUXn9KbLiq/d9t7NnVPfT/e7t7e4X93wasvv73NP6Pltt/MPsz
9t+uN+3C/m8DDOLTIWuRYzT/nkdePrsgAXWuaZ/JEiE3NJQt+CakA+2+S0OX/8E6PTrkXqIbEM6Z
+4pGLRIyd0Cj0e2LIARP4lKPzTU9Z11O/RZx1fd4RCyhr4RPuMV9x4td1lH6pyfrccRV5prazocP
i+i6SpW6I2R65y3580/U3XLhuWZg9f2fyVyv2DqWYMn+b8Dez+x/FSw/7P96w64W+38bsLM2lHbU
Tj1+fXF5eHJyeHl8+pq8OD0nb7qxH8WW3tile+AtIepDrY+kR51IEtEDIxCxEELSlmomc1u7RbIZ
x40ul1HIu3HEhd8Z0t9E2AE9lvCrRewq+UhsGz++h48a/qzVckeHzGMUbRLsCyAEOndjz5MsYXgJ
PbgDFz3hUA++f6PDYQLf19xnEXfysGY0Q08tNeCtNGuJowFT1hgDb8kjESZgLHvc54gBbXOXOQIH
JMpS0yDSJhL2Z4sMoiiQLctyxa3vCepKU29tU4T9nF2OthTn6nC/x98zeZVF/Wg8s90PUrTwHuSE
3QyPGuRRzBs60MWEJkUIDIiAPMgjJPOjMYNHPuYQmj+FgTzTlJALRQkBSrK5YeqxADibZxsaPeow
zXpAo0GLWCxyLBCHJUUcOkyaHojedBezbUxPhj/v0gP0I4hOTReyPnsftEjlvzv/kU+BbVJJ72ua
SCW7dztgvibRGM/2tzYp63yqvKhpnH+Vx7J7zuUS4ekhE1qzeZHpKe4pqhxJ7ZCVZbW6Io1FeJc8
HBEk2dYBO7OmMMZzrCUQwBLBrmiRj2nsg+xfSd73mWt0k7YVy9CSAxqyyW1mvTx7afzr6FdD82v2
g/53K/U0atVaA7u/HZmGbsy9abuwhrHQHKMVIMu5VszC/bzFbedp+zoLHITi/RprC/9NIKuH6wp0
ZKMXLMyh83vMQ9ZqoeBaLdWz1ZqTHuincK5lcwCiTW2K6gr8l39clfNxsx7Lpbb5zB0L5U3ggl1V
Qjk8uyQOdQYs3xvEqndH9dKNix3NIvHmY9UIFqpGs7HI+H/uMKeAHFg//sfkbL06wJL4v2nv2uP6
D96v1W17r4j/twH3jv/nE4DTs6PXF28ujsjzo/PjX+D+L0cX5uYTAfI41VniYdQ9EHDLGGY+yETD
HHHflCyKgyf5WQNWGlbOGZrL8oNyizRy+6R4yojIzO3WIiJgvhLgCaMBpgQ75HgYiDDSJvrk9Kc3
F+SaJQRCKY87PPISNNAUONHuIJXLH0kQgHMcCjeGX65g0q9EhMaRMLjCB4gBjcRBCbmlSTbilnte
bh5yfvbzZC6CdDw+YX3qJE/mQ8xg2IEO2lngxX0SkjTGmMg8kOiZwCY/b1pEL0ZBn5NaFYZ9cqqn
V2vSEz94ugcimowuDZ3umb6goTMwoXWR078jlt9QcrMoI5wzBAPmeZoIZ+i2SHm8PXgvURQZhptO
nS5TOq2hpzWaxsUoQNtYKrc0uE0P4h6AW+bfyeylnjiXW4xao3GfDbGbHUBun983vrx7eZHh2N/4
Ai9KTxfxvDCJQT7V3pS5qWlzIjk1seviBOcqTy5nMFor/tu0KzLWXsxMk0B3orunvbvgGOPQa28y
40RDhBGolZd2ps4WjdjfkQA0UFZKUI9yT0CHIYsGwm0HIQeBR0naqrXEbdvp76y5/cP36R3InyGN
cq5HXeAGWPm2OpWwLLUuwTVHIg1ossAFGTPuat0UeHQus1KCNu8Z1sjRUAI3PBT+ENVD9Xh1eXl2
0Tk7P/33r7C1Pnyo5Oa4FcJ75PGizPUJYR4EKJUKZsKlIhP8smD9/E8f5G3u/Me2m3sT5/91ff5T
qxX53zZgg/mfPgR+4OwvP6FLp/84ceq8an6HB0E/4IkQHgY18GyokXsi1CKH3pCecD9+D/2egak8
vYCLF8wVIYWL05A6HsvaR0Sdg+FMZoibSfCOzo5OVknvkni4Tm4H3S3X7+Und2re+WxpnTTJM3uK
f7D9v4HhUG48iLsWC5g35QVxrtw6+dSqgLeYcZaLxqjoS8t+gdMccXdH9R/EszCTupMl/DDS1D/N
hVbmaq2kaTnPO+RIqYsHkQrhI8bB/7Ib5sOViPsDwiP0yJRI0YvAMQfMd5nvJET400LCRc6UDlBr
vdJIqZobtuI0DghYETXW0nk/DlU0S30Xeg1BP5FsIcmA3jCkIU2zXHNuqVBDNQ5jSH3aXxDczKwU
jABHNYTe7uPpkU+WyXUn264N+1uCU0jYHdEAUTYV8XOU5K3F9Op+BCtF9gHrelWJB62irJznLyqu
TAvtuSC+iEZKBtpwdGJXvyUiHMmz9u1ditseKy4OWlmgdnXF7bAWVrDxX0rx6FMWaTM1pTwzWBSU
lpcckHO4UvnN1CNzqjlLsz98gynSGkaEfPNnOpQsMI8rF63G06s8bBppcxarZJEIoiUozSxVrk4g
911g75tZp/1XKJF9rvVbrQy30fVLcZqztY4VFvCLrvp9oUuYVRY3uoYZ0vsu4pdWyQTXY36dhUzU
WpeH6B9XzR6+0KLmBKw+TkcuU9sVpKF3c0VnX7qsmBdMVnTYV8lKjMyrpBZg288ZedxnGPd484/V
3Ve9EWVLT9fOLbuqnhBbsTCivYiB8I5OX6zK/7g5/2mjO+vP5LEO2+aj4plwcq0q9CztmfIDeZh+
rEtiKrHxFrovtaRN5nCtzUFG/eeu+2WwSv0X9+envAS+6vtf6v3fRg3f/2rWive/twIrr//9X/9a
+v6XXW/Ovv9l7xXPf20FplJ2tFnaOYze9CWjCL01uoKbaSLQyi5KZMJHFq8J/3Ug2//nR4fPfz4y
h+4DzLFk/9drdm327780dov3P7cC+92QWAel/YBQj/f9dtlheNJWPoAdvT+oz97FimJ2DnXm0aQr
xPW+NagDBis4KJX2XRZBPiLVs4ztMn5qVDIeDmmYHFyqIFr0MEzD7E3uW1kTdhPegYqb9j1+sE/J
IGS9dnmHdkUcGRCeG+lpTPngEG+RS4jYz/StfYse7FswbDQ+TUvGaAbi1nCFwY1YMgOPSIyeCKeO
N2Q5G0XIK3FLXEGOiT5/g9gNepOp3v/IpoC59bRTBIxn9jgIULLywYm+mCd23BfTWoosPtMXk333
LRTQvpVKGQS+s0PmRFG6RGpTUeH3DYd0m0RCeHguSCMi42B07OiywBMJPvOBy3K1MIp++zhLfW9v
b/NT3CcgKyzHpRpikmOYChFIQtXpE2w1Va8LBFZYUJ7Md/UP6g65j/kdjUQoR+e9zIVLdQ41pPhj
glocDsy5saNPpsblwCAOId9i0hzp6rUvbiEN7jN1DCZB5QAX0OrorI+9p8PAU8dAkEgM8ZFij18z
LyE+g46RgIQBKKRBpH/1eEQSEYeTT8yYpdLTp7A/bppkANxyPLe+xQOzHnc4qExipFIHFFdTZ2rA
hMPcGNgdy9kVzvJagnHTnFJfox/DSltPnj41idKBUdVdnRSr9Cl95UrrgZpZSnXmpY8IU7ZVq353
BBVH6/8Ym0onlaw82ic9RiOgnqQHouq8XgnCVPq50kYq2SZ5CSQ4nvD1mqg5YGol5yl5+cLVlZl3
796pSqD68XfSH43PpAh3BnHXhFwvFWCOHLVWmdA9w1uqmaPE8iyJBsKvZ4eloMR9BoqdgHYOzVLd
hE0SxQHk/FLeitD1UKIXF6+03Gb6400KCu04IvYjLWdUFxmDiOAujDVLDZOcxz55lzpnI0gtLTFg
uW9A10SYtPc13o7Ge/AdNIKAw/Z+yIYiYh38cUCyoRi6v9Prkdqg0iGwBvRe6+PbIAl5f6BNwhuf
q5Q1SpSlHnCH9gVsJhigOkmCqS5IztUYU0tVOtNvfLk8RNOBossMze8xbk1YaeT/XXr3n2P9BtI+
tyf8OiGL/7IKu9Prb3yOJfGfXYWYbzr+q9eK/G87cJX9ca+3+rmr1xfHP50cdZ6dvn5x/LKlvciE
k8NaLVchnLL+EUtPmrNXctIHMgDT7QD8t/aV4Fy02ecYEzxPJ8Q2Jw5DxKotBlg1Uz8V9UKE4O5b
cDWarw2XXszIj2oO9UI5mDLhjB5LGWivLaPH8klpbCZNa3RdKqkqRweLs211iTgOYzTJN4K76qGp
kbVnYQhuCkt56Bp7YM0k6VLnGt2Aeue2y30rUJ1TzwDIKtr4VjLvAK6BIRtTbn2018AtZftPF1It
CAFBbBCWdGiAD9iAqcYnLyEWgvQaPrEE7mC1PzEH0dArTTZpWtoYKyFfzwU+GaYeNyMVec0Bn1sh
6lnOEmBBx9BJb3dQdhJEDFzKIm3/miDTv9EmeYA5ltX/qs29Wftv7xZ//28rcDV6ifJtya7tmVX4
Z4+OItMwGSxsW/UrTMP/G2T7fzJP2PQcS/f/7mz9r95sNIv9vw0wVNwkW5it4dOMGBWNji4X5cqF
CSiggAIKKKCAAgoooIACCiiggAIKKKCAAgoooIACCvii4X90bx/VAHgAAA==
EOF

RUN <<EOF
    set -e
    /usr/bin/python3 -m venv /venv
    /venv/bin/pip install --upgrade pip
    # Install wheel to avoid the warning that setup.py is being used when
    # installing Ansible
    /venv/bin/pip install wheel
    /venv/bin/pip install ansible
    cat /ansible.64 | base64 -d | (cd /; tar zxf -)
EOF

# Modifying this arg value on the build command line will cause RUN to reinstall
# Globus instead of using the previous, cached iteration (if it exists). Useful
# for speeding up re-runs to get newer Globus versions.
ARG CACHEBUST=1
ARG GCS_PROXY
ARG GCS_REPO

RUN <<EOF
    ANSIBLE_CMD="/venv/bin/ansible-playbook playbook.yml"
    if [ -n "$GCS_REPO" ]; then ANSIBLE_CMD="${ANSIBLE_CMD} -e gcs_repo=${GCS_REPO}"; fi
    # Pass on proxy support if requested. Used for the pre-stable repo
    if [ -n "$GCS_PROXY" ]; then ANSIBLE_CMD="${ANSIBLE_CMD} -e gcs_proxy=${GCS_PROXY}"; fi
    (cd /ansible; ${ANSIBLE_CMD})
EOF

######################### STAGE 3 - Prepare GCS Image ##########################
LABEL maintainer="support@globus.org"

# This is the base64 compressed tar of entrypoint.sh
COPY <<EOF /entrypoint.64
H4sIAAAAAAAAA+1ZbXPbuBHO1+Ov2MieyJ6GlOSLk45bXye1dTnPxS9jO01v7joKREISThTIAqAU
Xa//vbsASJGSnJeJ005njA+WBCz2DbvPLmAujVrmmZAm0pNHX2d0cbw4PKTP3ovDbv2Tvj7vPu8+
6j17cfji2+fdbw+ePer2nnUPnz+C7lfSpzEKbZgCePQr05lkqbmL7mPr/6dj53FnKGRnyPQkCHbu
dwQ78Pbl9cXZxasjeM0KGU+EHMOrkxtYCDPJCgN6qQ2fJSA08Pc5V2LGpWFpBG80B2ZgmRUKsoUE
JfQ0Qn4n2SxnRgxTbnlYZofRs+ig94d71z4gA24nHHKm2IwbrjQsOEjOEzAZpNYiaMss4aC5KfI2
MEXUWiOFkDAXDLicC5VJsgu5zZkSDJXXaAvyh91Xry//+uZmcPL6rH9xOzg7hWP4c5wKpB6I5LtN
ipv+yXX/tkaleay4sZSn/avXlz+dE9mP/Z+IhsvEpvYg4XmaLUmJwZQvLfXF5Wkf2d2+uRq8vH51
g+RZbgSFOFox1jDKVNO2Pf4+gjAUeciSRHGt92vq3Zz+OOhf/O3s+vKCFKhzS/icp1lOwhveCMQI
fobwN2hteKEF/wjMhMsAcPB4kkHrXGhN0VPjUHkT2usM2hH03wtjcEfUclzwJ/SCkbhbrvPtF8p2
TD5RfvPEPltyc/sHZd53buzAzW3/CnpHmJFyJMYFBj7qDjZgKHRepdmw0DBcgiqkJBvqwfR1cvUi
UzOWpsun0B5b8WGcScljE2qu5lxBPZwXIk0hL/BPQgBTKt/WXnXkF3vTGEUyMJmUOY9CEAZizAGm
lpBmMYY5iRA4FcEP2QJDXj0FPLqYE2QgLCC7Raam5AimsgJ5kcQCYS4brWBQQqYSVBThZcLmuFFC
IXMl5iLlYwQV1MgwIZE58eOOyBLLJLUngAyRV64BkVPzdF5BjYNdVDye8Hhqz4g0wBhBetIT9TAT
BOKRSC3PGZsiL3ewOC3IIwwn8jxTBnXJU2aQyyyCc6LEUGMwsnsy3IHgjfrFaIDXzfsHmXgn1hRU
MwhHYAuRc0Vs0iCVEGo3aVTB15eR0RVWECoQK3QDRDf0ImrPnB2LCUcDGjhGOinOUANhgiYwHrc6
q4kQJ6Jfsei3ApuM6/j6Hew2dwfxZJYl8Lzb3VgJPhaPlK7wi83aMGzqsM7Mk60DuMeV3b9AKDl0
N7GkJmzE0DeJw4v/JlwclH2ATaZZJoXBMCwzh8Ifi1pRy4ivgBOkzc5OqQdlxTmTbMyVXbKuajeb
Fb/eLhsCmww2eV5enUGuMgICF/IIDNlCU9tCGcSSmZCUXj7VfDXeRBbqKzAz8ZMV2Bgp8RvJRnBQ
JV8MYhaTHFqwXVGNW2FnScStYlKPeOVTn/slvvD3PC4Menoc68HMmRXpLJ5yY08EWwlGyx3E7M46
DaCmKBjZDfmEpaMIzgw5oqBuh+AkzmazQorYGTXkZsE5GpdjqvHOxJg8sUJIz5pbqauz8oiXzBA2
lDC2vmHtQB0WfAjULI4nBCwYoZS/ROeUtey8CcIgoIwi17Upjjrxp4RCs2zeoNsjNXKRWIjYtyeF
uDaERChMzgwhnQjGYm4VPSeoRZ3KE4iIu7To5jTAzctZKuS0splkZakzV/KFrRDkFI0aIDd3pHW/
kE3aEDqPhHeR0zUKgtkU9do4EgQbKlvOQUfeTxtEHkPXpjv2OLceMkWLTw2rhA8juOEIwKkYegBO
/Gdzv0f4PYsmcQId7AE7Dvk6eoIx3EEl/2RXUTaFN4RFecbhuPoWNnYS7I8prjIlPfY5mKR6Shny
DD4+fgm+CcNcYSPK8FhyMWB5/vENCeMIUp/AvtyAuibHqOv7o+0+31QJo3CDFCeDfTqJtwzjvazU
ZcBiTRN4PFqMsbvGiCpsVI6K1BfWANeR6md4bIvqFuZYG5LMOlKnnOfQjQ5xQvKgRjdAuuN3GLZb
ObwLbLu1wGaCyTGnKxqexETkrouoMq1sBVyw2zCnlkcYStJPiinLp1ZZO9j+bvWtb6vR4kLjDEWN
k3pQL4U7cMqHgsnOm2EhTeGaaWmwB7Exa3NqsVjgyRt2VH75gFCeau4ZX/METe2cYJm+vOl8z5NM
sa38nVpH3id38/aFeL1cvcQioA0j5L+jYFUUVLJcwSqrlF7KuOxw16pQCV7UJ2gL7rZd1Jz63myM
nGbU8I6xPiBiapPQBd7FIpWnQhfUe+MZI1QbAu+y6hAKamrOMmrMXDlChihCIgFLnlJBa1tRZQuL
yytp9qLfTigSFK3oNnaMn4kfW9svVvoJnjRCv5q3SbD7ONg4h5fu7Cx4bz2GOkE7+MLY9IVWs5Ft
zCmD3Hbqg2nnOlucB3rWMnYVjSDcOK4izcsuPyPCm08NZEtjzXHwwk3cyaeiY1LdibkyumOvQ5NM
myhWBu2jDZWNToJjDX/EK1GBZdLeYnBTSg8rE9tbKVfwq26/3GstRcygTsbVzlDrNBzTDUZ57TBv
nJiVM9Bleo3bymfuFLd6yi65v9ZLlJINeN31W+6EVLt3BaYl/bvN1FYi+f72antSuzVETIrb9sei
32QFMrRGELxuDX6Cm7CEmzHyH5mcbhvByi9+X7nok8ZfUm7KL7GLAU8VEaaUSyfNpaScL33mYG+b
FOvsbYXsLuK7S5ojXS9nd/F5F3yNy49tRymF40IpjH2ESZmVV2lb4C/PTk/WX0Wj+7/9jDCiLNgL
PfAlYcBSbHT39oN/WfdNCfNDvMH28IKLt+F5R9IbycF3T3rBv2sM7CtCyaPavUP7QrhgsxJMdg/w
99XZaeCAY00sLq8ApXZ13cAMd4VF5nRJpdeHQtKDcYxf02WrIlN4vcUusVfHAT/XJfX1pLAPZAN6
8znu1sxJOZNFXhni5N14cvtEFEX+ntxk4mQZxXI09LZ/fV7/3f/72W1QbSL6Qa3QoALbnbLWh8GT
J9v392rO20YAIf8n9O725y1XeENlZu2mC3skdF2L/ZWbXZCQsRtUQUU0EkpjBcVi6vWk4VL6qPrt
k7Ycn+SKIV67psE3RL+3t7sSs79Pq84y6pzJKjzaumFYPSmAWm53TcNuTSPJ19xU5zBhuozBVhll
LtTvMU9d6rzlqIy7Epf3gLIQGH/Pt60Y3rvzlBse3bsetVS49q+49hXJZwtUKfGB5y1PS9lnk6Lc
a1OlMWOTxc602/DDm6vq+9kFJtHqKKpH0NrdBxHVvZLRsZR1Y7eRqTYZuqtC0UAwaNU7thbsVnUb
fv99a8avba/FSGszaj+bx6qHX+PW6E238V2DhKb5W7GgPCF72GUbaDHLltIKTG1m/K//X/kwHsbD
eBgP42E8jIfxML5s/Aebis1+ACgAAA==
EOF

RUN <<EOF
    cat /entrypoint.64 | base64 -d | tar zxf - > /entrypoint.sh
EOF

# These are the default ports in use by GCSv5.4. Currently, they can not be changed.
#   443 : HTTPD service for GCS Manager API and HTTPS access to collections
#  50000-51000 : Default port range for incoming data transfer tasks
EXPOSE 443/tcp 50000-51000/tcp

# Default command unless overridden with 'docker run --entrypoint'
ENTRYPOINT ["/entrypoint.sh"]
# Default options to ENTRYPOINT unless overridden with 'docker run arg1...'
CMD []
