# syntax=docker/dockerfile:1.3-labs

######################## STAGE 0 - Build the base image ####################### 

ARG BOOTSTRAP_IMAGE=almalinux:9
ARG YUM_OPTIONS='-c /yum/centos-9.repo --releasever=9-stream'
ARG RELEASE_PKG=centos-release

################################################################################
# We build the target image in 2 phases:
#
# - The first stage will create a root of the target distro using the base
#   image's commands. This results in a root that contains the yum/rpm commands
#   of the target distro but with a rpm database in the format used by the base
#   distro.
# - The second stage will copy the root to / to create the final image.
#
# We'll want to do this twice if the BOOTSTRAP_IMAGE is a different major number
# than the target image because the yum/rpm database format changes between
# releases so we'll want the final image to have been built by that distro's
# tools.
################################################################################

# Stage 1: Install the target distro into /$ROOT
FROM ${BOOTSTRAP_IMAGE} as stage_build_root

ARG RELEASE_PKGS
ARG YUM_OPTIONS

ARG ROOT=/ROOT

# This is the base64 of partials/yum/
COPY <<EOF /yum.64
H4sIAAAAAAAAA+27ee/jyJUl6r/5KRLoRmMGmirupNhAocFdXMR9bzwMuIvivojbpx9mll0ul+22
3eN2v4dXF1CKqaAieBVx7znnRvyOTwv+5r/YoMtIHP/2ftkv379dwxiJkygBoQj2GwiGMAj+zRf8
v/rBvtpnXuLpy5ffTH2//Ef3/aX2/4/acc2/ZTy/Ew3xO4UPv2PzbtHtv+8YXyeYwLA/N/8E+Ufz
j8I4+Zsv0N/3Mf60/f98/v/pi53nX17LMsz/CoLpNfv9/H0/lWCdHzMIAP/0Z9v+eNV8RwLffTWG
FyXtiyEaXwyXUSX2y3XLF0bVWeVbM+Dl01z13b9+EbuPIX5Z4e+x7/Ev/0PUXFCtus/+PwGgNSWN
EfQOhGaGpzmVO6IbZz7q1Hlwps1DMcQgVUjzwTYY60yQqYwt7SsHq6d+eM8XBYQbuDKScJ/TlnDA
1dDwoh9mpfIpd6ZfolJC+cASB55nN412Hw4fE4OtZz3JHgK3LR2APQQC5ucjwcrTcAizsifoXDNn
KUPGit40bwjeB+WqHuoj3DUjsjizqMir/WnevadjAtiB7fha1RRzS8dWrEaK9km42hsu9Px4Li2I
Qoug4ihNdTDOWZSbooqh9pbv+dMaiwjwZ7Ik2RsV8+KjmMUItHdV/7Q7KBaV0/RxA2XdeHdYMjBB
+aNlDDW+++C0hFsRc+78BvzPqtkmP7qBD2en/GbWqefX0skKVi6sQSr1KUVwYly55wDbe/p6Cs1i
ND3eJvZT+cDADg+YW9PnjmNomz8bK9DLHQFfHdMSD0KFhNk+OJswEAQ7hBsK5bnOcZj8wRj2MKG3
DkiDu7duRw892EK5lTcS4VgN+VaIWBzt0NVeAvMRdttQSiVkBuHlndaTQOV5rZI7MoUAht5HdJZ0
N9ujkBjWp+5bdeZ6/Un6DL872Y5rixhgdebj5pKaj+cNqV8LMTPd1UnKAHKYhtJGuzmNr5lVbKry
iTrCLmlXycpcXz7FLTUsFOSJuxpN5B2zm76uHupi1kVN3d+AFrREIb+DTV636olIlXCU99jdeJ4L
cPdm6iwNbeFUuib4ulfx8loZWbFT6m3SFm3SDLDwMhf5OOTAz0U7GDUK6lLhtSbpLMM9aFTiqTZq
m3fsC7MkaEOE4EPSpqWNeLhi03cgRbx3FshD9mjoEPE+mUidaksd0UnI9Nvl+Y1naeYu0M23eGHF
7SmyWy0x25NlGJcFWPrJCaXE0C/seuU0TfcyzzriqBTQSBOwo0EGiJAo5Lzu6fOWwQOva2QHCXBY
HfsoAua5DSwivCbEleZgqMDGdwJJJOjGWqf4/RZeG/Wol/DdCFj/FK8kbncSFBhZO2kI1aiAcMtz
mNayY13qDWufH+Qwt9zbXVL5YD3tGMzqW+uNGFjTcPRnju+GCEXG2xC1Sob2DcC0+VbgJiGOLYWQ
/SMYjsY1+fbzUGZ2QDMFrKN4l/VgbkdiPkK4TCb1jdDdCFW+b2CAM979Z724k5Omt9NEBsEi+5Wv
Xgpkra+2JkANu2HyRovVu3jl733TgrtDGOwnnHG5WoGXuc4SJWSS1DgGFryECNOoLuv4jcboB7lo
zNwy6INP1NG12w9iTfeXWDmI0aRYSNE6EDeVD9f6c46EcApQqp4Kq0Y6RAvWKjdlsNlQ+F7aokWQ
n7SuTyTK64TlhzcItd3D5wDUIjyypXCLcMPxnW63m4mzS4QsZ7v3beQUGCKJksIkttdKNon74S1l
XNXdUSONwgcHRCOdMBDXYM8k4x/E9TDSnU800FEbuIJIcrpRamDBrd41LCqqHITegiK85zxjFiSM
kkBoPysfn0B838ya3PlUaZIoa115QCPOMZnAgYg1XtcBfTf1OD4oU+fvXhVFRKyY6rgCg3rDkhlH
3udH3JynQ5a6hT9P7rY6UOHZZNDen299X6Myecx0eR6C2EhweQVX65LNBwU+hqZeiWTHbFjE5A4H
ftDFMPgRdniN+w9A52+EMr0oqrSKmy//48cPvtxv//M/h27I99D3CPKn4O18+nv9Fd4e01wPTKlR
+vBqX1adkgYYTjMt2uvakHXxueWUQscuUeDPnPaODpik/omh83GIdSkcfvmOnndw+kwk/zRC5Fhu
yAjCUaF6rNVRd5yQR0caocAaODfHOsUE7kxDkxvnRb3N7W5U2x9HOvg94QooHbY75aQFgTz3trq/
XyS2Wo1xwEb59lUco7AEDQC82Lkqe2DJaETH7jCjMbnCp7/xhevxYyUKFGYMIxG568SIutfDHnyT
ipZiRV7BKTIF4nxNxRS2hKbcpVK7Y+7w4d6GRYGn3WWbTAZzEK4R8QhSRYxLS5mLkPNFo6bxVFfB
HChuh57oHYuhh+GuQ1mamBJrMnGzn06kK1X9vB9pdTCbOm7Tu78LjVzW690r4hJEXIsEZElLjvHx
6FX3ZSIXpAX2pmDhe9mqTKB4t46ZyJ+uuQktVLIiNWj8Mdcr8Jafoe5DLbB+iqlO1/l1c5TG87rP
1vLGBeDt5trDrGaFIfcw95izu2BDqM0qRhwIGUfmRsG/q7AGusdgxgoPwbHv2apbHWVHCuQU5q04
epS3kAuz4cMJraPNkkiM8+gpnJL0eexETGvTAYjxgsaji44LE+gTDWZGHVCpz99cC996kEbcTJEj
tRFfT8S3ZLRZWtHB7h7F5jahUSHQYqySnWtJ8v67cRphysC7LyNKP+o81eSckQeW0aWfRC5kQlWl
xyFC1IuqlZ/gjRt+B28/gzXGiNpoCJHmlbCME/vZJ/bxTuKXJrfr0nhoTYh6RxxYOGCK3760pge+
pm16q0wJZZgnQ5f0izHl9BTmiH7NHFPOMkunHF2GHktLMlvO31AN+ANYo33YS3S+vEfZW58vWDtK
e39Q77EodJeylUPmmilWkVL6LGOEMvehAcQDNLuEMjmYl70Ei3adf6Uh4lOeXEhDV6AH86GXnjxX
JQdFuNsfGLMQviObbO2+0xnQ0NHw5x325mam+ZNMArF6HC1BXxRQQO6JSQWh1NeSGWSQg0wcCjaa
uGuLbkVIorw5YNXP8FxfSJW5UghzpejLMFwuD0GiKXZ9pP61pg3+VadKJNM6DseHwIyObQ9VP3mb
MwIxlF40s2xZU5cw8Bneamk9+3wvRHJ/1e6YQ9veDi/KMs29cRLN5Ngs3u1ySwTEuZUbkBwxt9Y2
ti8WYfdvklHeCt2mXYEXHcbi+gQpqjs+T2bhnklhmtWrI5AqkjUiikAsK4ERezjj4Q3H53wGszDI
lAoK4wPhZCzfRXFgVghKYjCKPwcpzqOe4kZ3YWYYP9ihOaAAwCCSs3YcXqhwCyVwWby4+eSvkbqV
ljzojqMMBP2OOjDGwwV9EW+uHLTiCfKHKkghdQIewQajaYJ32VrjqgblWWSLi3iokb5hdS+9I5Gn
SwirPofmvF87lIPmg/fSkB419RWIwMQ6TsJ2qGa7OjXufMDeFBBu4ToOelakIddvPDGCZbsqkuS5
Qxc3ApNp4CPDDdsbigD9PSiSPmX85i248o2Im7ezRqhqqopjGz7pCPpNDI6U1ltWfDXBC1malKic
FIMNmh0P4Dhu7aO1V+CHun6Qfw2s/d/qv1/qf6tP6+PvISx/Zn9R/xPoH+n/6+1X/f8PsN+Tounr
zDdfCcqf1v9Z8/0vbhk+yY/f+uMV9N39ryNLPzIhke6LM7yY0KXIbTg+N6JAtzb2MhBEY/sgdCSl
bu88Xz6NZa4loq4vy7LhXBsHANypJWFeRf/6gEvD1eIQPjwyq3KjfLYNZUfcAc9KI6EL99oJMUL3
TYCKDF59JhparQY4qrRqtw2ZXO2XNg3M6B4Nvlql/Sxc4Cbz4XDxg49UOsq2YOUuT4+19mfRrJha
3hUO+KCg1aiYFNKovlDVh2WKJqVg/qA3OHxDpZJyZ6KP77URFxul7aDcjdEuXOijspRrC8BH4ToD
WdKuURSxeEMfwqtHyW4q+2PR57tRXj31zPsuu7VPSbgyITEO2H58bhT3Rq+0BkgsMTGB5aJ7dT+h
MRyWXoiI105Cmod/blDgntwzyN4mbt9xygplpXpXW1s8WbKMTLoA9DrT0yrVzrwDnY0D5+ZVsdw8
PxiNz++Ev33wuuV6dqpIUW5CvfFdDAkqqIfl2msWDeDukZTdeIaT2pn8lPZ2UT57P6IZQ0dEogsh
ZK3lUB4X2XswVk6BiuMb7tTNhbKLcskCXI+GCYGCUuishSMPi1e8zEWF6RdP5wIs3ZKP18tWy/BH
qHAUk7nYbmoo5U2RclY6Crw4SexKMFcIIzZebjYSwbi23Rwhr5viJUf/xlKnR0qFZZCAJnXkoZrz
R8w+jzNUtHcBmBb1hrL3e3OmeRXXs+DP9GXAFImga1iQYpaq67gY4znsdoAIGm0NrBgwG7X9xIQ0
O/L3Jgy0RuK9T4Q0n8i/WM5X5sPtl6iPjqsNSrtLzz+8I3KZI0G0Kfevts7DgJ9EfY19FfUSzZW+
ZFqbm1rbaHeQ9yRuGpl6E4zMSWDFIe2yIfsCtVJKuM1VAdYsH9/oUVlL7CbxFz3iaFPKr1dQ0rTC
WvTvv6wK7RVw9nPtdVjgsoNOPgDcEjt/cq+ZFMouyk3tVCOeXZH3rSwFWw7ys9E8PcIlWLp/Wibu
kGMrFJO7P2/Su518oKZA8kVVOLbcLRu0NFLRepJnxU4JxoAzToZxZljcetg/m4XuY05xiwu0sV7G
YtYARwAMDM/nz3KQdTjg83Nlx7sXVPNnObgq4N/vp5Qz6bkn8CuJWzO4vVVHMuHnRTOiHg4N4Gzc
cXr4GIoFLJLAoJ/Y8dFc6r+m0npOY1y+lagwOk1Z+f15HNBnP0rJeicXDp9KUAMeaYd7HgzoS3M+
vVtWQv1+4SB0KD677WRsjs0jnijxPewtw9E6VJ96Uy7OBoL86GwWoHRhpFYlJfiQ8drWSHarcoIu
mQAGwUUwSPIEKzArHvX09hwnzDvtCPrSWJzFvhhFGgMEXCRGATGgjWoYavh31woYy4bmox4CzN6V
z83YFHYsbrpMvp68R8fDeDoLPFIOeR4MYG4r6+33mfT9NUhmJLtk2ERPdVO+H/3DTLNdVrLXx2o5
FKM/gc+q/q183CfZj4aP1qDAzZ+NKMCM9a1w5XMjwmfqkefLD4gUsvNVWc6F9A006BXuY7wU2HiK
sjma5DzkpcjccICL1lm2sbs0QDaGm0X7viNVEsQsIz8cLeLv0XybMudtUpyNj+tp0fB8vTImAUld
DXlAbnO/wLzoyJP2VqY4NJ9zSbgLcjj31/bDD8APdGXc/yrh/5+FMOpv1PtTPhffX7BZ5/mQT9+v
MMD2bZt3y79+UX73KQDss3ABnoxb9bfKtgCq5zy35Gc6POLmXeGrokTdHKyXPrZ1p5j6jqMqo38e
Hh/5c5sDdSILaGGKZEWWBauIHw8PfBjfJc3pc6xgnFe05KJ8VklvR9ZQ8yZyok2YJuUVEuQtA9L+
jqJNzWjlCa+EqZNGS2chuJOESTx2SKaOSvazG/a+rVaFvRL/8yKw1V2cjJyMrb4D0IGWWK/AoQNp
FhS0oHnx5dVva9vxisYkjjvyeD0kdxJv8Gp2tj75MQvpcDO6Eqp9eiAh3g5tsW0SG3N1CzyzY5K5
M4yRcJJmS29aKNvjG8+ozoE+fOCQUb++MTnHe98TgoECDFj366RHTjyolXef98kTPBWOt2WLvL9u
oUlrlKQrwlsFP6B4TjXc8yVzsPSlkoPbAwdexSedRtxFkyRVDizHl7DsumgfB15d0UIDkeZeRXX3
4F94HGoO7gfeY+DA+weZnu3WAhIVOvzzk/NL6x1Q5KH94F55gL2hkbu925WWl6yQj9zzQe95oI8N
lV6QUL0peNIJGPUAsiORsvQauQoQ/B0eDkYHTSwWtP7sMlnzSmaYIYuedCac5UuCr8WjUSs8Ld5e
Rq7hDpgvMaB0LvyshwxOPgllT6+qc/vdMJxiQ/dlzUa9XKrwwI7XEmLV22QppmV56kGV+u4CgoZQ
ZKVWLb1PEO/NPEcRhUFdc8CJkurPhfzZ6bUf22sNNetdvhkwKJBLj/xO+p+XoP4GYDYjXAq+STvm
kvQX+AnaGnUWGgbyBYTRmvl4HQbWkCBYqdrMTyAJSOLXegB9PDnpuBDy+NqQtBmdttQ7Rpv5Qk44
Z38sC2yzqHwtC7A0DTGmXOVupAJCxfNSOjfxR1h3d/9EdiOnLMwmjqvJMPS1FM4+ygt/TJ5jt/pB
v1yJ3kOaLqXqckEBWIvZVFdeNBPqAt/EOZDCSGTO9cPSCRBMTKSb0Y1q+FvsqI2MsyEk2k6C7drn
WG80B0jBUK6q/VwcCyoGSvTQ9cqXpuTP+YsbF1LHd8WvbugSZvHXnwBO1+51n8CeTVcJ+6hAfa+l
Vivn/ca+b9mk5GYPoauwMw5XwYxjCnXBLyhS0Ai94WWYinzzJGFy1p700xT4B2DcdB9/hdwDq1M1
WdxjMAIhSQM3iQvi7b6Lih/wRn2P4+ekD85Qm/p8TrjlxVSHgpMEWIRuXnf0hneyVvQsOZVWGRdx
UiFQPeNGvGj/Pj5JMr2N4KQfs3ELs4uHiHQGFSu/0kBb5DQWEpkBtU/rQxE8T8vwaCuC734aQiG6
z3jcZGevl2G7C6DE0CeGdTFMOgWEPOUHILKufzyhDl8/Ol4rt7Cu6y27rRgaNSPXbSIZ11ytbuWb
0CFT2xFHrLNyQW8sET803AaelQAN1cV8k0qjVB3KIZyukAk9HYEFBza+FLkIDy/kvcMDd8WD6xnF
vPmCVuS4dMMqgH0+DEuYIy3czU6iEWNaygUJn9uJepIoEZwDRjgh9+OG5XoRy45j2gFLa8sMlhw5
+gCH2lFgpORmcgTqDBz/lrPx1eZD7PBssmvkDg43cZOi0Je1Gx2+1qkQg+L9ydCc+9xBoLqFUmIo
D9i5MsBWHTsLQ0QrqSSEDzfdKvCTdqLnwdxDSF8t6cRjpWY4IXoipkbQXwHROKXiby4Z/FL/28NU
dWUWN/nfT2P+x/ofhgkC/4X+x2AE+VX//yPsn778fsa/kF/+5cv9t3zpokvzTy3ff71K86Xvvs+z
D5jFS/yzVpAE9zvxvwkM7P9wL+X3t/znt05g7I+2TlSGP191+7VgwMG3eKk77QV/igQyI01piM+z
0ztaRZL6vhJe614sW3NkQmaCzOIDoG89q+G5FZY3CoThheMlSD6jKh/7Mn7JqMiNvBa81KYYyny9
hQ/eJt7T4x7wYV1d8hjY9o97KOvY0zUBbSNLuCvo1I/B00OD8h+LlhxJgxqfe4Es55hNPAI9WrPk
T+/tHA9+A1DUz+nAb14X95SeqQzmWQ2BLxMKP7BmoVgJWiAcn8WJfY4dGpfJ4dbYJsc9wCPbDSNg
eZz2XX4Lw2k9JJS+3eSVOIJnduZ1h2NO2Cc3Lld6a86WQoKU6dDXG4Us6YYdTxRnFSDDLsVwX1B8
xYlttoLX5kU+H3YoU0hzdgl9AQuCx73bIQZW5KoiPmEPV9UhuTCUOrcSCFnDk07nxoDCSLfNsqOe
XN7JOSJMTxjQXlgkvfnAmGYyK7qNbpezmnK/8xG9V2A9HkAtqCOmFf7QIZkXhVYjZ5nvBNFtHOPQ
JGKJehzijoOmI8GveU/1o57a+9ZH67CEuWUCUlFzglGOTps5oxCruGOmGCqsujrPVM3IiGAnFeoP
liT7EEibYkqBFGm7HQs5EInrgIWmyi0zVwk1PRQcYJfvt6CxH5yQ4uw0Kg4Mn0+RUnjMFVvofnDJ
CWW4lDwgdjg/9QdYq+zNXCTFBG96k71t4f14sYJ64hfaHjGRPwcjtlNeGXtfC8+PtlI1V3p+oG20
qCSWBriCJ5ves3TE5pMFZWmJzZk95CHsPCj2qY/EvmyXh0rbx6HIz75tl/z2hMDrawEBiL7tpTBw
7AunKcKvTCw/6dVB0mpNJlIftfXqzPl6SsD87SkBTKDrb7Hz7ZQA8LtjAvTusvT29OmLK33lSwJG
02xZm8IMck9IrFm3QpCdppc+FwxrCC/lPhI36wN0VoCLLGc2BNfoi7erXtpo0SkO3Xbn96XKbrSu
jlyQFl16FBAWvhr+8cbaaj7BiWMlIMYTy++1t3Epn8dwspdCkYhBm+BXSNm6T2EMn3UlJYmiAgUv
gTmLpj3sr1UJikeiMAes0lfklEuOJzVzKVJiGCSxdXfndN9ZlWdqkgVEn+FCW0HR0vxzLMdT827Q
xsltxj9CgJyqAofde8LqSjeDrqDYNOqPrvK6+Aiy95jujXV7SzwRPSFMsWjJ9aVIUu7Wgx+IrQbS
ppnvcRHan0JuWzdPz4QHtyuLlE+bR0exSU1rd3SUf+pWgnab3+MmTWMSaBrCJPQsYEZmEquavt8N
MusKro8neXKNkGFcoX0q68Pt7G0lKMKMXicJWWv5dh5pYh9T1/IkwQJg4EKnO+S+Rgj81wIDDQ9S
M3oF9hqt+WawsYjMx8KYXsgPYSl2vWvYvuRgMaHJS3cD/E1+6KMVTqLoPKGI8EipfNL1WG08z3Z4
zrlB+Bo3dz4+Xp3kOuM7KdG9ZkN6oCZ7J4BZhQIQfp2Lgc9X+uhywg7RAJWOslnpYZ2VDnL01GPX
JNReSYkkhZGtRbvY9BV71dMFDmND5LJIVzUX4KV6mmSFG0V56B0UomATvdO0CR8xbOAG3zssjTQu
+VZbqGlLaXphGrCGHMSJVuSIGi+HLhcJpXUcnaTv9cWNWqVP/8piwc/w8N/+7W+qYitPbi2/glLw
sTpItYZhW90Hob7rdwp5BJIwvCKFrXCFBgf5Ump7pXb9AjRWA48A2VAUf3MRjZeeune7ienr7POm
ia2fO6PSBF185IfTgRGE6hr+gigom9iim5GYD3vAcCwGZaYzPl8x34WC7LrUWc0aPBz3vKo2yZls
LoFAbnsLW9JTZpSIyRq94L1rZV3MgLuNc2etl8w7Q2+QdItLN4jWTsgt+vBJ8cGR92lWpfYNStVL
nCDQ2ByWkTFTWYmOlipgtBzrNe7qE4aktpGVvF1bObXc6saoKw1fCruvFYk8OngTboFzPZxA6s0d
Wg/XPhrdA5zJw2figYEsE3CBiJm0uPrRJWHZ4maEZ+sfCzeAxflqR2XvPt6qmQ/7Ixyov1BTdBMA
g0rDkf0EyFQvUKF2CQZePytRG2ftPfEU73i64u1KuGfhZx/DaqJpa+g/rTFxGflwXaBmVokW7ptv
ybqfJ7kAjWzqwbwxbtpQKw+uepP3g/oUG+aA8KXptee1Llsar9OKMj0ZgBCHU6XXJdvPSi/ha9qH
8RJNMCt4jqFWy4In+tlZXtHcWOl4mNpJ+v7lEsO6i/vsE8AyHkcvtBQ4emmpRj5h0KclXJID0zKJ
W73BJust5XV/8IQ3o5SsLzWMeDcV8K08660BXPu8NBlpjWqonjn0zrjXe0KnYNBpK+t1xVZ7IoAd
dyYn3o3j8HaL12yIk+Gn/XwBdn7EkKwOLz0u8dQW+VhpfQWhQN7Stjkjm3n+qM1p/Hcg5SJNl7TN
B4gOZvp6xi1qqeNCK97h6uES9+fPO/2PwAqgrzF/LH9vvmSaHXp7P5dOkrGBM4/7G8X9JV6hQphL
lw37Tb/RUkJvrvpj9ftZAReKiYLZyyw9swwTXsj2FdXSn1CNunmTP1GPPVG6kgZBu88QuVdcZjeO
hzCPwFPrdhrNDriwj2eH7XMPjrkcEY9sKGByw0YOShpy5fy3Kj6FfOjpAo3h8eQi7WbCyh1AsVBf
9AS9eRCVFUqelDM9LM2J+/H6aghC6JH3/ePmH0tZUhUZA+h9asd8KWqvfGkXNRjffMFKyxbJlKId
jQBnomfnsJaqKBfMtBo2PgVqTlY0qPp5GLH8gPPRw3uhKjO0aRGAV+Vhyd0BQVBWQyDONi8B/Tk2
mNaXE3ErAqHE8qFSccRFeZEG9C1OYLFLNSEvGHojACU+6IZWUiouPJ1AW8fvHq84yykoPTuo33r/
6b2tYloDcAGDQFUH8cFuhl8946o1ygMob+WUxNr1dCG2pYbGjB5yLunz1cw3QUElqlhHEVENFDdH
Lm0ci3Pez/fZYohW14iEA91ZqhjaIi08Gi90GLt79XnV/OAvjCij7lmeJ3P3/ZfTU9jQk8mdzF/R
cLZNd0X+VoJAz+frY45rTDs1PFjnyF3qS6h4voobmPGMCnl8gFZYJwno88kjSss+DllBcsrMfbNV
A3zQhDSGcdrGrihuSjJkkWHwxSu6TwklPmSSJZOFzZ32RoztjXlrU5ZNlAZuu5A34usFSE/jyY8G
KO0y3LF2OeQ0Tq0OlkDwKB4rTfu0Ca5POL7V9BDeoVnV461quPlZh+QULYD/mJ/ucoyyg8y1k+0Q
eLzUdoI/PIHTJcT/uP55k1YEefO9k+QEhsbAASe5tGCaCKDbqK1EHibcdBt48AOpq7wYYLOLcywI
Ik2bXRby5v0NLY83vt+t2vRb77hfeiBM3KYD1DWihDPnbJUOyKqGF4rJ0efxLrxHU5jC9lKrHVkW
cbTnnjuXoLnr/iM9nfXGLhYkDoAQSJ+5vtcrZnRybD+WS9h016pEdcw9BqcjGLrIrXCm5AlTvf5p
9JfYctMwnpLHLQAFADo7on/AJPvqPNTQDvWi0XPp5RdXjPIhlQyyqBP/OCBKHFWNIKKq0JLyQWWR
uEgJxgAbT3t7y1BcaAYrzvEKJt+RSBUFozP7N6xOFzMz9dNzfGuSpuL23qRyAsGgHc9NZMADmI7Y
GtF7jtpPtJtoz8qYjLgfRG2bL8FLrikxaaicanPz1FeJjvVWWwqyB1NaNLq28oBztivi4sztLlbp
ImF7+gzlD5Ld9XFGETVFMciY1VJoHuNKDAj/9o1uiPxUf/S7QCE1QMtFsvul/TRCSxgw0HkHAT8n
dolm1QFJ4vDxS7O+gb2uRaSD+eLWV8JAIt7F7rV0kgGyxca0ih66g45RE+zwyN1oPxL6br5thLZD
O7cjTli+6kCVBo/h77E9qcmsaQHkKJoGMI9Hec/GoXTQ0IUd2Fid4CM7rYjVy5jfvbAQiacjOW9J
es0RAquujr7rwCfjiT36mQeYd/ywo8i/rWk5meF6QHJBMzxD0+IlUEJepK+Uz9J/NuUDv8z53Lcd
Te73eDA2ykW+vEJ08NejFXhD6dvEGrmEPsE4dYEge+PzpdN8x7Jep7KzfH+x7fmhEFE5sbYWRTcN
NxzQx+2aUE1itebORB3nHMJNnXUQMIjqwy1OFiP5R7w19McF1/MthUJ3Q1WZxDhdygx3Nz+zVcp2
lTattY0jTKlopr5ttQQ+Bdv0YqkzWcHm4QgZlAfRlwTSVyjnJSRy+jXpWevRiwf3LHdZhW8QMUpi
HSQf6x5EQOqu5KLLdMiW3GOP3RaXohT0Ds2X1fjjfih2oNDVh/WMW+5P7baSYlKklxhNoFQUrRug
6xNOh+LhO/H4MMAcwutaRRf642nP46JvVu/WaS1cHHEGeaa6fpHb/eHo+PHJsygOX4CCPlsVWS2l
qZponfNAfuuK3zgkDe/t6ngF1RCRpeP8bSFAhsL0qqf6elP0xeA1cR8BUduGF+jRAQdWZd+TXHZe
eo5rmtBjrMcgzVK7nHMig6rttwIVh1KPmSDtLcIuIicaA6UWtXoCxZxRrWT2uTmn3CXxQjUJwjcp
zGwXHXo+mqNID+OCkmK+ierL0MKRkwRvoCdg4CUtnz/z6+KSHUOjylMq4nIQ9vzKClyxO4aftLfO
K5Ys37XBV8koqpvcRww9s1ofAYK3E9sdlGhgkpzjCyYG3uCrSVG6ONjvpc3jUjiqo85S4YZVocSE
0/leGT1u9rfnYHdAnJYqfQxw0NBdfjL48W1HE+5o7K8SKX/H+t/X+u+Px6G/o76fLirzd+z7d/YX
zn9BJEb8ov6LkBj0a/33H2H//tvJT+I57+f/B+jiNv/ht0fe7WXK4/bLP095k1/Naz59+e4Lc13p
NtDmS9xUXf3D7/bW22qa+mn+/mdn6393z799XVc//MFA3/3z/K3zf4mn9PXDP3/98OvVvwxTv/Rp
3/zY7f/6+i9QDmWdHz8UVZNf44B/+i8Wv96VvvK0/gEGvg73v3/2/7yLkybPrivgd+7Gw/DjA/wV
HtPD8OPn/3mnfxruv8nvPz//X3v92ZmI/5IM8Jfin8CRX57/xKFf93/+Ifbvv5/8P8wB387AfPm2
6/JnMsC3td9U8/JH4fCLQza/v/PffrHsv8XIj/1997NBgD+5iP9CPHx74CvCf+bQL6P8z/v0sxj/
e7n1U5d/J8/+a+b/61g/2+f7b4l/EoV/Gf8YAv8a//8I+/c5a/4w8H9W/077Kf8W7r+Ilp9W+i+j
5W/ZNP5Zl+BPHX7dQf4xH/wsvP4wUn4XPn8haH7vxpUTfu/kd5/hepD8zznr/tj6X+Hvbwf+A79/
6+rv3f/7Of3fvbB+tV/tV/vVfrVf7Vf71X61X+1X+3+d/R+liMq+AFAAAA==
EOF

RUN <<EOF
    set -e

    # Yum repo definitions
    cat /yum.64 | base64 -d | (cd /; tar zxf -)
    mkdir -p ${ROOT}/var/lib/rpm
    rpm --root ${ROOT} --initdb

    # Create these /dev/ entries to avoid 3rd party postinstall warnings
    DEV_LIST="null urandom"

    # Create /dev/ in ROOT
    if [ ! -d ${ROOT}/dev ]; then
        mkdir ${ROOT}/dev
        chmod 755 ${ROOT}/dev
    fi

    # Create the /dev/ entries we need
    for dev in ${DEV_LIST}; do
        if [ ! -c ${ROOT}/dev/${dev} ]; then
            mknod ${ROOT}/dev/${dev} c `stat /dev/${dev} --format="%t %T"`
            chmod 666 ${ROOT}/dev/${dev}
            declare ${dev}_CREATED=1
        fi
    done

    yum -y ${YUM_OPTIONS} --installroot ${ROOT} install ${RELEASE_PKGS} yum

    # Delete any /dev/ entries we create above since they may have incorrect
    # major/minor device numbers for the target distro (they'll have the major/minor
    # device numbers of the bootstrap distro).
    for dev in ${DEV_LIST}; do
        varname=${dev}_CREATED
        if [ "${!varname}" = "1" ]; then
            rm -f /dev/${dev}
        fi
    done
EOF

# Stage 2: Copy /$ROOT from stage 1 to /
FROM scratch as base_image

ARG ROOT=/ROOT
COPY --from=stage_build_root ${ROOT} /

############## STAGE 1 - Prepare the image for GCS installation ################
FROM base_image

# Prereqs
RUN <<EOF
    dnf install -y coreutils gzip python3 sudo tar util-linux
EOF

##################### STAGE 2 - Install GCS using Ansible ######################
# This is the base64 compressed tar of the ansible repo directory
COPY <<EOF /ansible.64
H4sIAAAAAAAAA+1ce3PbNhLP3/wUOPk6SnIlqafVqpLv3MRJPOfGHsvpXMeXUyASklBTBEuQdtQm
3/12AVJvRZQfStJyM5EoEASwDyz2twRMfcl7HrMfPSCVgBr1uvoGWvxW1+Vao96o7peqldqjUrlc
KdUekfpDDiqlWEY0JORRKET0qXqb7n+lRBP9h8Jj8oGsYHv9V6rVUq7/XdC8/gee6MXSdITvMycy
JQuvWXhnq9he//v1+n6u/11QFv27rE9jL7q1e8ik/3qptN8olUul6qNSpVStVXL974K20v+Ict8a
j7wt+0AF79dq6/W/vz8//ytgADD/Sw/C8QL9xfW/R4B/MIAPsZ9cRExG3B98CEJm6iJj4MhuyALR
TCobn3vUOd0XZZn/EZVXd4kNs/r/RrlWr+6D/y839ht5/L8Tyq5/jg7C88ARuEMabbMMfNr/l0sN
uJf4/1q5VAb/D8t/7v93Qntbk7FHFB2/7lwcnpwcXhyfviYvTs/JOXNf0Yg8Pzo//hlKfz7qWMYt
mjewh0NtlqRPnUgS0Sfcj1gIK1NT3SaJ2XaF7PbpiHvjZtr9B9IJQli/XArr1ExNl8so5L044sLv
juivIuyCbUv41STfwVPfw/9aCT/K6x5rkkNvRE+4H7+Hes+YH5124OIFc0VI4eI0pI7H0vuT8ZwL
52q8MC7gkhyPAhFGJBoycnR2dEKu2Jiw94HHHR55Y9JjDo0lU/dTcYzjERkJN4ZLVzDpFyNC40iY
XDUFbUIbEp8Ykxs6xuq26/fJDfc8wyQ+HbEmOdbzeNrv+dlPBFd3ySMRjrEJg2DvAmuPmYRfYTDq
QnnTQMXjBRlGUSCbtu16Vl/xH4TiV/AZlggHdhD3bBYwz4amzZdnL81/H/1iYl/mH39kUAj5+BE6
uhkyX3dornyG/K1NClr2BWM9d1POlrgC8egO9KPZWMIPM2Qeo5KZHsVoKTNXli9o6AwtEKfqF4Ya
QccQaUkwpq153iNHylw8Ho0JnzDOJWHXzIcrEQ+GhEcESiiRoh8RF4bvu8x3xkT480JCJadGB01r
u9KNUtU3zML5NjiT2DSsFn0+iEOMDGHULtQagX3isIUkQ3rNcAzwGyu41pKq0EJ1G+aI+nTAwk2a
gidgjRpBbffx/JNPNsl1L52utfI/CHYhYXZEQ2yyrga/NJJ1upjX7gdwUKSFzmN+Zr88Of3xTecB
5vYn5/XLZ50V05o8PmED6oyfbDO/xY3vCepKS8cGajKsDhM0NkjjBBCLjSO20/n/Uj20eqauG2+l
VKl9ztGaOID1Q54ZLmBk7nO0C5nZz2QfLDgYBcC6HIzzPZOXKSJ7C15llgcss0E+aTv4O/FSWzmf
tH3lcKZIcMbRPtfzWctCdUae6UGTjhp0ghWnQuJsWTTJxLJ6MfcAdVpyyDxPD8IZuU1SQM7hCtgs
QOk1DaW+21W3Pxg6FvnjG8L728xS8s3H5FGywv8Q00zcVcKambBmatbMutnRQHjSPfNgOs83Wl9s
VbJIBNGGJi3mKz/ZLs007rvA3jeLq+KcklIFZdXfkb9BfUke4CvVn5biWllfaObuVX9JmxMFlrMr
sA1aSuR9jxpMUzp/ThW+Sbi7Vx2mjd5WianI71GL06c+rUdHBMmS6CJOIjaLHBuWHks9Zbmrlxbg
edqBqqo1LwBv+dFUvZfrJHYGT2vP9Tapiny1V/NSJ1CdzPnOHsTRcei101URzXB+Sdx+UccFEK3W
5SGuj1nDc/vvOBhcJO1kcH3KPQEVRgyCabcNAA5kH42Tu4s2kt5uf/9dUjIIBs6QOVeTKlAAYUa7
zz0GvCoVBVccB2zCrTm8lMRLZJayP6cjl7npCtLQs7mo4U0RJ+zjlTADTLmo4+TiEz2tiswrJh5g
rfHf2b4BcL1fhmke9xnGPcC66jWg0fCO5o1NNnV3bQnwXNaHIFYQDfKjijUGJQirWBjRfsRAeEen
L7LyP72tmwOcpEJE5i6HkyvlsimKXMluvbYqtPtU/mf7/J8E4LLdS6AN73/q5f3ywvufajl//7Mb
usf83+nZ0evOm87RA2cAJy6LeMKh3lBAkTlaDmNYFAdP1qcLOzrNkSk/WK6vrZlkggpNUltbJ2mn
gA1Za6s1iQiYrwR4wmiwlCPMnkn4fRwE4Fi3SCYkT+T5hK8in6C1lacUbolnptOD98dqRFnh/tro
5wsG4Ku4zQaOPxnrfbFo9Rb8vpkBbV8NskM+7b8mtMMIdC2o++Lh3HbwaTuMsLwybAETUALXPBT+
CM1D1Xh1cXHW6Z6dn/7nFwUdi2vBkgaTq/BOCiA1fMy3Dn1ZlB3/3XLz36PN+/8A9i3gv3K1Xs7x
3y5oyc9AGBpQ54oOlEOZSR/Bfd+loct/ZymImiSn9F6HJtF7gybF0x0PS7eesx6ngHlc9T19Alx7
k6CDNzD34nixy7rK/nRnytOSQpqLwCB2eVyXS3APY1q03ULufhZo+/yP1tj97f8q1WDuz+z/K2H+
p9qo5PN/F3Tr/M9S+udNL/aj2NYTe5cbv9IeM+ZycI9XuYwfuO2rgj8rlU35nSaBeQEDgcq92IN4
ZszwEmpwBy76mImC71/paIRbva4g8Im4sz7Vo8cMNbXUMNlzx6QADaIUI/R2kBCAXmYTAl2dEOhC
FQturQovs+OiJLRUgfHHj5/GRnDTo87ymwEQhy1FHDpMWh6Ifi1Imu9s7VauxA5wHcHmVHchG7D3
QZMU/7f3X/kU2CbFpFyPiRTTsntLGmyfIlmxme+uItNd3FJUayS1RzLL6m4Ae1keK+F1ZmFM+9hK
IEsoHNm/lHwAiMnsjdt2LAHzDmnIZqfZQjrRApD5baaaKvGI1d+S+0TjOOjNXCtmofwzvDtcq1v4
b+HWANRrClpXK+bQ+S3mIWs2UXDNpqrZbC5JD+xzHTYu/HCfbw3fBC74VZ3wP7sgDnWGbP1qEKva
XVVL31y90GRKL0xavddXkDl9RsoS/yMIvMsh4Kznf/YbUK+hzv/UK9X8/M8uKLP+b5/+2Zj/KVfr
i/mfcqOR479d0FzIj85dL0WTk55k8l6mObmCwuT1TzO9MMjMWpwfE/16KJ3/50eHz386skbuA/Sx
Yf5XK+XK4t//qO3n+d+dUKsXEvvAaAWEegA+2gWHYcKlcAAzujWsLpZiQiJN0Zx5dNwT4qplD6vQ
gh0cGEbLZRHlnlR7WdoF/NRNyXg0ouH44EIF66KPoSbG2bJlp7ewmvAOVPjY8vhBi5JhyPrtwh7t
iTgyIU41kyNZhYNDLCIXELqe6aKWTQ9aNjw2eT6J36fNDMWN6QqTm7FkJp6TMvsinDvjJAvpU4S8
EjfEFeSY6O01EIpDbTJX+59pF9C37nZuANOePQ4ClKxwcKIvlgc7rYsAhCKLz/TFbN2WjQJq2YmU
QeB7e2RJFMYFjjYRFX5fc0A/JBLCwz0/NCIyDib7ilzA4GKM7/xQLZcrkcDbxylqvLm5WY8On4Cs
cMdCYiEWOYausAFJqDqCBlNNbWkIBO4CR3ky39U/qDviPuJHCiBdTtJ+zIVLtXdpRPHHzGjxcWDO
jR19PG26YyKIQ0D7gNwntnrlixuPuQOmzsJJMDloC8bqaCDF3tNR4KmzYACIRrilzONXzBsTn0HF
SAAQghEC/tG/+jwiYxGHs29MLcN4+hTmx3WdDIFbjunLGzw11+cOB5MZm4nUoYnLuYN1wITD3BjY
ncrZFc5mGG5e1+fM1xzEoGn7ydOnFlE2MMnaqV1gxBdRmnLRdqB6llIdfNPnBBO21V2NHdFwtP1P
W1PgVcnKowPSZzSC0ZME8au0rRKEpewz00QyyhZ5CUNwPOFrnag+oGsl5zl5+cLVWwzevXun9n+o
H38ng8nzqRShZBj3AOinu5fWyFFblQXV03aNijUByGfjaCj8anpiEox4wMCwx2CdI8uoWjBJojgg
AdjVjQhdDyXa6bzScluoj4UUDNpxROxHWs5oLjIGEUEpPGsZNYucxz55lyzOZpB4WmKCuq/B1kQ4
brd0u13d7sG3cBMEHLZbIRsJgPz444Ckj2Lo/k7rI/FBxiGwBuO90mc4g3HIB0PtEt74XOXLo7Hy
1EPu0IGAyQQPqEqSIKwHybm6xcRTGWc64+PyEF0Hii51NL/FODVB08j/u6T0X1P7hqF97pXwr0lp
/Jfuq3L6g3vvY0P8Vy5VagvxX7WS47/d0GX6x53e6tdvrzvHP54cdZ+dvn5x/LKpV5GZRQ43BHAV
winvH7Ekf5huyU5OZUNLN0NYv/VaCYuLdvscY4LnSYd4z4nDEFvVHgO8mqW3Pb8QISz3Tbia9NeG
Sy9m5AfVh3qhBK5MOJOz6UO9asvosXxiTN2kZU+uDUNlObr4zqOtLrGNwxhd8rXgrtoQPfH2LAxh
mcK0LS6NffBmkvSoc4XLgMq597hvB6pysjJAY0XtfIvp6gBLA0M25pb1yVyDZSmdf/r9mQ0hIIgN
wpIuDfCUPbhqfPMOsRDAa/jEFLuDW9jG1jAaecbsLT2WNsZKyNdzgbu+1Q4MUpRXHNpzi0S9yzeg
FVwYuklxF2UnQcTApcxh+1+JUvubTJIH6GNT/q9Ubyz6//J+fv5nJ3Q5OUTz1ihXGlYJ/pUnL/SS
MBk8bFvVy13Dn43S+T+LE+67j43zf38x/1et1+r5/N8FmSpukk1Ea7g3BKOiyWvqVVg5dwE55ZRT
TjnllFNOOeWUU0455ZRTTjnllFNOOeWUU0455fTF0v8BaSwjaAB4AAA=
EOF

RUN <<EOF
    set -e
    /usr/bin/python3 -m venv /venv
    /venv/bin/pip install --upgrade pip
    # Install wheel to avoid the warning that setup.py is being used when
    # installing Ansible
    /venv/bin/pip install wheel
    /venv/bin/pip install ansible
    cat /ansible.64 | base64 -d | (cd /; tar zxf -)
EOF

ARG GLOBUS_ANSIBLE_OPTIONS

# Modifying this arg value on the build command line will cause RUN to reinstall
# Globus instead of using the previous, cached iteration (if it exists). Useful
# for speeding up re-runs to get newer Globus versions.
ARG CACHEBUST=1

RUN <<EOF
    (cd /ansible; /venv/bin/ansible-playbook playbook.yml ${GLOBUS_ANSIBLE_OPTIONS})
EOF

######################### STAGE 3 - Prepare GCS Image ##########################
LABEL maintainer="support@globus.org"

# This is the base64 compressed tar of entrypoint.sh
COPY <<EOF /entrypoint.64
H4sIAAAAAAAAA+1ZbXPbuBHO1+Ov2MieyJ6GlOSLk45b301q63Kei1/Gdpre3HUUiIQkVBTAAqAU
Xa//vbsASZGSnJeJ005njA+WBCz2DbvPLmAurV5mSkgbmcmjrzO6OF4cHtJn78Vht/5JX593n3cf
9Z69OHzx7fPutwfPHnV7B89xGbpfSZ/GyI1lGuBRqsZCfoDuY+v/p2PncWcoZGfIzCQIdu53BDvw
9uX1xdnFqyN4zXIZT4Qcw6uTG1gIO1G5BbM0ls8SEAb4+4xrMePSsjSCN4YDs7BUuQa1kKCFmUbI
70TNMmbFMOWOh2N2GD2LDnp/uHftAzLgdsIhY5rNuOXawIKD5DwBqyB1FkFbqoSD4TbP2sA0URuD
FELCXDDgci60kmQXcpszLRgqb9AW5A+7r15f/uXNzeDk9Vn/4nZwdgrH8Oc4FUg9EMl3mxQ3/ZPr
/m2NyvBYc+soT/tXry9/Pieyn/o/Ew2XiUvtQcKzVC1JicGULx31xeVpH9ndvrkavLx+dYPkKrNC
SZaiFWMDI6Wbtu3x9xGEochCliSaG7NfU+/m9KdB/+KvZ9eXF6RAnVvC5zxVGQlveCMQI/gFwt+g
teGFFvw9sBMuA8DB44mC1rkwhqKnxqHyJrTXGbQj6L8X1uKOqOW54E/oBSNxt1zv2y+U7Zl8ovzm
iX225Ob2D8q879zYgZvb/hX0jjAj5UiMcwx81B1cwFDovErVMDcwXILOpSQb6sH0dXL1QukZS9Pl
U2iPnfgwVlLy2IaG6znXUA/nhUhTyHL8kxDAlMq3TaE68osL0xhFMjCZlDmPQhAGYswBppeQqhjD
nEQInIrgR7XAkNdPAY8u5gQZCAvIbqH0lBzBtMqRF0nMEebUaAWDEpROUFGElwmb40YJucy0mIuU
jxFUUCPLhETmxI97Ikcsk9SdADJEXpkBRE7D03kFNR52UfF4wuOpOyPSAGME6UlP1MNOEIhHInU8
Z2yKvPzB4rQgjzCcyDKlLeqSpcwil1kE50SJocZg5PYo3IHgjfrFaEChW+EfZFI4saagnkE4AleI
vCtimwaphND4Satzvr6MjK6wglCBWKEbILqhF1F75u1YTDga0MAx0klzhhoIGzSB8bjVWU2EOBH9
wyjZClwyruPrd7Db3B3Ek5lK4Hm3u7ESfCweKV3hV5e1YdjUYZ1ZQbYO4AWu7H4PoeTQ3cSSmrAR
Q98kHi/+m3BxUPYBLplmSgqLYVhmDoU/FrW8lhFfASdIm52dUg/KinMm2Zhrt+Rc1W42K8V6u2wI
XDK45Hl5dQaZVgQEPuQRGNTCUNtCGcSSmZCUXkWqFdV4E1mor8DMxE+WY2OkxW8kG8FBl3wxiFlM
cmjBdUU1brmbJRG3mkkz4pVPi9wv8YW/53Fu0dPj2Axm3qzIqHjKrTsRbCUYLXcQszvrNICaomBk
N+QTlo4iOLPkiJy6HYKTWM1muRSxN2rI7YJzNC7DVOOdibVZ4oSQnjW3Ulfn5BEvqRA2tLCuvmHt
QB0WfAjULI4nBCwYoZS/ROeVdewKE4RFQBlFvmvTHHXiTwmFZmreoNsjNTKROIjYdyeFuDaERGhM
ToWQTgRjMXeKnhPUok7lCUTEXTp08xrg5uUsFXJa2UyyVOrNlXzhKgQ5xaAGyM0fad0vZJOxhM4j
UbjI6xoFwWyKem0cCYINlS3voKPCTxtEBYauTXfccW49ZIqWIjWcEkUYwQ1HAE7FsADgpPhs7i8Q
fs+hSZxAB3vAjke+jplgDHdQyT+5VZRN4Q1hXp5xOK6+hY2dBPtjiiulZYF9HiapnlKGPIOPj1+D
b8Iw09iIMjyWTAxYln18Q8I4gtQnsC83oK7JMer6/mi7zzdVwijcIMXJYJ9O4i3DeC8rdRmwWNME
Ho8RY+yuMaJyF5WjPC0Ka4DrSPULPHZFdQtzrA2Jco40KecZdKNDnJA8qNENkO74HYbtVg7vAtdu
LbCZYHLM6YqGJzERme8iqkwrWwEf7C7MqeURlpL0k2LK8alV1g62v1t9W7TVaHFucIaixks9qJfC
HTjlQ8Fk580wlzb3zbS02IO4mHU5tVgs8OQtOyq/fEAoTw0vGF/zBE3tnGCZvrzp/MATpdlW/l6t
o8Ind/MuCvF6uXqJRcBYRsh/R8GqKKhk+YJVVimzlHHZ4a5VoRK8qE8wDtxdu2g49b1qjJxm1PCO
sT4gYhqb0AXexyKVp9zk1HvjGSNUWwLvsuoQChpqzhQ1Zr4cIUMUIZGAJU+poLWdqLKFxeWVNHfR
bycUCZpWTBs7xs/Ej63tFyv9BE8aoV/NuyTYfRxsnMNLf3YOvLceQ52gHXxhbBaF1rCRa8wpg/x2
6oNp5zpbnAd61rJuFY0g3DiuIq2QXX5GhDefGsiOxpnj4YXbuJNNRcemphNzbU3HXYcmytgo1hbt
ow2VjV6CZw1/xCtRjmXS3WJwU0oPKxPXW2lf8Ktuv9zrLEXMoE7G187QmDQc0w1GF9ph3ngxK2eg
y8wat5XP/Clu9ZRb8n+dlyglG/C6W2y5E1Ld3hWYlvTvNlNbi+SH26vtSe3XEDEpbtsfi36rcmTo
jCB43Rr8BDdhCTdj5D+yGd02gpVfin3lYpE0xSXlpvwS+xgoqCLClHLppLmUlPOlzzzsbZPinL2t
kN1FfHdJ86Tr5ewuPu+Cr3H5ce0opXCca42xjzApVXmVdgX+8uz0ZP1VNLr/288II8qBvTCDoiQM
WIqN7t5+8C/nvilhfog32B5ecPE2PO9IeiM5+O5JL/h3jYF7RSh5VLt3aF8IF2xWgsnuAf6+OjsN
PHCsicXlFaDUrq4bmOGvsMicLqn0+pBLejCO8Wu6bFVkGq+32CX26jhQzHVJfTPJ3QPZgN58jrs1
c1LOZJ5Vhnh5NwW5eyKKouKe3GTiZVnNMjT0tn99Xv/d/9vZbVBtIvpBrdCgAtudstaHwZMn2/f3
as7bRgAh/yf07vbnLdd4Q2V27aYLeyR0XYv9lZt9kJCxG1RBRTQS2mAFxWJa6EnDp/RR9btI2nJ8
kiuGeO2aBt8Q/d7e7krM/j6tesuocyar8GjrhmH1pABq+d01Dbs1jSRfc1Odw4SZMgZbZZT5UL/H
PPWp85ajMv5KXN4DykJgi3u+a8Xw3p2l3PLo3vWopcJ18YrrXpGKbIEqJT7wvFXQUva5pCj3ulRp
zLhkcTPtNvz45qr6fnaBSbQ6iuoRtHb3QUT1r2R0LGXd2G1kqkuG7qpQNBAMWvWOrQW7Vd2G33/f
mvFr22sx0tqM2s/mserh17g1etNtfNcgoWn+ViwoT8gddtkGOsxypbQCU5cZ/+v/Vz6Mh/EwHsbD
eBgP42E8jC8b/wGXDHEMACgAAA==
EOF

RUN <<EOF
    cat /entrypoint.64 | base64 -d | tar zxf - > /entrypoint.sh
EOF

# These are the default ports in use by GCSv5.4. Currently, they can not be changed.
#   443 : HTTPD service for GCS Manager API and HTTPS access to collections
#  50000-51000 : Default port range for incoming data transfer tasks
EXPOSE 443/tcp 50000-51000/tcp

# Default command unless overriden with 'docker run --entrypoint'
ENTRYPOINT ["/entrypoint.sh"]
# Default options to ENTRYPOINT unless overriden with 'docker run arg1...'
CMD []
