# syntax=docker/dockerfile:1.3-labs

############## STAGE 1 - Prepare the image for GCS installation ################
FROM ubuntu:24.04

# Prereqs
RUN <<EOF
    set -e
    apt update
    # Resolves: "debconf: (Can't locate Term/ReadLine.pm in @INC" from python install
    apt install -y libterm-readline-gnu-perl
    apt install -y coreutils gzip python3 python3-venv sudo tar
EOF

##################### STAGE 2 - Install GCS using Ansible ######################
# This is the base64 compressed tar of the ansible repo directory
COPY <<EOF /ansible.64
H4sIAAAAAAAAA+1ce3PbNhLP3/wUOPk6SnIlqafVqpLv3MRJPOfGHsvpXMeXUyASklBTBEuQdtQm
3/12AVJvRZQfStJyM5EoEASwDyz2twRMfcl7HrMfPSCVgBr1uvoGWvxW1+Vao96o7peqldqjUrlc
KdUekfpDDiqlWEY0JORRKET0qXqb7n+lRBP9h8Jj8oGsYHv9V6rVUq7/XdC8/gee6MXSdITvMycy
JQuvWXhnq9he//v1+n6u/11QFv27rE9jL7q1e8ik/3qptN8olUul6qNSpVStVXL974K20v+Ict8a
j7wt+0AF79dq6/W/vz8//ytgADD/Sw/C8QL9xfW/R4B/MIAPsZ9cRExG3B98CEJm6iJj4MhuyALR
TCobn3vUOd0XZZn/EZVXd4kNs/r/RrlWr+6D/y839ht5/L8Tyq5/jg7C88ARuEMabbMMfNr/l0sN
uJf4/1q5VAb/D8t/7v93Qntbk7FHFB2/7lwcnpwcXhyfviYvTs/JOXNf0Yg8Pzo//hlKfz7qWMYt
mjewh0NtlqRPnUgS0Sfcj1gIK1NT3SaJ2XaF7PbpiHvjZtr9B9IJQli/XArr1ExNl8so5L044sLv
juivIuyCbUv41STfwVPfw/9aCT/K6x5rkkNvRE+4H7+Hes+YH5124OIFc0VI4eI0pI7H0vuT8ZwL
52q8MC7gkhyPAhFGJBoycnR2dEKu2Jiw94HHHR55Y9JjDo0lU/dTcYzjERkJN4ZLVzDpFyNC40iY
XDUFbUIbEp8Ykxs6xuq26/fJDfc8wyQ+HbEmOdbzeNrv+dlPBFd3ySMRjrEJg2DvAmuPmYRfYTDq
QnnTQMXjBRlGUSCbtu16Vl/xH4TiV/AZlggHdhD3bBYwz4amzZdnL81/H/1iYl/mH39kUAj5+BE6
uhkyX3dornyG/K1NClr2BWM9d1POlrgC8egO9KPZWMIPM2Qeo5KZHsVoKTNXli9o6AwtEKfqF4Ya
QccQaUkwpq153iNHylw8Ho0JnzDOJWHXzIcrEQ+GhEcESiiRoh8RF4bvu8x3xkT480JCJadGB01r
u9KNUtU3zML5NjiT2DSsFn0+iEOMDGHULtQagX3isIUkQ3rNcAzwGyu41pKq0EJ1G+aI+nTAwk2a
gidgjRpBbffx/JNPNsl1L52utfI/CHYhYXZEQ2yyrga/NJJ1upjX7gdwUKSFzmN+Zr88Of3xTecB
5vYn5/XLZ50V05o8PmED6oyfbDO/xY3vCepKS8cGajKsDhM0NkjjBBCLjSO20/n/Uj20eqauG2+l
VKl9ztGaOID1Q54ZLmBk7nO0C5nZz2QfLDgYBcC6HIzzPZOXKSJ7C15llgcss0E+aTv4O/FSWzmf
tH3lcKZIcMbRPtfzWctCdUae6UGTjhp0ghWnQuJsWTTJxLJ6MfcAdVpyyDxPD8IZuU1SQM7hCtgs
QOk1DaW+21W3Pxg6FvnjG8L728xS8s3H5FGywv8Q00zcVcKambBmatbMutnRQHjSPfNgOs83Wl9s
VbJIBNGGJi3mKz/ZLs007rvA3jeLq+KcklIFZdXfkb9BfUke4CvVn5biWllfaObuVX9JmxMFlrMr
sA1aSuR9jxpMUzp/ThW+Sbi7Vx2mjd5WianI71GL06c+rUdHBMmS6CJOIjaLHBuWHks9Zbmrlxbg
edqBqqo1LwBv+dFUvZfrJHYGT2vP9Tapiny1V/NSJ1CdzPnOHsTRcei101URzXB+Sdx+UccFEK3W
5SGuj1nDc/vvOBhcJO1kcH3KPQEVRgyCabcNAA5kH42Tu4s2kt5uf/9dUjIIBs6QOVeTKlAAYUa7
zz0GvCoVBVccB2zCrTm8lMRLZJayP6cjl7npCtLQs7mo4U0RJ+zjlTADTLmo4+TiEz2tiswrJh5g
rfHf2b4BcL1fhmke9xnGPcC66jWg0fCO5o1NNnV3bQnwXNaHIFYQDfKjijUGJQirWBjRfsRAeEen
L7LyP72tmwOcpEJE5i6HkyvlsimKXMluvbYqtPtU/mf7/J8E4LLdS6AN73/q5f3ywvufajl//7Mb
usf83+nZ0evOm87RA2cAJy6LeMKh3lBAkTlaDmNYFAdP1qcLOzrNkSk/WK6vrZlkggpNUltbJ2mn
gA1Za6s1iQiYrwR4wmiwlCPMnkn4fRwE4Fi3SCYkT+T5hK8in6C1lacUbolnptOD98dqRFnh/tro
5wsG4Ku4zQaOPxnrfbFo9Rb8vpkBbV8NskM+7b8mtMMIdC2o++Lh3HbwaTuMsLwybAETUALXPBT+
CM1D1Xh1cXHW6Z6dn/7nFwUdi2vBkgaTq/BOCiA1fMy3Dn1ZlB3/3XLz36PN+/8A9i3gv3K1Xs7x
3y5oyc9AGBpQ54oOlEOZSR/Bfd+loct/ZymImiSn9F6HJtF7gybF0x0PS7eesx6ngHlc9T19Alx7
k6CDNzD34nixy7rK/nRnytOSQpqLwCB2eVyXS3APY1q03ULufhZo+/yP1tj97f8q1WDuz+z/K2H+
p9qo5PN/F3Tr/M9S+udNL/aj2NYTe5cbv9IeM+ZycI9XuYwfuO2rgj8rlU35nSaBeQEDgcq92IN4
ZszwEmpwBy76mImC71/paIRbva4g8Im4sz7Vo8cMNbXUMNlzx6QADaIUI/R2kBCAXmYTAl2dEOhC
FQturQovs+OiJLRUgfHHj5/GRnDTo87ymwEQhy1FHDpMWh6Ifi1Imu9s7VauxA5wHcHmVHchG7D3
QZMU/7f3X/kU2CbFpFyPiRTTsntLGmyfIlmxme+uItNd3FJUayS1RzLL6m4Ae1keK+F1ZmFM+9hK
IEsoHNm/lHwAiMnsjdt2LAHzDmnIZqfZQjrRApD5baaaKvGI1d+S+0TjOOjNXCtmofwzvDtcq1v4
b+HWANRrClpXK+bQ+S3mIWs2UXDNpqrZbC5JD+xzHTYu/HCfbw3fBC74VZ3wP7sgDnWGbP1qEKva
XVVL31y90GRKL0xavddXkDl9RsoS/yMIvMsh4Kznf/YbUK+hzv/UK9X8/M8uKLP+b5/+2Zj/KVfr
i/mfcqOR479d0FzIj85dL0WTk55k8l6mObmCwuT1TzO9MMjMWpwfE/16KJ3/50eHz386skbuA/Sx
Yf5XK+XK4t//qO3n+d+dUKsXEvvAaAWEegA+2gWHYcKlcAAzujWsLpZiQiJN0Zx5dNwT4qplD6vQ
gh0cGEbLZRHlnlR7WdoF/NRNyXg0ouH44EIF66KPoSbG2bJlp7ewmvAOVPjY8vhBi5JhyPrtwh7t
iTgyIU41kyNZhYNDLCIXELqe6aKWTQ9aNjw2eT6J36fNDMWN6QqTm7FkJp6TMvsinDvjJAvpU4S8
EjfEFeSY6O01EIpDbTJX+59pF9C37nZuANOePQ4ClKxwcKIvlgc7rYsAhCKLz/TFbN2WjQJq2YmU
QeB7e2RJFMYFjjYRFX5fc0A/JBLCwz0/NCIyDib7ilzA4GKM7/xQLZcrkcDbxylqvLm5WY8On4Cs
cMdCYiEWOYausAFJqDqCBlNNbWkIBO4CR3ky39U/qDviPuJHCiBdTtJ+zIVLtXdpRPHHzGjxcWDO
jR19PG26YyKIQ0D7gNwntnrlixuPuQOmzsJJMDloC8bqaCDF3tNR4KmzYACIRrilzONXzBsTn0HF
SAAQghEC/tG/+jwiYxGHs29MLcN4+hTmx3WdDIFbjunLGzw11+cOB5MZm4nUoYnLuYN1wITD3BjY
ncrZFc5mGG5e1+fM1xzEoGn7ydOnFlE2MMnaqV1gxBdRmnLRdqB6llIdfNPnBBO21V2NHdFwtP1P
W1PgVcnKowPSZzSC0ZME8au0rRKEpewz00QyyhZ5CUNwPOFrnag+oGsl5zl5+cLVWwzevXun9n+o
H38ng8nzqRShZBj3AOinu5fWyFFblQXV03aNijUByGfjaCj8anpiEox4wMCwx2CdI8uoWjBJojgg
AdjVjQhdDyXa6bzScluoj4UUDNpxROxHWs5oLjIGEUEpPGsZNYucxz55lyzOZpB4WmKCuq/B1kQ4
brd0u13d7sG3cBMEHLZbIRsJgPz444Ckj2Lo/k7rI/FBxiGwBuO90mc4g3HIB0PtEt74XOXLo7Hy
1EPu0IGAyQQPqEqSIKwHybm6xcRTGWc64+PyEF0Hii51NL/FODVB08j/u6T0X1P7hqF97pXwr0lp
/Jfuq3L6g3vvY0P8Vy5VagvxX7WS47/d0GX6x53e6tdvrzvHP54cdZ+dvn5x/LKpV5GZRQ43BHAV
winvH7Ekf5huyU5OZUNLN0NYv/VaCYuLdvscY4LnSYd4z4nDEFvVHgO8mqW3Pb8QISz3Tbia9NeG
Sy9m5AfVh3qhBK5MOJOz6UO9asvosXxiTN2kZU+uDUNlObr4zqOtLrGNwxhd8rXgrtoQPfH2LAxh
mcK0LS6NffBmkvSoc4XLgMq597hvB6pysjJAY0XtfIvp6gBLA0M25pb1yVyDZSmdf/r9mQ0hIIgN
wpIuDfCUPbhqfPMOsRDAa/jEFLuDW9jG1jAaecbsLT2WNsZKyNdzgbu+1Q4MUpRXHNpzi0S9yzeg
FVwYuklxF2UnQcTApcxh+1+JUvubTJIH6GNT/q9Ubyz6//J+fv5nJ3Q5OUTz1ihXGlYJ/pUnL/SS
MBk8bFvVy13Dn43S+T+LE+67j43zf38x/1et1+r5/N8FmSpukk1Ea7g3BKOiyWvqVVg5dwE55ZRT
TjnllFNOOeWUU0455ZRTTjnllFNOOeWUU0455fTF0v8BaSwjaAB4AAA=
EOF

RUN <<EOF
    set -e
    /usr/bin/python3 -m venv /venv
    /venv/bin/pip install --upgrade pip
    # Install wheel to avoid the warning that setup.py is being used when
    # installing Ansible
    /venv/bin/pip install wheel
    /venv/bin/pip install ansible
    cat /ansible.64 | base64 -d | (cd /; tar zxf -)
EOF

ARG GLOBUS_ANSIBLE_OPTIONS

# Modifying this arg value on the build command line will cause RUN to reinstall
# Globus instead of using the previous, cached iteration (if it exists). Useful
# for speeding up re-runs to get newer Globus versions.
ARG CACHEBUST=1

RUN <<EOF
    (cd /ansible; /venv/bin/ansible-playbook playbook.yml ${GLOBUS_ANSIBLE_OPTIONS})
EOF

######################### STAGE 3 - Prepare GCS Image ##########################
LABEL maintainer="support@globus.org"

# This is the base64 compressed tar of entrypoint.sh
COPY <<EOF /entrypoint.64
H4sIAAAAAAAAA+1ZbXPbuBHO1+Ov2MieyJ6GlOSLk45b301q63Kei1/Gdpre3HUUiIQkVBTAAqAU
Xa//vbsASZGSnJeJ005njA+WBCz2DbvPLmAurV5mSkgbmcmjrzO6OF4cHtJn78Vht/5JX593n3cf
9Z69OHzx7fPutwfPHnV7B89xGbpfSZ/GyI1lGuBRqsZCfoDuY+v/p2PncWcoZGfIzCQIdu53BDvw
9uX1xdnFqyN4zXIZT4Qcw6uTG1gIO1G5BbM0ls8SEAb4+4xrMePSsjSCN4YDs7BUuQa1kKCFmUbI
70TNMmbFMOWOh2N2GD2LDnp/uHftAzLgdsIhY5rNuOXawIKD5DwBqyB1FkFbqoSD4TbP2sA0URuD
FELCXDDgci60kmQXcpszLRgqb9AW5A+7r15f/uXNzeDk9Vn/4nZwdgrH8Oc4FUg9EMl3mxQ3/ZPr
/m2NyvBYc+soT/tXry9/Pieyn/o/Ew2XiUvtQcKzVC1JicGULx31xeVpH9ndvrkavLx+dYPkKrNC
SZaiFWMDI6Wbtu3x9xGEochCliSaG7NfU+/m9KdB/+KvZ9eXF6RAnVvC5zxVGQlveCMQI/gFwt+g
teGFFvw9sBMuA8DB44mC1rkwhqKnxqHyJrTXGbQj6L8X1uKOqOW54E/oBSNxt1zv2y+U7Zl8ovzm
iX225Ob2D8q879zYgZvb/hX0jjAj5UiMcwx81B1cwFDovErVMDcwXILOpSQb6sH0dXL1QukZS9Pl
U2iPnfgwVlLy2IaG6znXUA/nhUhTyHL8kxDAlMq3TaE68osL0xhFMjCZlDmPQhAGYswBppeQqhjD
nEQInIrgR7XAkNdPAY8u5gQZCAvIbqH0lBzBtMqRF0nMEebUaAWDEpROUFGElwmb40YJucy0mIuU
jxFUUCPLhETmxI97Ikcsk9SdADJEXpkBRE7D03kFNR52UfF4wuOpOyPSAGME6UlP1MNOEIhHInU8
Z2yKvPzB4rQgjzCcyDKlLeqSpcwil1kE50SJocZg5PYo3IHgjfrFaEChW+EfZFI4saagnkE4AleI
vCtimwaphND4Satzvr6MjK6wglCBWKEbILqhF1F75u1YTDga0MAx0klzhhoIGzSB8bjVWU2EOBH9
wyjZClwyruPrd7Db3B3Ek5lK4Hm3u7ESfCweKV3hV5e1YdjUYZ1ZQbYO4AWu7H4PoeTQ3cSSmrAR
Q98kHi/+m3BxUPYBLplmSgqLYVhmDoU/FrW8lhFfASdIm52dUg/KinMm2Zhrt+Rc1W42K8V6u2wI
XDK45Hl5dQaZVgQEPuQRGNTCUNtCGcSSmZCUXkWqFdV4E1mor8DMxE+WY2OkxW8kG8FBl3wxiFlM
cmjBdUU1brmbJRG3mkkz4pVPi9wv8YW/53Fu0dPj2Axm3qzIqHjKrTsRbCUYLXcQszvrNICaomBk
N+QTlo4iOLPkiJy6HYKTWM1muRSxN2rI7YJzNC7DVOOdibVZ4oSQnjW3Ulfn5BEvqRA2tLCuvmHt
QB0WfAjULI4nBCwYoZS/ROeVdewKE4RFQBlFvmvTHHXiTwmFZmreoNsjNTKROIjYdyeFuDaERGhM
ToWQTgRjMXeKnhPUok7lCUTEXTp08xrg5uUsFXJa2UyyVOrNlXzhKgQ5xaAGyM0fad0vZJOxhM4j
UbjI6xoFwWyKem0cCYINlS3voKPCTxtEBYauTXfccW49ZIqWIjWcEkUYwQ1HAE7FsADgpPhs7i8Q
fs+hSZxAB3vAjke+jplgDHdQyT+5VZRN4Q1hXp5xOK6+hY2dBPtjiiulZYF9HiapnlKGPIOPj1+D
b8Iw09iIMjyWTAxYln18Q8I4gtQnsC83oK7JMer6/mi7zzdVwijcIMXJYJ9O4i3DeC8rdRmwWNME
Ho8RY+yuMaJyF5WjPC0Ka4DrSPULPHZFdQtzrA2Jco40KecZdKNDnJA8qNENkO74HYbtVg7vAtdu
LbCZYHLM6YqGJzERme8iqkwrWwEf7C7MqeURlpL0k2LK8alV1g62v1t9W7TVaHFucIaixks9qJfC
HTjlQ8Fk580wlzb3zbS02IO4mHU5tVgs8OQtOyq/fEAoTw0vGF/zBE3tnGCZvrzp/MATpdlW/l6t
o8Ind/MuCvF6uXqJRcBYRsh/R8GqKKhk+YJVVimzlHHZ4a5VoRK8qE8wDtxdu2g49b1qjJxm1PCO
sT4gYhqb0AXexyKVp9zk1HvjGSNUWwLvsuoQChpqzhQ1Zr4cIUMUIZGAJU+poLWdqLKFxeWVNHfR
bycUCZpWTBs7xs/Ej63tFyv9BE8aoV/NuyTYfRxsnMNLf3YOvLceQ52gHXxhbBaF1rCRa8wpg/x2
6oNp5zpbnAd61rJuFY0g3DiuIq2QXX5GhDefGsiOxpnj4YXbuJNNRcemphNzbU3HXYcmytgo1hbt
ow2VjV6CZw1/xCtRjmXS3WJwU0oPKxPXW2lf8Ktuv9zrLEXMoE7G187QmDQc0w1GF9ph3ngxK2eg
y8wat5XP/Clu9ZRb8n+dlyglG/C6W2y5E1Ld3hWYlvTvNlNbi+SH26vtSe3XEDEpbtsfi36rcmTo
jCB43Rr8BDdhCTdj5D+yGd02gpVfin3lYpE0xSXlpvwS+xgoqCLClHLppLmUlPOlzzzsbZPinL2t
kN1FfHdJ86Tr5ewuPu+Cr3H5ce0opXCca42xjzApVXmVdgX+8uz0ZP1VNLr/288II8qBvTCDoiQM
WIqN7t5+8C/nvilhfog32B5ecPE2PO9IeiM5+O5JL/h3jYF7RSh5VLt3aF8IF2xWgsnuAf6+OjsN
PHCsicXlFaDUrq4bmOGvsMicLqn0+pBLejCO8Wu6bFVkGq+32CX26jhQzHVJfTPJ3QPZgN58jrs1
c1LOZJ5Vhnh5NwW5eyKKouKe3GTiZVnNMjT0tn99Xv/d/9vZbVBtIvpBrdCgAtudstaHwZMn2/f3
as7bRgAh/yf07vbnLdd4Q2V27aYLeyR0XYv9lZt9kJCxG1RBRTQS2mAFxWJa6EnDp/RR9btI2nJ8
kiuGeO2aBt8Q/d7e7krM/j6tesuocyar8GjrhmH1pABq+d01Dbs1jSRfc1Odw4SZMgZbZZT5UL/H
PPWp85ajMv5KXN4DykJgi3u+a8Xw3p2l3PLo3vWopcJ18YrrXpGKbIEqJT7wvFXQUva5pCj3ulRp
zLhkcTPtNvz45qr6fnaBSbQ6iuoRtHb3QUT1r2R0LGXd2G1kqkuG7qpQNBAMWvWOrQW7Vd2G33/f
mvFr22sx0tqM2s/mserh17g1etNtfNcgoWn+ViwoT8gddtkGOsxypbQCU5cZ/+v/Vz6Mh/EwHsbD
eBgP42E8jC8b/wGXDHEMACgAAA==
EOF

RUN <<EOF
    cat /entrypoint.64 | base64 -d | tar zxf - > /entrypoint.sh
EOF

# These are the default ports in use by GCSv5.4. Currently, they can not be changed.
#   443 : HTTPD service for GCS Manager API and HTTPS access to collections
#  50000-51000 : Default port range for incoming data transfer tasks
EXPOSE 443/tcp 50000-51000/tcp

# Default command unless overriden with 'docker run --entrypoint'
ENTRYPOINT ["/entrypoint.sh"]
# Default options to ENTRYPOINT unless overriden with 'docker run arg1...'
CMD []
