# syntax=docker/dockerfile:1.3-labs

############### STAGE 1 - Prepare the image for GCS installation ###############
FROM opensuse/leap:15.5

# Prereqs
RUN <<EOF
    # Ansible 2.12 will require python38 or newer
    zypper install -y coreutils gzip python311 sudo tar util-linux
    # This helps stage 2 (ansible install) find python
    ln -s /usr/bin/python3.11 /usr/bin/python3
EOF

##################### STAGE 2 - Install GCS using Ansible ######################
# This is the base64 compressed tar of the ansible repo directory
COPY <<EOF /ansible.64
H4sIAAAAAAAAA+0ca3PbNjKf9Stw8nUU50rqLbWq5Ds3cRLPubHHsjvX8eUUiIRE1BTBEqQdtul/
v12A1FuW5NhK0nAzkSgQWGCf2F2Cpp7kfZcVnzwilACa9br6Bpj/Vtfleqlcb1RLtSr0K5fLzeoT
Un/MRaUQyZAGhDwJhAjv6rfu/hcKNJF/IFwmH0kLNpJ/rVlvVhulaqUG8q9Uq6VM/ruAWfkPXdGP
pGEJz2NWaEgW3LDgo7Vie/k36vVGJv9dwCbyt9mARm54b/ewjf9vNkH+lVK1UcnkvwvYSv4jyj0z
HrlbzoECbtRqq+XfaMzafwUV4AkpPQrFc/CVy3+PAP2gAB8iL7kImQy5N/zgB8zQTbmhJXsB80Ur
6Zz71KvO4KFgE/sPqbz+mNhwC/9fLlcasP83G80s/tsJbC5/jg7CdXs263O61Tawxv/XwPej/EvN
cq0OWwD4/2q1Wcn8/y5gb2vI7RGE4zfdi8OTk8OL49M35OXpObnsR14YFV8o9cjdA28OUR9qfSQD
aoWSiAHhXsgC2JJa6jZJ9LUnZG9AR9yNWySdcXLT5jIMeD8KufB6I/qrCHqgxxJ+tUi5RD6Qchk/
voOPCv6sVFaODpjLqGQtAnYBC4HO/ch1JYsZXkIPbsHFQFjUhe9f6WgUw/c191jIrVVY0zVDT801
oC1nEI+OYKJjbWckdBh59bxLcOOVPBRBTCAQ4x5HDDJHSJ9ZAgfEDH9RH1iEggH7bBEnDH3ZKhZt
ceu5gtrS1KZtimC4wsr/+IOoTb7HvQF/z+RVuuu/JX/+mVo/cLGIbRAT9lM8apBLMW7oQRcTbqmF
wIAQlgdxhGReOCHwyMMYQtOnMJDneiWkq1ZCYCXp3DD1hAGcLZINN11qMU26T0OnRYostIrAjqIU
UWAxabrAetNeTrYxOxn+vEsPoItCp6YL2JC991uk8L+9/8pnQDYpJO16TaSQtt06zNNLNCaz/a1D
8jqeyi+7NYm/8hPeveByDfP0kCmteXiW6SnuyaoVnNojG/Nqc0WasPAufljCj1PTAT+zJTMmc2zF
EMASglW0yAf1U5ktuZJ86DHb6MedYiSDonRowKbNrPjq7JXx76NfDE2vOfSH327U06iUKjXs/nbs
GvoRd2f9whbOQlOMXoCsp1oRC+2rhNtZpe3bCNgPxPstZAv/TVjWAOUK60hHLxHMofVbxAPWaiHj
Wi3Vs9Va4B7op7CuZd0B1iY+RXUF+vM/bEr55LYey6X2+cyeMOXSt8GvKqYcnl0Qi1oOW70bRKp3
T/XSN5dvNMvYuxqrRrBUNeq1Zc7/U4c5GayA7eP/gNkODR8u/i+XseYzyf+w/lOtlZpZ/L8LuHf8
v5gAnDP7NQ3Ji6Pz45+h9eejrrnLNCCZ/gPp+gH3hjZ12aY5ASYC38P/GiYDtfLqsP3QHdET7kXv
od9z8GunXbh4yWwRULg4DajlsvT+eD3nsC/Ec+sCKsnxyBdBqNzv0dnRCblmMYEgyeUWD90YXS+N
ZOLoE3bE0YiMhB3BpS2Y9AohoVEoDK5QAU7AIXFETG5pjN2Ltjcgt9x1l7p9Ne/52U/TSQagWAwZ
/VEP2rXzx4tJguGaA0U/bFi/gs9QMYMf9YvMZ24RUBtpIIJzrQyRZgQCW+bchrlsjIoJNe/zyzc1
Rd0dgR+wZ3o724wk/DCS2MbQWc/GVJmeoIHlmMDOZZvktjTvkSOlLi4PIVQYEw5BA7thHlyJaOgQ
HmIYQYkUgxCiCZ95NvOsmAhvlkko5FTpALXWK42UqrnBCmdxQD6GqDGM4sMoUGEY9WzoNQL9xGUL
SRx6w3ANts5cbHNBVKihGocxoh4dLgk85iQFI2CPGkFv++nsyP11fN1LzbVW/gfBKSRYR+ggyrpa
/MJKVsliVrofwEGRNjqPWct+dXL642X3EWz7TrvGusGiWZOnJ2xIrXh/G/veOieYqhTgiucSkdV1
jmXrxazlU65WpU0fXZpZ5WceqzYD/JlOBRMvtZXzeYxKxLLyTWJYJqZTIfdM6TDX1YuwRnaL5JFy
uMIsClpvaCD13Z66neZof3xD+GAbKyXf/JkMJUv8DzGMxF0lpBkJaYYmzagbXf0gbDw9c8GcZ5HW
57FKFgo/XIPSZCrptTulKeSeDeR9M78rflQlaW1unTwH/ELlp7m4ktcXmrgHlV+CcyzA8uYCxDpA
wu8HlGD6SPevKcLLhLoHlWGK9L5CTFn+gFJcVsRcJselpS7Yekw1amX9sj5VwVRdl1fBrlZx7AxG
a8/1NumKdHWW01In0J3M+M4+xNFR4HYesiyJGyBqrc0D3B83Dc+Lf8fF4CZZTBY3oNwV0GHEIJi2
O5DAAe/DOLk7ryPp7c733yUtQ39oOcy6HneBBggzOgPuMqBVici/5rhgA27N5EtJvESmYfNxOnKZ
MVfghrbmgk5vCmiwT5emGaDKBR0nF/a1WRWYW0g8wK5ruC73GMY97uIji/uqN6Js6ek6K8u2qifE
ViwI6SBkwLyj05cPWclNw8nlfHmqw7bF8HcunNyiCru49lT5YXmeCLdeYsKxiQndd7WkQxZwbU1B
uvpPXVP7kmD7+q+ExHW7Q4Brzn/Uy43y3Pm/ajk7/7cbeMD67+nZ0ZvuZffokSvA4y2LuHjqwhHQ
ZIwWw1gWRv7+6nJxV5e5NjszUl93PiTfIrWVfRI8eURkruzWIsJnnmLgCaP+Qo1480rS77Hvg3fe
opiUjMjqSV9EPUlLKysp3TOfnZgHH8RqRZuWe1ZGv59xAWYZtZsVR+6M9T/basU96L2cStq/mMwe
6Sx+nak9RqArk/rPPp3fLn2+MwHbYGfYKjtk3g0PhDdC9VA9Xl9cnHV7Z+en//lFlQ4KK5NlXUxY
lu+mBQRdPsiSs88LNs//7vny15P173/hmf/Z/K9crZez/G8XsOBnIAz1qXVNh8qhTJUP4b5n08Dm
v7M0iRoXJ/VZlxbRZ8PGzZMTLwu39AH4FtFvk0xGRHjWHh18DmtvlhvZrKf0T0+mPC3Jp7UIDGIX
13W1kO5hTIu6m8/czxxsYv+oBB/zEvgW73+Vag18/7tZr2Tv/+4ENpb//d3/Wv8P3n7e/5eb2fnP
ncBMDQB9rI5Ax2/6knFe1hpfQWOS/rXSixyZymay14S/HEjt//zo8MVPR+bIfoQ51th/tVKuzP/9
l1oji/92Au1+QIoHubZPqMuHXidvMayz5w/AottOdb4Vw8O0zHzm0rgvxHW76FQBQ9E/yOXaNgsh
yZaqlt3J46dGJaPRiAbxwYUqd4gBZrJYhpDtYnoLuwn3QMV5bZcftClxAjbo5PdoX0ShETrMSI7k
5g8OsYlcOLAM3dQu0oN2EYaNxydB5QSNI24NWxjcgPDSwHOyxkAEM2dcZf5gHIq+FrfEFuSY6PI6
JLTQm8z0/mc6Bcytp51ZwGRmlwMDJcsfnOiLxcVO+mJ9hiKJz/XFdN92ERnULiZcBobv7ZEFVuQu
cLUJq/D7httMklAIF2v+NIQA2x8/V7CZ74oYc34Uy9XSQsPbp2kN5/b2dnWtZh94hRXLRENMcgxT
IQJJqDqCDKamSpq+wFNAyE/m2foHtUfcw0IODUUgx097mA2X6tnFiOKPqdXicCDOjix9PHlSMfWj
wBeSSXOsq9eeuHWZPWTqLLQElQNcsFZL1+fYezryXXUWGHKgET5Scvk1c2PiMegYCtJnsELqh/rX
gIckFlEwXTExc7lnz8A+burEAWo5PrW6xVPTA25xUJnYSLgOKK5mDlYDERazIyB3wmdbWOuLYsZN
fUZ9jWEEki7uP3tmEqUD4zK+egqkHvEnr1xqPVAzS6kOPutz4gnZ6q5+dwwVR+v/BJuqWSleuXRI
BoyGsHqSPAtTT+sUI0ylnxsZUq5sklewBMsVnpaJmgOmVnye4ZcnbF1ifPfunar/qh9/J8Px+JSL
0OJEfdMS6dOLFXzUWmVC9xRvrmKOc+KzOHSEV01PzIMSDxkodgzaOTJzVROMJIx8SJulvBWB7SJH
u93Xmm9z/bGRgkJbloi8UPMZ1UVGwCJohbFmrmaS88gj75LN2fATT0sMEPcN6JoI4k5b4+1pvAff
wk1gcNBpB2wkQtbDHwckHYqh+zstj8QH5Q6BNFjvtT7D78cBHzraJVx6XJVRw1h5aodbdCjAmGCA
6iQJlgyBc7bGmHiq3Jl+49PmAboOZF3qaH6L0DRB0kj/u6T1XxP9hqV96p3w64Q0/kufq1iD4YPP
sSb+K5fw/b+Z+K9ayfK/3cBV+se93upTF2+6xz+eHPWen755efyqpXeRqU0OC4JchXDK+4cseXqd
HslI3soBTLcO7N96r4TNRbt9jjHBi2RCvGdFQYBYtccAr2bqYw8vRQDbfQuuxvN14NKNGPlBzaH+
oAS4MmGN301y9K4tw6dyPzdxk2ZxfJ3LqSpHDw8QdtQl4jiM0CXfCG6rAxFjb8+CALYpfFqDW+MA
vJkkfWpd4zag3rnvc6/oq87JzgDICtr5FtLdAbYGhmTMbOtjW4NtKbU//UC9CCEgsA3Ckh718S0r
cNV48gpiIUiv4ROfdVn4CCs2nXDk5qZv6bV0MFZCul4IPPWhKrCkIK854LMLRNVSc4AFN4Ze0txD
3klgMVAps7T9a4JU/8ZG8ghzrKv/lerNef9fbmTn/3YCV+NDdG9z5UrTLMG/8vjJehImg4ftqH6Z
a/irQWr/03nCQ8+x1v4b8/W/ar1Wz+x/F2CouEm2MFvDo5AYFY1PpyzLlTMXkEEGGWSQQQYZZJBB
BhlkkEEGGWSQQQYZZJBBBhlk8FnD/wFov+lFAHgAAA==
EOF

RUN <<EOF
    set -e
    /usr/bin/python3 -m venv /venv
    /venv/bin/pip install --upgrade pip
    # Install wheel to avoid the warning that setup.py is being used when
    # installing Ansible
    /venv/bin/pip install wheel
    /venv/bin/pip install ansible
    cat /ansible.64 | base64 -d | (cd /; tar zxf -)
EOF

ARG GLOBUS_ANSIBLE_OPTIONS

# Modifying this arg value on the build command line will cause RUN to reinstall
# Globus instead of using the previous, cached iteration (if it exists). Useful
# for speeding up re-runs to get newer Globus versions.
ARG CACHEBUST=1

RUN <<EOF
    (cd /ansible; /venv/bin/ansible-playbook playbook.yml ${GLOBUS_ANSIBLE_OPTIONS})
EOF

######################### STAGE 3 - Prepare GCS Image ##########################
LABEL maintainer="support@globus.org"

# This is the base64 compressed tar of entrypoint.sh
COPY <<EOF /entrypoint.64
H4sIAAAAAAAAA+1ZbXPbuBHO1+Ov2MieyJ6GlOSLk45bXye1dTnPxS9jO01v7joKREISThTIAqAU
Xa//vbsASJGSnJeJ005njA+WBCz2DbvPLmAujVrmmZAm0pNHX2d0cbw4PKTP3ovDbv2Tvj7vPu8+
6j17cfji2+fdbw+ePer2nnUPnz+C7lfSpzEKbZgCePQr05lkqbmL7mPr/6dj53FnKGRnyPQkCHbu
dwQ78Pbl9cXZxasjeM0KGU+EHMOrkxtYCDPJCgN6qQ2fJSA08Pc5V2LGpWFpBG80B2ZgmRUKsoUE
JfQ0Qn4n2SxnRgxTbnlYZofRs+ig94d71z4gA24nHHKm2IwbrjQsOEjOEzAZpNYiaMss4aC5KfI2
MEXUWiOFkDAXDLicC5VJsgu5zZkSDJXXaAvyh91Xry//+uZmcPL6rH9xOzg7hWP4c5wKpB6I5LtN
ipv+yXX/tkaleay4sZSn/avXlz+dE9mP/Z+IhsvEpvYg4XmaLUmJwZQvLfXF5Wkf2d2+uRq8vH51
g+RZbgSFOFox1jDKVNO2Pf4+gjAUeciSRHGt92vq3Zz+OOhf/O3s+vKCFKhzS/icp1lOwhveCMQI
fobwN2hteKEF/wjMhMsAcPB4kkHrXGhN0VPjUHkT2usM2hH03wtjcEfUclzwJ/SCkbhbrvPtF8p2
TD5RfvPEPltyc/sHZd53buzAzW3/CnpHmJFyJMYFBj7qDjZgKHRepdmw0DBcgiqkJBvqwfR1cvUi
UzOWpsun0B5b8WGcScljE2qu5lxBPZwXIk0hL/BPQgBTKt/WXnXkF3vTGEUyMJmUOY9CEAZizAGm
lpBmMYY5iRA4FcEP2QJDXj0FPLqYE2QgLCC7Raam5AimsgJ5kcQCYS4brWBQQqYSVBThZcLmuFFC
IXMl5iLlYwQV1MgwIZE58eOOyBLLJLUngAyRV64BkVPzdF5BjYNdVDye8Hhqz4g0wBhBetIT9TAT
BOKRSC3PGZsiL3ewOC3IIwwn8jxTBnXJU2aQyyyCc6LEUGMwsnsy3IHgjfrFaIDXzfsHmXgn1hRU
MwhHYAuRc0Vs0iCVEGo3aVTB15eR0RVWECoQK3QDRDf0ImrPnB2LCUcDGjhGOinOUANhgiYwHrc6
q4kQJ6Jfsei3ApuM6/j6Hew2dwfxZJYl8Lzb3VgJPhaPlK7wi83aMGzqsM7Mk60DuMeV3b9AKDl0
N7GkJmzE0DeJw4v/JlwclH2ATaZZJoXBMCwzh8Ifi1pRy4ivgBOkzc5OqQdlxTmTbMyVXbKuajeb
Fb/eLhsCmww2eV5enUGuMgICF/IIDNlCU9tCGcSSmZCUXj7VfDXeRBbqKzAz8ZMV2Bgp8RvJRnBQ
JV8MYhaTHFqwXVGNW2FnScStYlKPeOVTn/slvvD3PC4Menoc68HMmRXpLJ5yY08EWwlGyx3E7M46
DaCmKBjZDfmEpaMIzgw5oqBuh+AkzmazQorYGTXkZsE5GpdjqvHOxJg8sUJIz5pbqauz8oiXzBA2
lDC2vmHtQB0WfAjULI4nBCwYoZS/ROeUtey8CcIgoIwi17Upjjrxp4RCs2zeoNsjNXKRWIjYtyeF
uDaERChMzgwhnQjGYm4VPSeoRZ3KE4iIu7To5jTAzctZKuS0splkZakzV/KFrRDkFI0aIDd3pHW/
kE3aEDqPhHeR0zUKgtkU9do4EgQbKlvOQUfeTxtEHkPXpjv2OLceMkWLTw2rhA8juOEIwKkYegBO
/Gdzv0f4PYsmcQId7AE7Dvk6eoIx3EEl/2RXUTaFN4RFecbhuPoWNnYS7I8prjIlPfY5mKR6Shny
DD4+fgm+CcNcYSPK8FhyMWB5/vENCeMIUp/AvtyAuibHqOv7o+0+31QJo3CDFCeDfTqJtwzjvazU
ZcBiTRN4PFqMsbvGiCpsVI6K1BfWANeR6md4bIvqFuZYG5LMOlKnnOfQjQ5xQvKgRjdAuuN3GLZb
ObwLbLu1wGaCyTGnKxqexETkrouoMq1sBVyw2zCnlkcYStJPiinLp1ZZO9j+bvWtb6vR4kLjDEWN
k3pQL4U7cMqHgsnOm2EhTeGaaWmwB7Exa3NqsVjgyRt2VH75gFCeau4ZX/METe2cYJm+vOl8z5NM
sa38nVpH3id38/aFeL1cvcQioA0j5L+jYFUUVLJcwSqrlF7KuOxw16pQCV7UJ2gL7rZd1Jz63myM
nGbU8I6xPiBiapPQBd7FIpWnQhfUe+MZI1QbAu+y6hAKamrOMmrMXDlChihCIgFLnlJBa1tRZQuL
yytp9qLfTigSFK3oNnaMn4kfW9svVvoJnjRCv5q3SbD7ONg4h5fu7Cx4bz2GOkE7+MLY9IVWs5Ft
zCmD3Hbqg2nnOlucB3rWMnYVjSDcOK4izcsuPyPCm08NZEtjzXHwwk3cyaeiY1LdibkyumOvQ5NM
myhWBu2jDZWNToJjDX/EK1GBZdLeYnBTSg8rE9tbKVfwq26/3GstRcygTsbVzlDrNBzTDUZ57TBv
nJiVM9Bleo3bymfuFLd6yi65v9ZLlJINeN31W+6EVLt3BaYl/bvN1FYi+f72antSuzVETIrb9sei
32QFMrRGELxuDX6Cm7CEmzHyH5mcbhvByi9+X7nok8ZfUm7KL7GLAU8VEaaUSyfNpaScL33mYG+b
FOvsbYXsLuK7S5ojXS9nd/F5F3yNy49tRymF40IpjH2ESZmVV2lb4C/PTk/WX0Wj+7/9jDCiLNgL
PfAlYcBSbHT39oN/WfdNCfNDvMH28IKLt+F5R9IbycF3T3rBv2sM7CtCyaPavUP7QrhgsxJMdg/w
99XZaeCAY00sLq8ApXZ13cAMd4VF5nRJpdeHQtKDcYxf02WrIlN4vcUusVfHAT/XJfX1pLAPZAN6
8znu1sxJOZNFXhni5N14cvtEFEX+ntxk4mQZxXI09LZ/fV7/3f/72W1QbSL6Qa3QoALbnbLWh8GT
J9v392rO20YAIf8n9O725y1XeENlZu2mC3skdF2L/ZWbXZCQsRtUQUU0EkpjBcVi6vWk4VL6qPrt
k7Ycn+SKIV67psE3RL+3t7sSs79Pq84y6pzJKjzaumFYPSmAWm53TcNuTSPJ19xU5zBhuozBVhll
LtTvMU9d6rzlqIy7Epf3gLIQGH/Pt60Y3rvzlBse3bsetVS49q+49hXJZwtUKfGB5y1PS9lnk6Lc
a1OlMWOTxc602/DDm6vq+9kFJtHqKKpH0NrdBxHVvZLRsZR1Y7eRqTYZuqtC0UAwaNU7thbsVnUb
fv99a8avba/FSGszaj+bx6qHX+PW6E238V2DhKb5W7GgPCF72GUbaDHLltIKTG1m/K//X/kwHsbD
eBgP42E8jIfxML5s/Aebis1+ACgAAA==
EOF

RUN <<EOF
    cat /entrypoint.64 | base64 -d | tar zxf - > /entrypoint.sh
EOF

# These are the default ports in use by GCSv5.4. Currently, they can not be changed.
#   443 : HTTPD service for GCS Manager API and HTTPS access to collections
#  50000-51000 : Default port range for incoming data transfer tasks
EXPOSE 443/tcp 50000-51000/tcp

# Default command unless overridden with 'docker run --entrypoint'
ENTRYPOINT ["/entrypoint.sh"]
# Default options to ENTRYPOINT unless overridden with 'docker run arg1...'
CMD []
