# syntax=docker/dockerfile:1.3-labs

######################## STAGE 0 - Build the base image ####################### 

ARG BOOTSTRAP_IMAGE=rockylinux/rockylinux:9-ubi
ARG YUM_OPTIONS='-c /yum/springdale.repo --releasever 9'
ARG RELEASE_PKG=springdale-release

################################################################################
# We build the target image in 2 phases:
#
# - The first stage will create a root of the target distro using the base
#   image's commands. This results in a root that contains the yum/rpm commands
#   of the target distro but with a rpm database in the format used by the base
#   distro.
# - The second stage will copy the root to / to create the final image.
#
# We'll want to do this twice if the BOOTSTRAP_IMAGE is a different major number
# than the target image because the yum/rpm database format changes between
# releases so we'll want the final image to have been built by that distro's
# tools.
################################################################################

# Stage 1: Install the target distro into /$ROOT
FROM ${BOOTSTRAP_IMAGE} as stage_build_root

ARG BOOTSTRAP_IMAGE_PREREQS
ARG RELEASE_PKGS
ARG YUM_OPTIONS

ARG ROOT=/ROOT

# This is the base64 of partials/yum/
COPY <<EOF /yum.64
H4sIAAAAAAAAA+18567rSHqtf/MpDmDDuIZuNzMpGmgYzGIQk5iNC4NZzFFMT391zuk0PaFnBj1t
GN4L0BbBooosVX211vqqtI9XC/7TPxjQGySOf3l/45fvX45hHEJx5DPe5+H3MflPn/B/9IN9xmte
ounTp3+a+n75S9f9Wvn/UBzv/reM+zeiIX6j8ME3Vp/Ux298j88dTGDYn+t/giTQf4IxEidRAkKR
93UwCr/fPkG/8XP8Sfwv7/9//vRclmH+dxCcPvd8U3av/dt+KsA6O2YQAH4qT5tvf3HJ8Iq/fuqP
R9A3V+Cbz2B4UdI+GaLxyXAYVWI/va/4xKg6q3wpBoDWlDRGpPv8DBieZonjAUfnRuTo1kZuCoJo
9DgIHUmoS5Vly6uxzLVA1PVpWQ8408YBAHdqiZln3j9f4NJwtTgEN5dMy8wo7m1DPULugGelkdCF
e+6EGKL7JkB5Cq8eEw6tVgMcVVi10wZMpvZLm/hmeA0HTy2TfhYWbpD5YFCd50sqbGVbsGKXp9ta
e7Nolkwt7woHvFDQalRMCmhUX6jyxTJ5k1Awf9AbHFRQoSTcGetjtTbi8kDph1/sxvjIHeilspTz
EICXwnUGsiRdoyhiXkEvwq1H6dGUj5dFn1WjPHvqnvVdemnvkqDbNjEO2H68LhRXoVIVAhJLTIxv
OeheXk9oDIalF0LiuZOQ5uKvC+Q7J3f308rEH1ecsgJZKatya/M7SxahSeeAXqd6UibamXWgvXHg
3DxLlpvnG6Px2ZXwthdet1zPTiUpyk2gN56DIX4J9bBcu82iAdw1lNILz3BSO5Ov4rGJuvvYj3DG
0BGR6FwIWGs5lJvQFDfGyihQsT3Dmbo5V3ZRLliA69EgJlBQCuw1t+VhcfOnuagw/eTpTIClS/xy
e9lqGf4IFI5iUgfbTQ2l3ClUzlJHgScniV0BZgphRMbTSUfCH9e2m0PkeVHc+OgrLLF7pFBYBvFp
Ukduqjm/xPR1OwNFq3LAtKgKSqtqs6d5Fdcz58/kacAUiaBrkJNimqjruBjjOewPHxE02hpY0Wc2
aqMt2qQZYOG0R+jtTeBrjcS7rxBpXqHnHpGHdxK3D3EbHu8yKOncKr25R+gwR4xoU+a9yzoXA9SW
OsKTkOka4/mNl2iu8CTT2pzE2sZHB7l34qKRiTvByBz7VhTQDhuwT1ArpJjbHBVgzeJGF4HLFrXE
bhIvFBJHm1L2fvkFTSusRf/0YVVo3wH3uK+9DgtcetDxC4BbYudP7jmTQtGFmamdasizK1JdikJ4
yH52Npqrh7gES9dXy0Qdcmy5YnLX+0Wq2skDagokn1SJY8vVeoCWRipaT/Ks2Cn+6HPGyTD2DItb
D3tns9B9xClO7o8m1stYxBrgCIC+4Xr8WQyyDvt8dq7seHX9cn4tB1f6fFXdpYxJzj2Gn3HUmv6l
Um3JhO+cjIU9HBjA2TjjdPMwFPNZJIZBL35ERzNevZpK6jmJcPlSoMJoN0Xp9edxQK/9KCSrionS
PhW/BlzyEeyZP6BPzX71TlEKdfXEQehQPHbbycgcm1s0UWI17C3D0TpUn3pTLPYGgvxobxagdEGo
lgUleJDx3NZQdspigpJ1Bn3ftmOSPMESTPNbPVWubQdZpx1+XxiLvTyOfUwigIDz2MghBnygGoYa
3tWxfMZ6QPNRDz722JXXxdgUdswvukw+77xLR8N42gs8UjZ5Hgxgbivr7teZ9LzVj2ckJUJnoqe6
KapbfzOTdJeV9PmyWg7F6Jfvsap3KW7XSfbC4aU1KHDxZiP0MWOtFK64b0RwT1zyfHo+kUCPbFWW
cyE9A/V7hXsZTwU27qJsjiY5D1khMhcc4MJ1lh/YVRqgB4abeVtdkTL2I5aRb7YW8tdwvkypXZkU
98DH9bRoeH6/UiYGSV0NeEBuMy/H3PDI4vZSJDg0n3NBOAty2Nfn9t13wHd0aXxPMrzG/SWK+Xsp
jPrrKMzNprnsu3//NGVz/u2bNussG7Lp2xUG2L5ts27590/KD2cBYJ+FN+HJuFXPb8LjBFA957kl
X9PhEhf3Hb4qStTNwbrJbVt3iqmvOKoy+uvm8qE3txlQx7KA5qZIlmSRs4r4cnHfg/Fd0uw+w3LG
foZLJspnGfeP0Bpq3kROtAmSuHiHBHlJgaS/omhTM1pxwith6qTR0mkA7iRhErcdkqmjlL30glWX
1SqxZ+y9ngS2OoudkpOx1VcAOtAC6xU4sCHNgvwWNB2dWr22fthu3pjEcUVuz5vkTOIFXs3uoU9e
xEI63IyOhGqvHoiJyqYtto0jYy4vvmt2TDx3hjESdtxsyUUL5MdY4SnV2dCL920y7NcKkzO891zB
HyjAgHWvjnvkxP1aqfqsj+/gqXD8Q7bI6/MSmLRGSboiVCr4AsVzquGeL5iDpRlf9y83HHjmr2Qa
cQeN40Q5sAxfgqLrwn0ceHVFcw1EmmsZ1t2Nf+JRoNm457u3gQOvL2S6t1sLSFRg8/dXxi+te0Ch
i/aD854H2AsaOlvVrrS8pLl8ZK4HuvcDvW2o9ISEsqLgSSdg1AXIjkSKwm3k0kfwKjhsjPabSMxp
/d6lsuYWzDBDFj3pTDDLltGt+a1RSzzJKzcl12AHzKfoUzoXvNZDBiePhNK7W9bZo2oYTnlA12VN
R71YyuDAjucSYGVlshTTsjx1owp9dwBBQyiyVMuW3ieId2eeo4jcoN59wImS6s25/NrptR/b9xhq
1qt8MWBQIJceMb8nvNOhHl8I7MEIcWc1Sccc0WfyE7Q17Cw08OU3EYZr6uF14FtDjGCF+mB+JElA
Epcme9DHnZOON0MenwviNqWTlqoitJnfzAlnLL4mbXLZZlFhmDvD0jTEmHKZOaEKCCXPS8ncRC9h
3Z39FT4aOWFhNrYdTYYhVtzu7K1484/Jc+xW3+inI9F7QNOFVL6boACsxWyqIy+aCXW+Z+IcSGEk
Mmf6YekECMYm0s3oRjX8JbLVRsbZABIfdozt2utYLzQHSP5QrOrjvtgWlA+U6KLre740JW/Onty4
kDq+K155QZcgjT5/BXCyds/rBPZsskrYSwXqay21WjHvF7a6pJOSmT2ErsLO2FwJM7Yp1Dm/oEhO
I/SGF0Ei8s2dhMlZu9N3U+BvgHHRPfwZcDesTtR4cY7B8IU48Z04yonKqfKSH/BGrcbxddIHZ6hN
fd4n3HIjqkPBSQIsQjffV/SGe7JWeC84lVYZB7ETwVdd40I8ae863kkyuYzgpB+zcQnStw4R6RTK
V36lgTbPaCwgUgNq79aLInieluHxoQie82oIhehe43GR7b1ehu0qgBJDnxjWRTBp5xByl2+AyDre
cYc6fH3peK1cgrqut/SyYmjYjFy3iWRUc7W6FRWhQ6a2I7ZYp8WCXlgiumn4A7iXAjSUb+Ublxql
6lAG4XSJTOhpCyw4sBHjNSI8PJFqhwfuHQ+Oa+Tz5glanuHSBSsB9n4zLGEOtWA3O4lGjGkpFiS4
byfqSqJEcDYY4oTcjxuW6Xkk27b58FlaW2aw4MjRAzj0EfpGQm4mR6D2wPGVnI7PNhsim2fjXSN3
cLiImxQGnqxd6OC5Trno59UrRTPudQWB8hJIsaHcYPs9A2zlsbMwRLSSSkL4cNGtHD9pO7wfzDWA
9NWSTjxSaoYTwjtiagT9mRCNU8r/GkL8A//3S///GKayK9KoyX47j/mX/T8MEwT+C/+PwQjy4f9/
D/zzp596/BP56V8/Xb/XS2+5NP9Y8u3noyRb+u7bLH2BabREPysFSXC/Ev9FYGA//8Fg+umSv1FK
id3LED+tyLfQtzD26f+ImgOqnzXbv31JGKgMfz7r9nPCgIMv0VJ32hN+5TFkhprSEK97p3e0isT1
dSXc1nmrbM2WCZnxU4v3gb51rYbnVljeKBCGF46XIPkMy2zsi+gpoyI38pr/VJt8KLL1Etz4B1FN
t6vPB3X5tsfAtr+cQ1nHnq4JaBtZwllBu74Nrh4YlHdbtPiIG9R4XXNkOcd04hHo1poFf7qVfdz4
DUBRL6N9r3m+tad0T2QwS2sIfJpQ8II1C8UK0ALh6MxP7HXs0LhMNrdGD3LcfTx8OEEILLfzcZUr
YTitm4TSl4u8Eod/T8+s7nDMDvr4wmVKb83pkkuQMh36eqGQJdmw447irAKk2NsxXBcUX3Fimy3/
ubmhxwcdyuTSnL6NvoD5/u3a7RADK3JZEq+gh8vykBwYSuxLAQSs4UqnfWFAYaTbZtlRVy6u5BwS
pisMaC8skt68YEwzmRXdRqfLWE25XvmQ3kuwHg+gFtQR03Jv6JDUDQOrkdPUs/3wMo5RYBKRRN0O
ccdB05bg57wn+lFP7XXrw3VYgswyASmvOcEoRrtN7VGIVNw2EwwVVl2dZ6pmZER4xCXqDZYkexBI
m2JCgRT5cDoWsiES1wELTZRLaq4SarooOMAO329+87hxQoKz06jYMHzeRUrhMUdsoevBxSeU4lJ8
g9jhfNUvYC3TinmLFBO86E1aPYTq9mQF9cTfbHtERHYfjOiR8MrYe1pwvrSVqrnC9Xxto0UltjTA
EVzZdO+FLTav1C8KS2zO9CYPQedCkUe9JPb5cHioeHg4FHrpW1tZ+FtbDSGCPz8nEIDwURfGjYEj
TzhNEX6mYvFK3hXErdakIvVSW7dObUKmK/NzQuEtfzGBrr/EzmdpJAJvTSQxb41E7w5Lb3ePfmul
z3pJwGiaLWpTmEHuDok165QIstP00meCYQ3B27mPxMV6AZ3l4yLLmQ3BNfri7qqbNFp4ikO3Xfl9
KdMLrasj5yd5lxw5hAXPhr9VWFvOJzhxrAREeGx5vVYZb+dzG0727VAkYtAm+BlQD92jMIZPu4KS
RFGB/KfAnHnTHo/PWQmKR8IgA6zCU+SEi487NXMJUmAYJLF1d+V0z16Ve2KSOUSfwUJbft7S/H0s
xlNzL9DGyW3K3wKAnMoch51rzOpKN4OOoDxo1Bsd5fnWI8jeY7o71u0ldkX0hDDFoiXHk0JJuVo3
fiC2GkiaZr5GefB45XLbOllyxjy4vWeR4v7g0VFsEtPabR3l77oVo93m9bhJ05gEmoYwCT0LmKEZ
R6qm71eDTLuc66NJnhwjYBhHaO/KenO6x7YSFGGGz5OErLWo7FsSP46pa3mSYAHQd6DTGTJPIwT+
c4KBhgepGd0ce47WfDHYSETmY2FMN+CHoBC73jEenmRjEaHJS3cBvE2+6aMVTKJo36GQcEmpuNP1
WG48z3Z4xjl+8Bw3Zz5ebh1nOuPZCdE9Z0O6oSZ7JYBZhXwQfp6Lgc/v6aPLiEeA+qh0FM1KD+us
dJCtJy67xoH2jAskzo10zdvlQb9jr7w7wGFsiFzkyapmAryUd5MscSMvDr2DAhRswipJmuAWwQZu
8L3N0kjjkJXaQk1bSNMT04A14CBOtEJb1Hg5cLhQKKzj6CR9r9/aqFX65K9MFvyMD//jP/6mLLZy
59biMyn5L6uDVGsYttW5EWpVVwnkEkjM8IoUtMI7NDjIk5KHW2jvb4DGauDmIxuK4hUX0njhqnu3
m5i+zh5vmtj6ujIqTdD5S77ZHRhCqK7hT4iC0onNuxmJ+KAHDNtiUGY6o/MZ8V0gyI5DneWswcNx
zcpyk+zpwcUQyG2VsMU9ZYaxGK/hE967VtbFFLg+cO6s9YKpUvQCSZeocPxw7YTMog+PFG8ceZ1m
VWorUCqf4gSBxmazjIyZykp0tFQCo2Vbz3FX7zAktY2sZO3ayonllBdGXWn47bD7WpHIo4M34eLb
74cTSL25QuvhPI5GdwF7cvGZuGEgy/icL2ImLa5e+LawbH4xgrP1joUbwPx8tqOydy931czb4yUc
qLdQU3gRAINKgpF9+chUL1CudjEGvr9WojbO2r3jCd7xdMk/SuGaBq99DMqJpq2hf7XGxKXkzXGA
mlklWrhuniXrXhZnAjSyiQvzxrhpQ63cuLIirwf1yjfMBuG3p9fu73HZ0nidlJTpygCE2JwqPd+2
/Sz1An53+zC+TRPMCq5tqOWy4LF+dpabNxdWOm6mdpKe924SwzqLc+9jwDJuRy+0FDi6SaGGHmHQ
pyW8LQempRK3usODrLeE173BFSpGKVhPahjxaipgpdzrrQGcx/n2ZKQ1qoF6ZlCVcs9qQid/0Gkr
7XXlofaED9vOTE68E0XB5RKt6RDFww+mfhFg+yuHpHXw9uMST22hhxXWZxLy5S1pmzN8MPev3pzG
fyApB2m6uG1eQHgwU+jXRdhSx5uteJurh7e5P39e6V8iK4B+3/Nr+nvzJNPs0Et1XzpJxgbOPK4V
intLtEK5MBcOG/SbfqGlmN4c9Wv2+14CbxYTBbOXWXpmGSZ4M9tnVkt+ZDXq4k7eRN32WOkKGgQf
fYrIveIwu3HchHkE7lq302h6wPnjuHfYPvfgmMkhcUuHHCY3bOSguCFXzqtU8S5kQ0/naASPJxdq
FxNWrgCKBfqix+jFhag0V7K4mOlhaU7ci9ZnQxBCj1TXl5O9LGVJVGT0oerUjvntqN3iqb2lwVjx
OSstWyhTinY0ApyK7iODtURFOX+m1aDxKFCz07xB1dfNiOQbnI0u3gtlkaJNiwC8Kg9L5gwIgrIa
AnEP822gX8cG0/pyIk5JIJRY3FQqCrkwyxOfvkQxLHaJJmQ5Q28EoEQH3dBKQkW5qxNoa3vd7Rml
GQUlZwf1W+/d3crKp9UHF9D3VXUQb+xmeOU9KlujOIDiUkxxpL2fLsC2xNCY0UXOJbk/m/kiKKhE
5esoIqqB4ubIJY1tcXZ1r84WQ7S6RiQc6M5CxdAWaeHReKLD2F3L17PmB29hRBl1zuI8mavnPe2e
woaejK9k9gyHs226d+RvBQj0fLbe5qjGtFPD/XUOnaV+GxXXU3EDM+5hLo830ArqOAY9Pr6FSdFH
AStIdpE6FVs2wAuNSWMYp23s8vyixEMaGgafP8PrFFPiTSZZMl7YzG4vxNhemEqb0nSiNHDbhawR
n09Auht3fjRAaZfhjn0UQ0bj1GpjMQSP4rHStEeb4HqHo0tND8EVmlU92sqGm+91QE7hAni3+e4s
xyjbyFzb6Q6Bx1NtJ/jFEzhdQPzX8c+btCLIm+eeJCcwNAYOOMklOdOEAN2GbSnyMOEk28CDL0hd
5cUAm12cI0EQadrs0oA3rxW03Cp8v1q16bXucX37gSB2mg5Q15ASzox7qLRPljW8UEyG3o8qd29N
bgrbUy13ZFnE8TH33Ln4zVX3bslprxd2sSBxAARfes31tV4xo5Ojx215G5vuPSpRHXOOwe4Ihs4z
K5gpecJUt78b/dtsOUkQTfHt4oMCAJ0d0d9gkn12Lmpoh/qW0XPhZm+tGGZDIhlkXsfecUCUOKoa
QYRlrsXFjUpDcZFijAE2nnb3lqG4wPRXnOMVTL4ioSoKRmf2FaxOb2Vm6qdre9YkTfml2qRiAkG/
Hc9NZMADmI7IGtFrhj7uaDfRrpUyKXE9iPphPgU3fneJSUPFVJubqz4LdKy32lKQ3Z+SvNG1lQfs
s10RB2cuV7FMFgnbk3sgv5D0qo8ziqgJikHGrBZCcxtXYkD4yjO6IfQS/dbvAoXUAC3n8e4Vj7sR
WMKAgXbl+/wcPwo0LQ9IEoeXV5j1Bex1LSRtzBO3vhQGEnHf6l5LJhkgW2xMyvCm2+gYNv4Oj9yF
9kKh7+bLRmg7tHM7YgfFs/ZVaXAZ/ho9JjWeNc2HbEXTAOZ2K67pOBQ2GjiwDRur7b9kuxWxehmz
qxvkInG3JbuSpOccIrDq6GhV+x4ZTezRzzzAVNHtEYbeZU2KyQzWA5JzmuEZmhbfBiXgRfo95bP0
n53ygV/O+dyXFU3uJz4YG+UtvtxctPHnrRV4Q+nb2Bq5mD7BKHEAP63w+e3TPNuynqeys3z/Vtvz
TSHCYmIfWhheNNywQQ9/1IRqEqs1dyZq2+cQbOqsg4BBlC9usdMIyV7ipaFfDrielRQI3QVVZRLj
dCk1nN18zVYhP8qkaa1tHGFKRVO1eqgF8MrZphcLnUlzNgtGyKBciH5bIH2FMl5CQrtf4561br14
cPdil1X4AhGjJNZ+/LKufggkzkouukwHbMHd9shpcSlMQPfQPFmNXs6LYgcKXT1YT7nletcuKynG
efI2ozGUiKJ1AXR9wulAPDw7Gm8GmEF4XavoQr9c7X685ZvVO3VSC2+NOIM8U76/kcv1Zuv48crS
MAqegILeWxVZLaUpm3CdM1+udMVrbJKG93a13ZxqiNDScf6yECBDYXrZU329Kfpi8Jq4j4CobcMT
dGmfA8ui70kuPd9+jmuawGWs2yDNUruccyyD6sNrBSoKpB4zQdpdhF1ETjQCCi1s9RiKOKNcyfR1
sU+5i6OFamKEbxKY2d5y6H5rjjw5jDeV5PNFVJ+GFoycJLgDPQEDL2nZ/Jqfby3ZMTSq3KU8KgZh
z96zApfvtuHF7aVz8yXNdm3wVDIM6ybzEENPrdZDAL+yo0cHxRoYx+f4hImBN/hyUpQu8vdr8eBx
KRjVUWepYMPKQGKC6axWRo+avXJt7AqI01ImtwH2G7rLTgY/vqxowh2N/VUm5TfM/33O//5sTXR6
i5nfsPav+JX9XxCBI7/c/4VDH/nf3wX/+VPnfxNHc9bP/w/oojb77ssa+KcvWddP/zJlTfYuXLPp
0zefmPeR/gDacpr6qSnn5bsf1te/npp/ucj+05X/EU3J87t/+Xyjz0f/+nm4ffe1vm9+dhOgGIrk
mSX1dzCQdVHcZOn76H2yzo7v8rLJ3vcC/+TORQD4eYOiYZiXKYvaX20TPQyPL1f+ds36scrfqGX/
mP7/fK+f5fn/W+KfROFfxj+GwB/x/3vgP+e0+cPA/1n+K+mn7Eu4/yJafhzpv4yWv2XR6GdVgj9W
+HkF6et88LPw+sNI+SF8fiVofmrGe074qZHfvIb3g2R/rrHO19J/RHu/v/EftPv7pv7U/N+u0X9l
//+yBjbrFv3x246xX93//dP+fwgm0C/7v7GP+P9d8M+fHln24wa55N37/fyn93//suyPR8035N+3
zAt/i32L/9Eqr8YIegdCX3bJqdwRXjjzVif2jTMfPBRBDFIGNO9vg7HOBJnI2NI+M7C864d7f1JA
sIErIwnXOWkJG1wNDc/7YVZKj3Jm+ikqBZQNLHHgWXrRaOdm8xExPPS0J9lD4LalA7CbQMD8fMRY
cRo2YZaPCTrX1F6KgLHCiuYNwX2hXNlDfYg7ZkjmZxrmWbnfzat7t00AO7AdX8uaYi7J2IrlSNEe
CZd7wwWuF82FBVFo7pccpak2xtmLclFUMdAq+ZrdrTEPAW8mC5K9UBEv3vJZDMHHruqvdgfFvLSb
PmqgtBuvNkv6Jii/tJShxqr3T0u45BHnzBXgvVbtYfKj43twesoVs049vxb223zKuTVIhT4lCE6M
K3cf4MeePO9CsxhNj7fx4668YGCHB8yp6XPHMbTN7o3l68WOgG/T1BI3QoWE+XFwD8JAEOwQLiiU
ZTrHYfILY9jDhCodkAZnb52OHnqwhTIrayTCthqyUohIHB+Boz0F5iXsD0MplIAZhKd7WncClee1
jK/IFAAYeh3RWdKddA8DYljvumfVqeP2J+kx/G6nO64too/VqYebS2Le7hekfi7EzHTvShIGkIMk
kDbayWh8Ta18U5VX2BGPgnaUtMj05ZVfEsNCQZ64quFEXrFH09flTV3MOq+pawVofkvkcuVv8rqV
d0QqhaO4Rs7G85yPOxdTZ2loC6bCMcHntYyW58rIyiOhqh8T6rzMhR4O2fB90Q5G/ZwbV3itiTvL
cA4alXiqDdumijxh/n51d4jbpHggLq486CuQIG6V+vKQ3ho6QNxXKlLnj1vFK+f7ld2rQDdf4uXL
yu4PC7sM47AAS985oZAY+om9XxlN073Ms7Y4Kjk00gRsa5ABIiQK2c9rcr+k8MDrGtlBAhyUxz6K
gHluA4sIzwlxpNkfSrDxbF8SCbqx1imqKuG5Ubd6CapGwPq7+BZxj06CfCNtJw2hGhUQLlkG01p6
rEu9Ye39hRzmlrm7QyovrKdtg1k9a70QA2satn7P8N0QodCoDFErZWjfAEybLzluEuLYUgjZ3/zh
aByTb183ZWYHNFXAOox2WffndiTmI4CLeFIrhO5GqPQ8AwPs8erd68WZ7CS5nCYyCBbZr3z5VCBr
fbY1AWrYBZM3Wiyr/JlV+6b5V5sw2Fcw43K5Ak9znSVKSCWpsQ3MfwohplFd2vEbjdE3ctGYuWXQ
Gx+ro/NoX4g1XZ9iaSNGk2ABRetA1JQeXOv3ORSCyUepesqtGukQzV/LzJTBZkPha/EQLYJ8JXV9
ImFWxyw/VCDUdjePA1CLcMmWwi3CCcYq2S4XE2eXEFnOdu/b0M4xRBIlhYkfbis9SNwLLgnjqM6O
GkkY3DggHOmYgbgGu8cpfyPeDyNd+VgDbbWBS4gkpwul+hbc6l3DoqLKQejFz4NrxjNmTsIoCQSP
e+nhE4jvm1mTO58oTRymrSMPaMjZJuPbELFG6zqgVVOP440ydf7qlmFIRIqpjiswqBcsnnGkOl/i
Zt9tstAt/H5yl9WGcvdB+u31Xun7GhbxbaaL8xDERoKLd3C1Dtm8UOBlaOp7ItmxByxicocD3+li
4P9VSZO/jcr0PC+TMmo+/Z+vJz5dL//2929iQpA/RW/n3dvrz/R2m+Z6YAqN0odn+7TqhDTAYJpp
8bGuDVnnr0tGKXTkEDl+z2j36IBJ6u8YOh+HWBfC4RVVeL+C02si+bsRIMdyQUYQDnPVZa2OuuKE
PNrSCPnWwDkZ1ikmcGUamtw4N+wf3O6E9eNlSwe/x1wOJcN2pewkJ5D73pbX6kliq9UYB2wUlafi
GIXFqA/g+c6V6Q2LRyM8dpsZjckRXv2Fzx2XH0tRoDBjGInQWSdG1N0eduGLlLcUK/IKTpEJEGVr
IiawJTTFLhXaFXOGF1cZFgWejy7dZNKf/WANiZufKGJUWMqcB5wnGjWNJ7oKZkB+OfRY71gMPQxn
HYrCxJRIk4nL426HulLW9+uRlAezqeM2Vf1VaOSiXq9uHhUg4lgkIEtafIy3W686TxN5U5r/2BQs
qJatTAWKd+qICb3p3TeBhUpWqPqNN2Z6CV6yM9A9qAXWVz7VyTo/L7bSuG732lreeBN4uzmPYVbT
3JB7mLvN6VV4QOiDVYzIF1KOzIycr8qgBrrbYEYKD8GR5z5UpzyKjhTIKchacXQpdyEXZsOHE1rH
B0siEc6jp3BK0uu2ExGtTQcgRgsajQ46LoyvTzSYGrVPJR5/cSx860EacVJFDtVGfN4Rz5LRZmlF
G7u6FJs9CI0KgBZjlfRcC5L3qsZuhCkFr56MKP2o81STcUbmW0aXvGI5lwlVlW6HCFFPqlZ+pDdu
+IHefkZrjBG24RAgzTNmGTvy0teXX0Hxn/d7f96zpDUB6n7Z0ASY4pcPrcnxdaN3aUro543edEE/
GVNOTmEO6efMMcUss3TCffmBEy3JbDF/YTXgD2iN9mA31vniGqaVPr9p7Sge+42qxjzXHeqhHDLX
TJGKFNJrGUOUuQ4NIB6g2cWUycG87MZYuOv8MwkQj3LlXBq6HD2YF7305LkqGSjC3X7DmIXwbNlk
a6dKZkBDR8Obd9idm5nmTzL2xfJ2tAT9loACco1Nyg+kvpZMP4VsZOJQsNHEXVt0K0RipeKAVT+D
c30iZepIAcwVoifDcLHcBImm2PWWeO8xbfDPOlFCmdZxODoEZrQfj6HsJ3ezRyCCkrfMLFrW1CUM
vAeXWlrPPttzkdyftTNm0La3w5OyTHNv7FgzOTaN9kexxQJiX4oNiI+IW+sHti8W8egrklEqhW6T
LsfzDmNxfYIU1RnvJ7Nw9zg3zfLZEUgZyhoRhiCWFsCI3ezxcIfjdd79WRhkSgWF8YZwMpbtojgw
KwTFERhGr4MU51FPcKN7c2YQ3dihOSAfwCCSs3YcXqhgCyRwWdyoeWXPkboUljzotq0MBF2FHRjh
wYI+iYorBi2/g/yhClJAnYBLsP5omuBVttaorEF5Ftn8LTzUUN+wupeqUOTpAsLK16HZ1XOHMtC8
8W4S0KOmPn0RmFjbjtkO1R6OTo0777MXBYRbuI78nhVpyPEaVwxh+VHmcXzfobc2AuNp4EPDCdoL
igD91c/jPmG8phIc+UJETWWvIaqaqmI/DI+0Bf0i+kdC6y0rPhv/iSxNQpR2gsEGzY4HcByX9tY+
VuC7ur6Rf/Nm7r8Dn/3/Vzr8hvrHZP/+ivwfRvzC/yPkx/7v3wf/+X3n/0EK8HvJ8zV9/Wey/9ny
FrRd/UdJ8p9pqx+u+Y8v+fA/uNE3//I1Mf+vv8icD1O/9EnffK32/37++2s5r68P+/Mk2efb/def
TLQDPzT3lysDf6nFP1sb+Hsb/ePt/pva/ef7/5e1fn3g/nv1+83jRiM48YMohv++iPyV+EcRBP3x
/3/AKPyOfxKB8I/4/z3wYWk+LM2HpfmdLA1L08+/ZGV+cDLA974n+qWlWfXCpO+CLUpmX9PcgV/Y
oxOUKtdJC3LdQd7bQHQnGLCrTolubbV3chSM/TOiXrVYtOoLmi6NjCFKTXQWX8Nrs+cWnZdeCkFh
3V4UVLqPMMgBPPTMWGT1r+NYzao8o9U5Qs9CW3vKh143LqIxGWZuM3edebzswBx7lGsVd8Uq9Ksl
OgDsqxpb9OMgaImlG/BVHRVnu3rLWHhpFzARXhIcPu4X7275kHbTtoS9H3BzXmZb2CUHoFqPSNT5
HkWJIXLXwfEltymvBuU2K1oxNbwJ0mgVpuFB8PAE0fhODjn1PO6UQOcO5gO0kBwx3AdvQ3RF+Fpi
nYyoslc4nQSZGpnq0k0wiR72HN7leAHlo3zbDW5AcPGBTXQEYNZ4lLF6atVDTP0gUytESxjwqo+R
cbHh54rKXDRmJGT2QQSKEotNTxjXDt+NHeOiioCLrU6pkm1MHd25CvgZ3OQ4KTCLTPW5DG/TXdgO
Ugiz2Yzcyc/kZrcSviLwaWjhcAmBdqN5uEbU2apX9Zio5xDWfnfPdCWQjG1IW6byNVdz45GEKFLf
Qz0wjH6+lKFy9/IGAxyzu8+su/dduERtKmEjn6DVvX6EhqwU+tCIejvjVRpc+PSxzoLHm9B7qkJT
9pk7JOcCPWbF72FcN9ttWl+hpKtRvz6P/WUZT4Mo3Lc7OwdbAcl1WrlGiOOQJ2YERlouhFHLY4DW
zun9xJ7Ad1Ghg7+HpfnA34Cf+T8Y+gcZwF/RfzCE/uz/v8HEF/+HEx/67/fA/3z/9yuO5X+fMfxN
vpD/7nH5gQ984AMf+MAHPvCBD3zgAx/4wAc+8IEPfOADH/jABz7wgQ984AMf+MAHPvCBD3zgAx/4
y/j/EhTu9AB4AAA=
EOF

RUN <<EOF
    set -e

    if [ -n "${BOOTSTRAP_IMAGE_PREREQS}" ]
    then
        yum install -y ${BOOTSTRAP_IMAGE_PREREQS}
    fi

    # Yum repo definitions
    cat /yum.64 | base64 -d | (cd /; tar zxf -)
    mkdir -p ${ROOT}/var/lib/rpm
    rpm --root ${ROOT} --initdb

    # Create these /dev/ entries to avoid 3rd party postinstall warnings
    DEV_LIST="null urandom"

    # Create /dev/ in ROOT
    if [ ! -d ${ROOT}/dev ]; then
        mkdir ${ROOT}/dev
        chmod 755 ${ROOT}/dev
    fi

    # Create the /dev/ entries we need
    for dev in ${DEV_LIST}; do
        if [ ! -c ${ROOT}/dev/${dev} ]; then
            mknod ${ROOT}/dev/${dev} c `stat /dev/${dev} --format="%t %T"`
            chmod 666 ${ROOT}/dev/${dev}
            declare ${dev}_CREATED=1
        fi
    done

    yum -y ${YUM_OPTIONS} --installroot ${ROOT} install ${RELEASE_PKGS} yum

    # Delete any /dev/ entries we create above since they may have incorrect
    # major/minor device numbers for the target distro (they'll have the major/minor
    # device numbers of the bootstrap distro).
    for dev in ${DEV_LIST}; do
        varname=${dev}_CREATED
        if [ "${!varname}" = "1" ]; then
            rm -f /dev/${dev}
        fi
    done
EOF

# Stage 2: Copy /$ROOT from stage 1 to /
FROM scratch as base_image

ARG ROOT=/ROOT
COPY --from=stage_build_root ${ROOT} /

############## STAGE 1 - Prepare the image for GCS installation ################
FROM base_image

RUN <<EOF
    yum install -y coreutils gzip python3 sudo tar util-linux
EOF

##################### STAGE 2 - Install GCS using Ansible ######################
# This is the base64 compressed tar of the ansible repo directory
COPY <<EOF /ansible.64
H4sIAAAAAAAAA+0ca3PbNjKf9StwcjtyciX1pN2qku/cxEk858Yey+lcx5dTIBKSUFMES5B22KT/
/XYBUm9akmMr7oWbiU0SwAL7wL5AmnqS91xWfvKAUAHYtyz1G2D+t7quWpWqtVevNOrQr1qt7tef
EOshF5VCJEMaEPIkECK8rd+q9r8o0ET+gXCZfCAtWEv+jX1rv75XqdcaIP9avV7J5b8NmJX/wBW9
SBq28Dxmh4ZkwTULPlsrNpf/nmXt5fLfBqwjf4f1aeSGdzYPa9r/eqNWs2p7tSeVWqVu5fZ/K7CR
/EeUe2Y8cjecAwW812hky39vb3b/10ABYP9XHoTiOfjK5b9DgH5QgE+Rl1yETIbcG3zyA2boR4WB
LbsB80Uz6Vz40qvO4b5gnf0fUnn1ObHh2vbf2rcqexj/7+9Xarn93wasL3+OBsJ1uw7rcbqRG1hh
/xtg+1H+lf1qwwIXAPa/Xt+v5fZ/G7CzMRR2CMLxm87F4cnJ4cXx6Rvy8vScvO1FXhiVXyj1KNwB
bwFRH2p9JH1qh5KIPuFeyAJwSU3VTBJ97QrZ7dMRd+MmSWecNDpchgHvRSEXXndEfxNBF/RYwl2T
VCvkE6lW8cf38KOGt7Va5uiAuYxK1iSwL2Ah0LkXua5kMcNL6MFtuOgLm7rw+zc6GsXw+4p7LOR2
FtZ0zdBTcw1oKxjEoyOY6FjvMxIOGXn1vEPQ8UoeiiAmEIhxjyMGWSCkx2yBA2KGd9QHFqFgYH82
yTAMfdkslx1x47mCOtLUW9sUwSBjl3/8SJST73Kvzz8weZl6/Xfkzz/T3Q9cLOMziAl7KR41yKUY
N3ShiwlNaiEwIITlQRwhmRdOCDzyMIbQ9CkM5LleCemolRBYSTo3TD1hAGeLZEOjS22mSfdpOGyS
MgvtMrCjLEUU2EyaLrDedJaTbcxOhre36QF0UejUdAEbsA9+k5T+u/Mf+QzIJqXkuV4TKaXPbobM
00s0JrP9rU2KOp4qLmuaxF/FCe9ecLmCeXrIlNbcP8v0FHdkVQandsjavFpfkSYsvI0ftvDjdOuA
ndmQGZM5NmIIYAlhVzTJJ3Wrti25lHzgMcfoxe1yJIOyHNKATW+z8quzV8a/jn41NL3mwB98t1ZP
o1apNbD7u7Fp6EXcnbULGxgLTTFaAbKaakUsPM8SbjtL2zcRsB+IDxvIFv6bsKw+yhXWkY5eIphD
+/eIB6zZRMY1m6pns7nAPdBPYV9JawisTWyK6gr0F39cl/JJsx7Lpbb5zJkw5a3vgF1VTDk8uyA2
tYcs2xtEqndX9dKNyx3NMvZmY9UIlqqG1Vhm/L90mJNDBmwe/8tIss2KQCvif6u6V52r/9Sref1n
O3Dn+H8xATg9O3rTeds5Ii+Ozo9/gee/HHXM+08EyG6is8TFqHso4JExSn2QiYY55J4pWRj5T7Oz
hg6o8do5g7UqPyg2SSOzT4KniIjMzG5NInzmKQaeMOpjSrBDjke+CEJtok9Of3rbIVcsJhBKudzm
oRujgaZAiXYHCV/+iH0fnONIOBHcOYJJrxQSGoXC4AofIAY0EgfF5IbG6Ygb7rqZecj52c/TuQiu
Y/eEDagdP10MMf1RFzpoZ4EXd0lIkhhjKvPARc8FNtl507L1YhT0JVerwrDPTvW0tKY98YOne8Ci
6ejS0Ome6Qka2EMTWpc5/Vti+XtKbpZlhAuGYMhcVy/CHjlNUpxsD96P1YoMw0mmTsSUTGvoaQ3L
6IwDtHtL5VYGt0kh/gGoZd6txF7oiTOpxag1nPS5J3LTA4jt0/vWk7eLFwmOvHsX8LL0dBnNS5MY
pFPtTZmZmlpTyamJXZcnOJdZfDmD0Vrx3yVdkbD2cmIsAt2J7p707oFjjAK3fZ8ZJxoijEDLWWln
4mzRiH2DC0ADVU4W1KfcFdBhxMKhcNp+wIHhYZy0ai1x2tXkPm1u//B98gTyZ0ij7KtxF3gAVr7d
5y4D+pRc/CuOizSgqQwuyJhzV5umwKmLWC9BW/QMG+RoyIFrHghvhOqhery+uDjrdM/OT//9K2yt
jx9LmTluifA+2V2WuT4lzIUApVTCTLiQZ4KPC9bP/+54+P9k9fk/nvnM5n/VulXN879twIKdgTDU
p/YVHSiDck0DqU1BF9o9hwYO/4OlSVRiBQk5Z85rCi4lYM6QhuPHHTCh3sChYB3nm/QBSJPo08TJ
iAjPWtDAwyPu2W7ksK7SPz2ZsrSkmNYiMIhdXNflQrqHMS3qbjE3P3Owef1HC/L+zn+reO6bvP/V
aFSsOtZ/GtV6vv+3AfdY/9FG4IGrP9kFnWT6T1NWZ936Dh4E/wD/G3gY3KhmV2gO3RE94V70Afo9
hyjptAMXL5kjAgoXpwG1XZa2j9dzDjFTPLeuudrO0dnRyTqVnTgabVLWge5lx+tn13XUvIuFkk0q
JK7ZV/RD2Pcb2AwVwftRr8x85s4EwDhX5hHZjEDAWM/FycvGqMRL835JvDym7paDP2DP0iLKrSTh
DyOp+iVlkLWp2qhesprmHXKk1MWFJIXwMeEQerNr5sGViAZDwkMMximRoh+Cu/WZ5zDPjonwZpmE
Qk6VDlBrvdJIqZobduEsDshVETUeo/FBFKhEFnwx9BqBfuKyhSRDes1wDUmFxTEXRIUaqnEYI+pB
4LGY18xJCkaAjxpBb2d3duTTVXzdSbdro/p3glNI2B3hEFFaavELK8mSxax0P4GBIi00Ho+lILl2
ge/B6pRZ+ysvUq4uYyHlcKVy5pkwXDWnpZuP32LavYF2km//HMfai/tu7ULoZHqV288iteaxShYK
P1yB0kzLL5Up5J4D5H077w3+CmXXLyW/9Uq79yq/BKc5Xz9bQ4CPupL8SEWYVqvvVYYp0rsK8bFV
x8H1mF9ncRy11uEB+sd1w9JHWiifgvXH6chlZrsCN/RuLumwXpeql4bXoMolHR+W0rI1c0uJBdj2
u2su9xjGPe7iq5p3VW9E2dTTtTNL+aonxFYsCGkfsm6g5fTluvRPmrPfYLv1TIPs6rBtMSqeCyc3
OtmYX3uq/LA8T4QbLzHh2GQL3XW1pE0WcG1MQbr6u9R/1qn/4V76nI+A1/z+R3//v4ff/+5btfz7
n63A2vK/+/HPyvOfat2aP/+p7u/n9d9twEx6jfZFG/Lxl55kHE03x1fwMAnam+lFgUz5s/wz0b8O
pPv//Ojwxc9H5sh5gDlW7P96rVqb//sfjb38/Hcr0OoFpHxQaPmEunzgtYs2w5OW4gHs6NawPv8U
q3/pYcSZS+OeEFet8rAOGMr+QaHQclgIuYNU77K2i/hTo5LRaESD+OBCBbyijyEVZlqyVU6bsJtw
D1SM03L5QYuSYcD67eIO7YkoNCCUNpKSfPHgEB+RC4iuz/SjVpketMowbDw+SSEmaIbixnCEwY1I
MgPr5EZfBDM1bllMRxHyWtwQR5Bjog9hIM6C3mSm9z/SKWBuPe3MAiYzuxwYKFnx4ERfLC520hdT
UIokPtcX031bZWRQq5xwGRi+s0MWWFG4wNUmrMLf1xxSYxIK4eLhEA2JjPzx2ZPDfFfE+M4PiuVy
acT7bjdNU29ubrLT0afAKyydJRpikmOYChFIQtURBGw1VVvzBVZDkJ/Mc/QNdUbcw1yMQp4vx+d9
zIFLdRgxongztVocDsQ5ka2PJyalOz8KIDdi0hzr6pUnbiBlHTB1FiJB5QAXrNXWGRr7QEe+q84C
IOgf4SvlLr9ibkw8Bh1DAcE9rJD6ob7r85DEIgqm35gyC4Vnz2B/XFtkCNRyPLe8wVOTPrc5qExs
JFwHFJczBytAhM2cCMid8NkR9uq837i2ZtTXGEQg6fLTZ89MonRgXCFXx4Uq1Uk+udN6oGaWUh18
6HOihGzVqr8dQsXR+j/BplI/xSuXDkif0RBWT5JTMXVeqxhhKv1cayMVqiZ5BUuwXeFpmag5YGrF
5xl+ecLRVZT379+rqp26+YYMxuNTLsKTYdQzIS9LGJjBR61VJnRP8RZq5jgJPIvDofDq6YkZKPGA
gWLHoJ0js1A3YZOEkQ/5uZQ3InBc5Gin81rzba4/PqSg0LYtIi/UfEZ1kRGwCJ7CWLPQMMl55JH3
iXM2/MTSEgPEfQ26JoK43dJ4uxrvwXfQCAwO2q2AjUTIunhzQNKhGLq/1/JIbFDhEEiD9V7pMzw/
DvhgqE3CW4+r9DKMlaUecpsOBGwmGKA6SYJpKXDO0RgTS1U401/8OTxA04GsSw3N7xFuTZA00v8+
efrPiX7D0r60J/w6IY3/0mq43R/c+xwr4r9qBWK+2fivXsvzv+3AZfrHnd7p927edI5/OjnqPj99
8/L4VVN7kSknh3VVrkI4Zf1DlpwKp59kJafygOlmCP5b+0pwLtrsc4wJXiQTYpsdBQFi1RYDrJqp
X415KQJw9024Gs/Xhks3YuRHNYf6gwJgyoQ9fjdhqL22DHfl08LETJrl8XWhoKocXSykttUl4jiM
0CRfC+6oN2fG1p4FAbgpLLuha+yDNZOkR+0rdAPqm+se98q+6px4BkBW0sa3lHoHcA0MyZhx6+O9
Bm4p3X+66FmGEBDYBmFJl/r4lgWYanzzDmIhSK/hJ5arbazMx+YwHLmF6Sa9ljbGSkjXC4GvB6l3
jkhJXnHA55SIepevAFjQMXSTx13knQQWA5UyT9u/Jkj1b7xJHmCOVfW/irU/b/+re/n3v1uBy/FH
tO8K1dq+WYF/1fGxYRImg4Vtq365afh/g3T/T+cJ9z3Hyv2/N1//q1sNK9//2wBDxU2yidkavnmI
UdH4mHFZrpybgBxyyCGHHHLIIYcccsghhxxyyCGHHHLIIYcccsghhxxyeLTwP8hgMs4AeAAA
EOF

RUN <<EOF
    set -e
    /usr/bin/python3 -m venv /venv
    /venv/bin/pip install --upgrade pip
    # Install wheel to avoid the warning that setup.py is being used when
    # installing Ansible
    /venv/bin/pip install wheel
    /venv/bin/pip install ansible
    cat /ansible.64 | base64 -d | (cd /; tar zxf -)
EOF

ARG GLOBUS_ANSIBLE_OPTIONS

# Modifying this arg value on the build command line will cause RUN to reinstall
# Globus instead of using the previous, cached iteration (if it exists). Useful
# for speeding up re-runs to get newer Globus versions.
ARG CACHEBUST=1

RUN <<EOF
    (cd /ansible; /venv/bin/ansible-playbook playbook.yml ${GLOBUS_ANSIBLE_OPTIONS})
EOF

######################### STAGE 3 - Prepare GCS Image ##########################
LABEL maintainer="support@globus.org"

# This is the base64 compressed tar of entrypoint.sh
COPY <<EOF /entrypoint.64
H4sIAAAAAAAAA+1ZbXPbuBHO1+Ov2MieyJ6GlOSLk45bXye1dTnPxS9jO01v7joKREISThTIAqAU
Xa//vbsASJGSnJeJ005njA+WBCz2DbvPLmAujVrmmZAm0pNHX2d0cbw4PKTP3ovDbv2Tvj7vPu8+
6j17cfji2+fdbw+ePer2nnUPnz+C7lfSpzEKbZgCePQr05lkqbmL7mPr/6dj53FnKGRnyPQkCHbu
dwQ78Pbl9cXZxasjeM0KGU+EHMOrkxtYCDPJCgN6qQ2fJSA08Pc5V2LGpWFpBG80B2ZgmRUKsoUE
JfQ0Qn4n2SxnRgxTbnlYZofRs+ig94d71z4gA24nHHKm2IwbrjQsOEjOEzAZpNYiaMss4aC5KfI2
MEXUWiOFkDAXDLicC5VJsgu5zZkSDJXXaAvyh91Xry//+uZmcPL6rH9xOzg7hWP4c5wKpB6I5LtN
ipv+yXX/tkaleay4sZSn/avXlz+dE9mP/Z+IhsvEpvYg4XmaLUmJwZQvLfXF5Wkf2d2+uRq8vH51
g+RZbgSFOFox1jDKVNO2Pf4+gjAUeciSRHGt92vq3Zz+OOhf/O3s+vKCFKhzS/icp1lOwhveCMQI
fobwN2hteKEF/wjMhMsAcPB4kkHrXGhN0VPjUHkT2usM2hH03wtjcEfUclzwJ/SCkbhbrvPtF8p2
TD5RfvPEPltyc/sHZd53buzAzW3/CnpHmJFyJMYFBj7qDjZgKHRepdmw0DBcgiqkJBvqwfR1cvUi
UzOWpsun0B5b8WGcScljE2qu5lxBPZwXIk0hL/BPQgBTKt/WXnXkF3vTGEUyMJmUOY9CEAZizAGm
lpBmMYY5iRA4FcEP2QJDXj0FPLqYE2QgLCC7Raam5AimsgJ5kcQCYS4brWBQQqYSVBThZcLmuFFC
IXMl5iLlYwQV1MgwIZE58eOOyBLLJLUngAyRV64BkVPzdF5BjYNdVDye8Hhqz4g0wBhBetIT9TAT
BOKRSC3PGZsiL3ewOC3IIwwn8jxTBnXJU2aQyyyCc6LEUGMwsnsy3IHgjfrFaIDXzfsHmXgn1hRU
MwhHYAuRc0Vs0iCVEGo3aVTB15eR0RVWECoQK3QDRDf0ImrPnB2LCUcDGjhGOinOUANhgiYwHrc6
q4kQJ6Jfsei3ApuM6/j6Hew2dwfxZJYl8Lzb3VgJPhaPlK7wi83aMGzqsM7Mk60DuMeV3b9AKDl0
N7GkJmzE0DeJw4v/JlwclH2ATaZZJoXBMCwzh8Ifi1pRy4ivgBOkzc5OqQdlxTmTbMyVXbKuajeb
Fb/eLhsCmww2eV5enUGuMgICF/IIDNlCU9tCGcSSmZCUXj7VfDXeRBbqKzAz8ZMV2Bgp8RvJRnBQ
JV8MYhaTHFqwXVGNW2FnScStYlKPeOVTn/slvvD3PC4Menoc68HMmRXpLJ5yY08EWwlGyx3E7M46
DaCmKBjZDfmEpaMIzgw5oqBuh+AkzmazQorYGTXkZsE5GpdjqvHOxJg8sUJIz5pbqauz8oiXzBA2
lDC2vmHtQB0WfAjULI4nBCwYoZS/ROeUtey8CcIgoIwi17Upjjrxp4RCs2zeoNsjNXKRWIjYtyeF
uDaERChMzgwhnQjGYm4VPSeoRZ3KE4iIu7To5jTAzctZKuS0splkZakzV/KFrRDkFI0aIDd3pHW/
kE3aEDqPhHeR0zUKgtkU9do4EgQbKlvOQUfeTxtEHkPXpjv2OLceMkWLTw2rhA8juOEIwKkYegBO
/Gdzv0f4PYsmcQId7AE7Dvk6eoIx3EEl/2RXUTaFN4RFecbhuPoWNnYS7I8prjIlPfY5mKR6Shny
DD4+fgm+CcNcYSPK8FhyMWB5/vENCeMIUp/AvtyAuibHqOv7o+0+31QJo3CDFCeDfTqJtwzjvazU
ZcBiTRN4PFqMsbvGiCpsVI6K1BfWANeR6md4bIvqFuZYG5LMOlKnnOfQjQ5xQvKgRjdAuuN3GLZb
ObwLbLu1wGaCyTGnKxqexETkrouoMq1sBVyw2zCnlkcYStJPiinLp1ZZO9j+bvWtb6vR4kLjDEWN
k3pQL4U7cMqHgsnOm2EhTeGaaWmwB7Exa3NqsVjgyRt2VH75gFCeau4ZX/METe2cYJm+vOl8z5NM
sa38nVpH3id38/aFeL1cvcQioA0j5L+jYFUUVLJcwSqrlF7KuOxw16pQCV7UJ2gL7rZd1Jz63myM
nGbU8I6xPiBiapPQBd7FIpWnQhfUe+MZI1QbAu+y6hAKamrOMmrMXDlChihCIgFLnlJBa1tRZQuL
yytp9qLfTigSFK3oNnaMn4kfW9svVvoJnjRCv5q3SbD7ONg4h5fu7Cx4bz2GOkE7+MLY9IVWs5Ft
zCmD3Hbqg2nnOlucB3rWMnYVjSDcOK4izcsuPyPCm08NZEtjzXHwwk3cyaeiY1LdibkyumOvQ5NM
myhWBu2jDZWNToJjDX/EK1GBZdLeYnBTSg8rE9tbKVfwq26/3GstRcygTsbVzlDrNBzTDUZ57TBv
nJiVM9Bleo3bymfuFLd6yi65v9ZLlJINeN31W+6EVLt3BaYl/bvN1FYi+f72antSuzVETIrb9sei
32QFMrRGELxuDX6Cm7CEmzHyH5mcbhvByi9+X7nok8ZfUm7KL7GLAU8VEaaUSyfNpaScL33mYG+b
FOvsbYXsLuK7S5ojXS9nd/F5F3yNy49tRymF40IpjH2ESZmVV2lb4C/PTk/WX0Wj+7/9jDCiLNgL
PfAlYcBSbHT39oN/WfdNCfNDvMH28IKLt+F5R9IbycF3T3rBv2sM7CtCyaPavUP7QrhgsxJMdg/w
99XZaeCAY00sLq8ApXZ13cAMd4VF5nRJpdeHQtKDcYxf02WrIlN4vcUusVfHAT/XJfX1pLAPZAN6
8znu1sxJOZNFXhni5N14cvtEFEX+ntxk4mQZxXI09LZ/fV7/3f/72W1QbSL6Qa3QoALbnbLWh8GT
J9v392rO20YAIf8n9O725y1XeENlZu2mC3skdF2L/ZWbXZCQsRtUQUU0EkpjBcVi6vWk4VL6qPrt
k7Ycn+SKIV67psE3RL+3t7sSs79Pq84y6pzJKjzaumFYPSmAWm53TcNuTSPJ19xU5zBhuozBVhll
LtTvMU9d6rzlqIy7Epf3gLIQGH/Pt60Y3rvzlBse3bsetVS49q+49hXJZwtUKfGB5y1PS9lnk6Lc
a1OlMWOTxc602/DDm6vq+9kFJtHqKKpH0NrdBxHVvZLRsZR1Y7eRqTYZuqtC0UAwaNU7thbsVnUb
fv99a8avba/FSGszaj+bx6qHX+PW6E238V2DhKb5W7GgPCF72GUbaDHLltIKTG1m/K//X/kwHsbD
eBgP42E8jIfxML5s/Aebis1+ACgAAA==
EOF

RUN <<EOF
    cat /entrypoint.64 | base64 -d | tar zxf - > /entrypoint.sh
EOF

# These are the default ports in use by GCSv5.4. Currently, they can not be changed.
#   443 : HTTPD service for GCS Manager API and HTTPS access to collections
#  50000-51000 : Default port range for incoming data transfer tasks
EXPOSE 443/tcp 50000-51000/tcp

# Default command unless overridden with 'docker run --entrypoint'
ENTRYPOINT ["/entrypoint.sh"]
# Default options to ENTRYPOINT unless overridden with 'docker run arg1...'
CMD []
