# syntax=docker/dockerfile:1.3-labs

######################## STAGE 0 - Build the base image ####################### 

ARG BOOTSTRAP_IMAGE=rockylinux/rockylinux:9-ubi
ARG YUM_OPTIONS='-c /yum/springdale.repo --releasever 9'
ARG RELEASE_PKG=springdale-release

################################################################################
# We build the target image in 2 phases:
#
# - The first stage will create a root of the target distro using the base
#   image's commands. This results in a root that contains the yum/rpm commands
#   of the target distro but with a rpm database in the format used by the base
#   distro.
# - The second stage will copy the root to / to create the final image.
#
# We'll want to do this twice if the BOOTSTRAP_IMAGE is a different major number
# than the target image because the yum/rpm database format changes between
# releases so we'll want the final image to have been built by that distro's
# tools.
################################################################################

# Stage 1: Install the target distro into /$ROOT
FROM ${BOOTSTRAP_IMAGE} as stage_build_root

ARG RELEASE_PKGS
ARG YUM_OPTIONS

ARG ROOT=/ROOT

# This is the base64 of partials/yum/
COPY <<EOF /yum.64
H4sIAAAAAAAAA+276c7ryJUt6N98igNUoXAv2GnOpFhAosBZHMR5LjQuOIviPIjT07fOSTszneXy
BNvVjc4N6BOhoCK4FbFjrbVjf+e7g37zDzb4YxRBfHv/2C/fv10jBIwRKAqjOPUbGIExkvzNF+If
/WBf7b2syfzly2/mYVj/1H1/rv3/o3Z+5t82H99JpvSdKkTf2UPWnH/nMb5OMInj/938kxSJ/QbB
KYLCSBhDP/chGPJ5+wL/nZ/jj9r/z+f/X74813Vc/h2C5q8z39b9+/jtMFdQU5wLBAA/teftb39x
y/hOf/jWf11B392A774aK0iy/sWUzC+mx2oy9+VzxxdWMzj1WzMAdJassxIzlFfECgxHng6SXDtZ
YnuX+DkEYYlzkgaa0eCrKNZ3a1tbhWrb07YdpNCnEYAOek3ZZzk839Da8o00RnefyuvCrB5dSzsx
fyKL2srYyj8PUoqxYxfhMke2gI3HTm8Anq7sxusittCGtctCK77FY6DV2bCIKz8qQjRq3vMtV666
r3h1KPN9a4JFsmq2UQ6VB94YZLcaLkcMZqx0/ebYss1oRDiZHYlecKVm/JUa02trpdXBGCesDnNy
Sg9+axztOSLwVvneRNesb1VVKl/wm/SbSXba2nnbzPVq1edAP4qhz8HuIYuG65LTiB/nG6T5Fya/
YkDmyJkNbQ876tsFT9G4DmJMPg8K1n3iDcKhd/GPMH9ZhHMjaDtS1PpV71354KgqtpgSMJrcyOpM
v4oecnceWtpnzfHLcmd1obiRwf4mmo4fuLmmJKWNjDbwcDSs4QFRGr9ddYC/xXIOCiwvdwv1rpxd
MnznOOMFxyZUZkox4uz1VO9iW91Zu6Ah1Q1Mb+6XUj0kpeIAfsCilMQgOXK30lXG1S+f1qohzFNg
ChGRwfTtD4rdscIZqTzN5h5+WDpG+3OsXrWBAU9elvoKKlTSTMynl09kOG1dv8ToE1T99BxeeOYO
aKVyLBoylIHeNWt5S/n7fkWq/ioBy6ZfcP567e68bNJ2lcKVPU2EplBsi0pKyjNtm1ZzusbDCVFR
Z+yRk0J2p3fGZiyGBVZed+LgaKNQb2XBf8do+44D/0wCopf5Y0y7+Py0wVnvv/K7f8Yee6aoPhfB
p633cUDr6DO+SIVpcEHYBZnhq0C27N3L7H1yeth/kKBOZf6MoEsa2knEeFzEPSG9klN+9zSAs6o7
U0U+VzUyt8uCWMk8Y8nF5xVWDKNyNvPTlzWx+wSc89gGAxH5/GTSN4B05CFc/HOhxKqPC0u/tFjg
NvQFVpXoKGFxtbpvxISMyLd3xyY9eu6lavG3Byi/ujkAGhqinnRN4OvNdiBbp1R9oARO6tVwCnnz
Yll3QaR9QIKrXZkh4VWvDCcLHxQ84UxoAqDQ9APhqkbFQEKhuDZuuvlhvbzXk69D4fV6yAWbXUeK
PNOks0LwpbmyhTx4BY8HJDKBq/Wm+R7gGB5yaIpAQeokZzvdgobOmiVLCAWsMHFy26oOhus84fdx
VrL9SsnavdSwAXzKiY4iHLGn7r4Hr6rF5vUkIPhUA24/qMSa2nsy09JrPDqWZwy4uYy2Wt0dgoTJ
3W1A7aNYqytaDGDzuW+x4tXVDGfbAoWh66YUdUE1lJf3Zn75rhsVvX6GQ2Wu7uqcx5QlAImUqVnC
LORgOo6Zwc2zQ9Z24OVsxhB3DvUNmrvKTSVoKNTzIfhMMk6XuyIT7VLXyQLWvnH+cVuoINjCdEFz
MvZmZm7a6nUf7laWH4qaP992x2M48w4DTgvA6n6blSAe33qLAWCwmHGIm9tL5avHTkaPzKeuZxCS
GewUm7peKxWYWDio/Nt8qoj5kBRrsqhlLCqJBQmAj7dFcfCbPMIOTlhl97qhdRomHKvcXT0WbvEC
zrn7smjeIabtshlk+bxyNoUoQ4sEQOmKoMT9+CzSDqwyAl6upSK9FT3d23P//nvge6Y2fwcygs7/
KYj5WyGM/ssgzC/mpR76f/8yF0v52w9sNkUxFvNvNwTghq4r+vXfv6i//xQAjkX8AJ5C2M3yATxe
hLRrWTrqPZ8+Cfqf8NUwsmlPzs/u+3bQbHMjMI013ndfiIOlK4AmVUSstCSqpqqSU6W3T4QBQhyy
7g4FXrLuM14LSbnqdHBie2wEC72wNsrS6hMSFJgD2XDDsLZh9epCNtIyKLNj8gg6KNIi7wes0Get
BDmIv8DNrvFnGryfJL55q5tTs7k3NwA+sQofVCRyYd2Gww6yPIPegq5xXL9sLfK8offnXfZmCUQ2
q3eMOUg42EDayZMx/T0AKflyGZvr0sRcajD0rZ5Nl940J9JN2z0D9UhxpheR070Lv4XQpeJhe+FK
QQyBL4YjDZiIETTpgF5E2KivoRjSB3SpvOAoNnV7gpHF6LRsqOJLg96QdM0NMggVe3IMGxoheCeA
Z/nO5onwsDTN1BMviDWq+j4+plHQNqzUIbS91XHT34UnkUS6SwShfx956PZG50e3d4BMR67weBfC
2vknHPvYMHqffYADsdjbX93GKGteKmfhB5D/OLH7jslPWKxfNDIbJIL5ANVTaFX5rVKHKPGKThdn
wjaRSsZ49Lmi+xU7LrDNzAYbLYpt9lt5b7WayMqXn1NbdADWUwppg4/e26lAc0DB+cOvm8J5tSyv
OvBt3fLJqNY6OvHzuUZ4/bI4mu04gb7TlXF4gKijNFVrdcccMyz4i8DTZGnSnzngJVkLllJ5H8w2
TN1nDbXbTQFNBBKpdUCt3wHe5dHONwBzWDHt7Tbr2TP5Cn6ivsW9jUWh8gHCeMsDoolCe0xRvNIc
9keQBGRpbQuHOR+8fH4Q8vzakHY5k3X0K8Ha5YOcSMERW9Zl4L5IKss+WI5hYNZS6sKLNUCsBUHO
ljZ5i9vhHe/YaZWMQ7jU9XQFgTlpf3D36oM/lsBze3Nnnp7MHBHDVHL9cUEFOJvdNU9ZdQvuw8Ai
eIjGKXQpjNM2SAhKLbRfsJ1uBTBxtVYhuAiWHDfFD/19biDDA3I4VpvmPFbXhsuRlnxs++yXlhws
xZOfVsogDjWoQWyN8uTrT4BkW/+8zdDAZZuMvzWguTVyp1fLAXIvMJ/VwhpgbBMP1uVrhHUtsSmF
FUNLBmV2oooySWgfFEIt+oN5WKJwB0zQCIhnxN/xJtPS1TtHMxTTLPTSpCRf3qushZFotdc0vS/m
5E2tba7HTNh+QvcYNMuATRrW547B9C/Ojh8VrzEa66FuJoaab4Lkkwlu04OiMnCCZuNcTDDKPzxE
YnK43ISNAbqyYPCIzE24e9hvmhQERkEmRxUD792SKtm/pxNU3KNZx/0mQjLLXDjeJwjlljD6UO6A
xHnB+YB7YnsbRKOCUdM0ew5uOBa3E9/vEpU0fKPt1Ys0YEs/UFdq8mrFQI5M7jrhAI9ahMf6w3zT
Wqc1Ay5ggqnRGbtckYNGLmGDVkLGJ/o6kJH/xIPnm+WyB6JeFoQM4jXAPe6mLS6xHh1WLzOoOa/V
ikaP/cJ8WZJJ3oViglSGaccLo0wU17WckGP0dYEqnpoCgMecODQzard4EnNHXngp+fTsijFxBS49
dOqARlDa5TgKFB1kouc2l1JYvt45VvDvGwTUYCSnpnpH3M8OsNfnwSEw2ckaBRMjaNglcTFu/DjZ
WwQbmy1fRKI2LC/GD9TSSeYrIJqXXP4lgPgH+u+X+t8Z57qv8qQt/n4a80/rfwQhSeIX+h9HUPRX
/f/PsH/58tOMf6G+/NuX2+/40ocuLT+2/PbrVVasQ//bIn9DebImP2uFKOi4kf+HxKFh+YPF9NMt
fyWVkvq3KX3Z0N/Cv0XwL/9L0j1I+8rZ/ve3hIHGCtez6b4mDHgETNam15/Iu0xhK9bVlnw/eqNn
NDRtbhvpd96HZeuuQipsmNtCCAydb7cCvyHKTkMIsvKCDCtXXBfTUCVPBZP4SdDDp9aWY1VsYHQX
HPI132+hEDX1Rx4D+/H2TnWbBqYh4X3iSG+D3OY++kZk0sF91dMzbTHzfSvR9ZryWUDhe2dVwuW/
3PMu7ACGBQUTBu3zwz3lR6ZARd7A0NOCozei2xheQTaEJFd54e/zgKd1dvktcajpCInY8aIYWO+X
c1Ne4njZdxljQFDZyDN85FfR9ATuRkMK8oU62Eu+ljKszqexgTS6Zjt+PjCCU4Ec/yiG24oRG0Hu
ix0+dz8OhKjH2FJe8o/QF/EwvN/6A2YRValr8h0NSF2fsofAmQtWQMSZvny5IAuJE9O164H5SnWj
lpi0fHHEBnGVjfaN4LrFbtg+eX3B6ertJsTMUUPNdAKNqE24XgZjj+Z+HNmtkueBG8bgNCWRRSYy
fT+lg4AsV0aey5EZZzN3t32It3GNCtsC5LLhRbOa3C53JzHRCNfKcEzcDG1Z6IZVUNFJaywYbVkJ
YIixpIyGaMrxeg52YYowABvLVDC3NhmzfAwaEU8Y9rB17ryYEdw8qS6CXA+JVgXckzr4dvLpBeeE
nN5hbrzezRvY6vzFfkiKBYFGm78c8XV/cqJ2ER+0PROyeIxm4mSCOg2BHl1vfaMbvvKDUN8ZSU1t
HfBEX7H8R+VK7TsPq8qW2iu/K2PU+3AS0G+ZezqeAFdOQMBxkH+4lU18uNUYo8TzawIBiJ2mMu8s
kgTiZUnIM5eqd/bpIO30Npfot9b5Te6SCvOyviYUPvQXF5nmW+x8pUYS8OFEMvvhSMzhccz+CJgP
V/rKl0ScYbiqscQF4h+w1HBejaIHw6xDIZr2GH2U+0SC9hvo7ZCQON5qSb41Vv/Q/KzV40sa+/0m
HGudg4yhTXyYlX12ljAePVvh/sK7ermgmedkICFSOxj0l/lRPvfx4j4KRSZHfUaeEe0YAY2zQt5X
tCxJKhw+RfYq2+50vmYlaAGNowKwq0BVMj49H/TCZ2iF47DMNf2NNwJ3Ux+ZRZUwc0UrY4dlxwiP
qZou3QfhnVe6XLhHADXXJYF4t5Qz1H6BPFF1GCyYPPX54SPoMeCGPzUdmPoSdsG4ajOyF8ixrN7s
uzCSewNkbbvckjJy3qXSdV6RXakA7Z9dpHo4AjZJbWbZh2tgwsOwU6zfg4GwGAaXIcsUZ3HgACu2
0kTTjeNmUnlf8kMyK7NnRizrid1D3e5e7+wbSZNW/Lwo2N6ql3vPUuec+06gSA6AQg++vLEIdFIU
viYYGGSU28kv8edkL6DJJRK6nCtr+ZEwRpXUD57pBLKLJ6SurD0IBLtyNyY7miXJfcAx6VNy9WCa
qd4FgeuJgvfC6Dnt3nK+/SYtDDZwM7J/LqZ8xyzuRgKLBocQ8rxWk1g+20dfkE6EhZh8Vu3GjNui
9rBrZD63pZH+TCs0Lc18K7vVYT6xVz884DR3VKnKbNMKEVnrh0XVhFlWp9HDEQa18SvL2uieICZh
CoPLMWjrUS+tg9uukucnrgNbxMO8ZMeupAtK5PGxWNnn2cvG0Xy4UacO2V+YLPgZHv7Hf/xVWWz1
wW/VV1AK33YPa/Y47pt3J7VX88pgn0RTVlDlqBM/ocHDgZw5fqV/fgEGb4B7iO4YRrz4mCEqXzv6
w8KNbQkEy8K3943VGJIp38rd7aEYxgydeMI0nM9c2S9oIkQDYLo2i7HzlVzPROgjUfE8+qoXHRnP
W1HXu+zODp/CEL+/xD0daCtOpXSLn8jRd4oh5cDNIfirMSr2lWMgLINJ5YXx1ouFzZwBJd156jYv
mty9ILl+SjMMmbvLsQpuqRvZM3INTLZrP6dDeyCw3LWKWnRbp2S2V4OstjHIR2EPjSpTZ4/sIhi6
n4cTKaO9wdvpOWdr+IA7+8RC3nGIY0M+lHCLkbYg/khYrgTN6OqCc+VHqLye3aQe/dvfdOvuvMUT
C1Z6jkERMOksmrh3iM7NCpdan+LQ52clG/Nq/AeREb3A1IJTi7c8eh9TVM8MY4/DuzNnPqfungc0
7CYz4m0PbMUIirQQ4YnLfEQwp10fG/XO1y/qdtLvcsddCPloev3xWZcdQzRZTVu+AsCoy2vy8yPb
r9qokM+0j9NHNCGc6LumVq8rkRpXb/tlC3Lyebf0iwqCj0ss563eY0gB27yfg9jR0ORnlRYHpMlc
tviRHLiey/zmjw7V7JlgBKMvvli14gK5ZaWbpUIv9dHsLeA510eTUfakRdpVwK+cf75mbA5Hg7Hz
wVAdbSBDxPUWaha8JIlAMNnyMUnH34v6VUTcHzAkb6KPHpcFeo8DvLK/glCo7FnXXrHDPn7Q5gzx
e5Dy0LZPu/YNxCc7x2FTxR19ftBKcPlm/Ij76+ed/imwApjPmD+kv/dAtqweA1+PtZcVfOSt8/bC
iGBNNrgUl8rjomE3QEZOmd3Tfsh+P2rgg2KSaA0Kxywcy0YfZPuKatmPqEaD/hzM9P1I1b5iIMgZ
clQZVI89zPMuLhPw0PuDwfITKZ3z0ePHMkBTocTkPR9LhNrxiYfTltr44KVJD7EYB6bEEmS6+FgH
LUS9ARgeGauRYqAP03mpFmm1MOPaXkSQbM+WJMUBfd3eXvG21TXT0CmEX5d+Lh9F7VdP/UMNppdQ
cvK6xwqt6mcrIrnkOwWiZxrGhwujRW1AQ7qbly2mve9motyRYvKJQayrHGs7FBA0ZVwLb0RRjNNR
mHesj4B+nzvCGOuFejWJ0lJ11+gk5uOizEIGTFJE6jNdLEqW2UlATU6mZdSMTkrfILHODfr7M8kL
Gs6uHh72IXj4L7uctxBaoTDUtFG6c7sZ1I+k7szqBCqwmtNE/zxdhO+ZqbOTj15r9ni2CyiqmEyX
2yShmokR1sRnrWvz7uvxujoc1ZsGlQmgvyoNxzq0QybziY1Tf6vfz0YYg5WVFMy7qutib0HwdAca
HwcqvVHFMx6vru0/kb9XEDAIxXZfkgbXL50ItyX21uYjVPxAI0zcfMSlMt0hO2rSFAqE9B5n1ZBE
nCi7Ve69uLoF3lhKmeM071NflqCajnlsmkL5jG9zSkt3heKodOUKtwPJqQPZlz7n+Uzr0H6IRSs9
n4D8MB/CZELyoSA951RjwRD05uIpjEzSuTFMwFjQ9kASsGHG6AYvmpHsdcsvjyai5ngFgvvy8NZz
Ulx0adz8gKHzqXUz8hZIgqlg4Yf1L1iMKip74F8UL7IMDo0ExWcl28YA08VdLQkI6WX7KEBvWNuU
1YTaQ1oSUZQYxurzSLBuL3i9v4jjZjdW0Pnn7aMHotRre0DbYlq8Ct7RmJCqG2Sl2QJ7nK/Sv7el
Je5PrT7QdZUmZxn4aw3bmxHcs8vdQG61YWkExFB+L82t2XCzVxLnvn6ETf9ZlZiBe+fo9iTLlIUd
LbQy45o/PMzhI7a8LErm9A6GkAjAV08Od4Tinr2PmfqpfWj0UvnFhyvGxZjJJlU2aXCeMC1Nmk6S
cV3qaXWn81ha5RRngV1g/KNjaT6ywo3gBRVXbmisSaLZW8ML0eYPM7OMy3cDe5bnEnztcjVDUNhN
1y6x0AnMZ2JP2K3AnAfWz4xv52xO3k6ycayn6KefKbEYuJoba/e1Z4VNzd7YKnqEc1a2hr4JgHt1
G+oRLHiT6myV8SN7RMobzW/GtGColmE4bC5aJbb3aSNHVHgFZj/GQWbch0Ok0QZglDI9gsp5mJEt
jjjkvsJQWFKnwvL6hGVpfAeV1YDQYOgx5eKBtA+1OFKo/2H3ejYrANXhU1bHd8PFprgND2TiQSaI
xaFfwJ3UD/jgD9SNqmcTavLos8ItcWYtXXQ9hF1V1wH2fq9u+TRWLhZ5iIuYmxu+FbeT8Gadipsf
lRL5cGX3JcvPJUYRzTOwVxMGVDJz57AIAPtK7k4cB+CWVbMVbSeslAwrsAwjfQRKJEjMZ8vnmP92
ywd+uefz3040+Z/wYGrVD/nyS8klnvdOFEx16FJ74lPmgpLMA8L8RSwfnRa4tv281IMThg/bXu4q
GVcz5+hxDOqE6UIB4TSkZpGbvfQW5rrXGO3aYkCASdZvfnXzBC3eEtgybw/arpcciT2IaQqF84ac
m95hvRe7Upw6azt7nyaE1rBcezlaBbxLrh2kymDzkiuiCTZpH2Y+EsjY4EKQ0dgdtnTg7Psgnfyj
OhQNAWFykqUmTN/2LYyBzNuo1VCYiKv4+5F4HSHHGeSfeqBoydt709xIY1uAGDm/3h46uFFSWmYf
MZrCmSTZIGAYM8FE0hm4yXQ3oQImmkbDVubt64/zQ9/swWuyRvxwxAUS2Przi4C3u2sQ57vI4yR6
Air26DR0s9W2buNtKULlZahB61IMcnSb65d0S8a2QQjgSkIsjRv1QA/NrhqrKejSMQGSvo9PyGdC
HqqrYaD4/ProOb5tI5+176O8yN16LakCaU7QiXQSyQNuQYy/ioeEXlgCVHrcGSmc8Ga9UfkbdC+l
T5OVblNUaDOE3T906HFvzzI7zQ+UlAsoaU9TjyZeFv2RmYFRkPVieS/PD5fsWQZTH3KZVKN4FJ9d
gS8P1wzSDuz9cs2LQx8DjYrjpi0C1DRyuwtQIHy5idPDqQ6l6TU9EXIUTKGeVbVPwuNWOQIhR5M2
GRwd7XgdyWw0X6+NNZL2ePkufgOkea2z+4iELdMXF0uc3040kZ7B/yKR8nfM/33N//7sTHT+kJm/
Y+8/2J+p/4JJAv1l/RcB/5r//afYf/40+d+lyVIMy/8N9ElXfP/tDPzLt6zrl3+di7b4NG7F/OW7
L+znynCArp7nYW7rZf3+9+frP3y0/PKQ/ac7/yOZs+f3//p1oK9X//Z1uX3/Q3/f/WwQoBqr7Flk
zfcIUPRJ2hb55+rzYVOc35d1W3zGgv5o5SIA/NyhZByXdS6S7s/6xIyj8+3Ov59bP3b5d/LsHzP/
X8f6WZ7/fyT+KQz5ZfzjKPJr/P8z7D+XvP3DwP9Z/isb5uJbuP8iWn5c6b+Mlr/m0OhnXUI/dvj1
BOmH/eBn4fWHkfL78PkzQfOTG5894Scnv3uPnwcp/jtnvR9a/xH+/m7gP/D7d67+5P7fz+m/cP5/
2QNX9Kvh/H3X2J+t//5Z/T9CYt/qv/Ff4/+fYv/yxSmKHwvkss/sD8sfr//+Zdt/XTXfUX/bMS/y
W/y3xH855dVZ0egh+FuVnMafMchb9yZz77zlCHACs2gdMUK4j+a2kFSm4Gv3LKD6YZz+40kD0Q5t
rCzelqwjXWgzdaIcxkWtA9pbmKekVnAxcuRJFDmoM97dFRJydIx8oLhT5Pe1B/C7SCLCcqZ4dZku
adXODF9b7q5VxNrxixFM0X9jfD3AQ0x4VkyVVx6XRX08rJv/cC0AP/GD2OqGZsFs6qR6opmAQuqj
5SM/SJbKhmmsDGue1jUX591VBVVNivSXcise9lTGQLBQFcWBdCJI93KRYsg5NOPdHZBU1m47JC2c
99PN5ajQgpS3nrP09BrCyxbBMuG95QUE7013LGHywgDJL+XFbvMgbJX7EZ9KaY9yZcwZSpDTxj9G
xDmy50NsV7MdiC51HuobAQ5kxL2GuQ4Cx7ri0dqhUR0o9BFNHXknNVhcnJN3SBNF8VMEMbgoDJ7H
lTfOcqcFvwxAHr2j83pmHKAOLuyilUnXbqmXSibS5ESe/hTZt3g4plqpETuKT/+yHySmLFud3tA5
AnDsNmGLbHj5EUfkuD2MwG5yzx8uKmCFw80PQl+lEG/ygLDWzLo/QLR5ruTC9p9OMhZQoiySd8Yr
GGLL7XLX1Hfck07FeGpeFcb6LsHMtDFIIG9aPFM33GmHpr5rq9WUDX17AXrYkaXyCndl2+sHKtfi
Wd0SbxcEPiQ80DI4Bt6jufIs6Hmrk/W5sYrqZPTrx4S6oPBxQMAu8lj1k9W+5sZVQW/T3ja9k8Fk
ge7irn0lgbj87nR3TLusclCfUB3mBmSo/8pDZczvLROh/juX6OvHUvGX97uT3ZvItN/i5dvJ7u8P
dlnW4wCOefBiJbPME/+8CoZhBkXgXGlSS3hiSMTVYRNCKQx2n7fsAebIKBg61cMiEtXnMUmAde0j
h4rPGfXkJRxrqA3cUJZIprW3OXm9xOdO35s1erUiPjykD4lzehkOzbybdZRuNUAEiwJh9Pzc1mbH
u8cbPa298A+PUt/4wLgmuwX2BpIjZ5mu8SiIw5Tg2HyZkl4r8LEDuL6AJWGR0tTRKDXcw/FsPUvo
3nd14UYsV6EmTg7FCJduIpczQqp01l4o009wHQQmDrjTLXg0qze7WQZeFjqKNjVsQv1UYXt7dg0J
6TiIKzsj1a/yWbyOXQ9vLmly72ghlHoDnta2yLSYy3Lrmnj4FGNcp/u8F3YGZ+7UqrNLx2J3IdUm
z+neqD3fnlLtomab4RHNGEDS1gHSGI8lFqM5xOhmLu0G7VE93OrCUqB2x5Bb5Ug2Sb2zprnQuGhS
ThhfENz194AHMJv0qY4mbNKLple2g6BFcGuMrld3DF3sljgqS7LKpo7fyQ5FBBGYsZ7mHZiZxdGd
B+KJSVmYb/FHmgt38vMw8k1IdcjVWqSGKWoGaS20kc7oWw6TNB7GwLCMboXAWiWFYBQQOY86IGaI
OHaroQ4hU9s0zjtPGbGYdy02dGFyS7ZtxF5tM0132jKEm1/HMZmoljZtwKiBeLoQ6Ot6S7v7cKnK
sInHxYObC5e+Q4Xd7fEyji2u0vvCVNcpSq2MVJ/g6jyqfWPA29S1z0Zy4A4i4UpPAN8bUhT+RUmT
vw7KjLKsszppv/yvHz74cgP/999exISifwzerkdwNF/h7T4vzchWOm2Mz+5pNxllQtG8MJKzbS3V
lG+woFUm8ciSeBSMf/bALA8PHFvOU2oq8QyqV/y4QfN7poSHGaHnCqIThMSl5nN2T98IUplceYJD
e+S9Au9VC7ixLUPtvB8PDn94ceO8XfkUjpQv4Wzcb7SblST6OLr69npS+Ga35omY1SvQCJzGUywE
iPLg6/yOp5MZn4fLTubsie8BFErPF6ZaEmncHCcy9raZlQx/QHwElMuO5iRBJWgqA5Jiy6QMscW2
OuRKv+He+OZfpk1Dl9Pnu0KFSxhtMXkPM1VKKltdyogPJLNhiMzQoAIowdNIjZ7DsdP0trGqLFxN
dIUEnYcbG2rdPG5nVp/srk37/BpuYqtUzXbzy6SCUM+mAEXW03O63wfNe1roB9JCZ1fx6LXudS7S
gtckbBzMn7mJbEy2Yy1sg6kwaggsrsgI4A7Y3uXcZNvyBF219f3+vXeC+QHwbveccdHy0lQGhL8v
+U10YMzhVDMJxZynCrMUXnXUAP19tBJVgJEk8B3Nq8+qp0RqjopOmnzaX6mV3YnxgrfJ4Sg0IQTs
Ei9Zft8PMmH0+QSkZMWSycOmlQ2NmYFyswnpLBBAzyb2AWJQL1eVWGul5wMNbAVr105y8ZtPc4VD
6nQEdDin5tdWUULwat1WnHPoFiioOkyGQLcFbxahbfbZO1VKhdQ0+X5KMP2kG/VHeOPH38Pbz2CN
NeMuHiO0faYc6yZB/v72X1DC13rvrzVLehth/reCJsCSvn1py84fCr1rS8a+FnozFfNkLSW7xCVm
ngvPVovCMRn/7R+cGFnhquUbqgF/AGtMgPipIVS3OH8ZywfWzso57vRrKkvDox31VPh2TjS0kt/r
FGPsbWwB6YSsPqUtHhEUP8XjwxCeWYQGtK+U8tiX2Mm+mXWgrk0tIAnpjzvOrmTgKhbXeK9sAXRs
MoPlQPylXRjhotJQqu9nRzIfCiiit9Siw0geGtkKc9hFZx6DWl069NWwYzRVXzywGVd0bU+0zj05
QvhKChQEqda7KDM0t92z4LOmTeHZZGqsMAaBJKfITq7jjPUw+7s7AQmcfWhm1XGWIePQIwIbebuG
4igl6ng23lTA+9GNT9q2rKN1U93iuTw5nGpPRdQFqx1Iz4TfGgc/Vpt0hhfFqi+V6bK+JMoe5whj
hlXNmx4Xu/KPtLSs+tmTaB0rOhnHEJ5XwITf3en0x/N9PcJFHBVag8TpjvIKXhySNLIbDKcJFCfv
k5KWycgIs/9gZpTcubE94RDAYYq3DwJZ6WiPZGhd/aR9F8+JBitbGQ3XVUeSecU9lBDRij3JF1+N
evmAhFMT5Yi+AJ/kwsmyoJtib0ndQMoiceWHeGixsePNIL9iSWAqGK/fp+6+ngdcQNZd8LOImXTt
GUrAzLluyvWY7ngGPR1CyIEqhHRIk4QDJzGwF7S+FCOKU5dp+jjgDzeC0nkUYtOLOhBDgeEWlumQ
sUH7Ej0FJJP25W4xplma6jpmQLmiAUrhmTFGx0nPNnyia5uRtZvhiMlw0wmcJ9jdO2cDvm+aO/VX
F3P/DfZV//8Ah9/R/5js31+Q/8PJX+h/lPq1/vufY//5u8n/gxTg7yjPD+nr/yb7X6wfQts3/yVJ
/jNu9ft7/uNbPvwPBvruX39IzP/bLzLn4zysQza0P3T7f339++dyXj887M+TZF+H+z9/NNEO/N7d
X54M/CmPf3Y28Lc6/eNw/0N+/0+vsl/tV/vVfrVf7Vf71X61X+1X+9X+32D/D+bQtPEAUAAA
EOF

RUN <<EOF
    set -e

    # Yum repo definitions
    cat /yum.64 | base64 -d | (cd /; tar zxf -)
    mkdir -p ${ROOT}/var/lib/rpm
    rpm --root ${ROOT} --initdb

    # Create these /dev/ entries to avoid 3rd party postinstall warnings
    DEV_LIST="null urandom"

    # Create /dev/ in ROOT
    if [ ! -d ${ROOT}/dev ]; then
        mkdir ${ROOT}/dev
        chmod 755 ${ROOT}/dev
    fi

    # Create the /dev/ entries we need
    for dev in ${DEV_LIST}; do
        if [ ! -c ${ROOT}/dev/${dev} ]; then
            mknod ${ROOT}/dev/${dev} c `stat /dev/${dev} --format="%t %T"`
            chmod 666 ${ROOT}/dev/${dev}
            declare ${dev}_CREATED=1
        fi
    done

    yum -y ${YUM_OPTIONS} --installroot ${ROOT} install ${RELEASE_PKGS} yum

    # Delete any /dev/ entries we create above since they may have incorrect
    # major/minor device numbers for the target distro (they'll have the major/minor
    # device numbers of the bootstrap distro).
    for dev in ${DEV_LIST}; do
        varname=${dev}_CREATED
        if [ "${!varname}" = "1" ]; then
            rm -f /dev/${dev}
        fi
    done
EOF

# Stage 2: Copy /$ROOT from stage 1 to /
FROM scratch as base_image

ARG ROOT=/ROOT
COPY --from=stage_build_root ${ROOT} /

############## STAGE 1 - Prepare the image for GCS installation ################
FROM base_image

RUN <<EOF
    yum install -y coreutils gzip python3 sudo tar util-linux
EOF

##################### STAGE 2 - Install GCS using Ansible ######################
# This is the base64 compressed tar of the ansible repo directory
COPY <<EOF /ansible.64
H4sIAAAAAAAAA+0ca3PbNjKf9StwcjtyciX1pN2qku/cxEk858Yey+lcx5dTIBKSUFMES5B22KT/
/XYBUm9akmMr7oWbiU0SwAL7wL5AmnqS91xWfvKAUAHYtyz1G2D+t7quWpWqtVevNOrQr1qt7tef
EOshF5VCJEMaEPIkECK8rd+q9r8o0ET+gXCZfCAtWEv+jX1rv75XqdcaIP9avV7J5b8NmJX/wBW9
SBq28Dxmh4ZkwTULPlsrNpf/nmXt5fLfBqwjf4f1aeSGdzYPa9r/eqNWs2p7tSeVWqVu5fZ/K7CR
/EeUe2Y8cjecAwW812hky39vb3b/10ABYP9XHoTiOfjK5b9DgH5QgE+Rl1yETIbcG3zyA2boR4WB
LbsB80Uz6Vz40qvO4b5gnf0fUnn1ObHh2vbf2rcqexj/7+9Xarn93wasL3+OBsJ1uw7rcbqRG1hh
/xtg+1H+lf1qwwIXAPa/Xt+v5fZ/G7CzMRR2CMLxm87F4cnJ4cXx6Rvy8vScvO1FXhiVXyj1KNwB
bwFRH2p9JH1qh5KIPuFeyAJwSU3VTBJ97QrZ7dMRd+MmSWecNDpchgHvRSEXXndEfxNBF/RYwl2T
VCvkE6lW8cf38KOGt7Va5uiAuYxK1iSwL2Ah0LkXua5kMcNL6MFtuOgLm7rw+zc6GsXw+4p7LOR2
FtZ0zdBTcw1oKxjEoyOY6FjvMxIOGXn1vEPQ8UoeiiAmEIhxjyMGWSCkx2yBA2KGd9QHFqFgYH82
yTAMfdkslx1x47mCOtLUW9sUwSBjl3/8SJST73Kvzz8weZl6/Xfkzz/T3Q9cLOMziAl7KR41yKUY
N3ShiwlNaiEwIITlQRwhmRdOCDzyMIbQ9CkM5LleCemolRBYSTo3TD1hAGeLZEOjS22mSfdpOGyS
MgvtMrCjLEUU2EyaLrDedJaTbcxOhre36QF0UejUdAEbsA9+k5T+u/Mf+QzIJqXkuV4TKaXPbobM
00s0JrP9rU2KOp4qLmuaxF/FCe9ecLmCeXrIlNbcP8v0FHdkVQandsjavFpfkSYsvI0ftvDjdOuA
ndmQGZM5NmIIYAlhVzTJJ3Wrti25lHzgMcfoxe1yJIOyHNKATW+z8quzV8a/jn41NL3mwB98t1ZP
o1apNbD7u7Fp6EXcnbULGxgLTTFaAbKaakUsPM8SbjtL2zcRsB+IDxvIFv6bsKw+yhXWkY5eIphD
+/eIB6zZRMY1m6pns7nAPdBPYV9JawisTWyK6gr0F39cl/JJsx7Lpbb5zJkw5a3vgF1VTDk8uyA2
tYcs2xtEqndX9dKNyx3NMvZmY9UIlqqG1Vhm/L90mJNDBmwe/8tIss2KQCvif6u6V52r/9Sref1n
O3Dn+H8xATg9O3rTeds5Ii+Ozo9/gee/HHXM+08EyG6is8TFqHso4JExSn2QiYY55J4pWRj5T7Oz
hg6o8do5g7UqPyg2SSOzT4KniIjMzG5NInzmKQaeMOpjSrBDjke+CEJtok9Of3rbIVcsJhBKudzm
oRujgaZAiXYHCV/+iH0fnONIOBHcOYJJrxQSGoXC4AofIAY0EgfF5IbG6Ygb7rqZecj52c/TuQiu
Y/eEDagdP10MMf1RFzpoZ4EXd0lIkhhjKvPARc8FNtl507L1YhT0JVerwrDPTvW0tKY98YOne8Ci
6ejS0Ome6Qka2EMTWpc5/Vti+XtKbpZlhAuGYMhcVy/CHjlNUpxsD96P1YoMw0mmTsSUTGvoaQ3L
6IwDtHtL5VYGt0kh/gGoZd6txF7oiTOpxag1nPS5J3LTA4jt0/vWk7eLFwmOvHsX8LL0dBnNS5MY
pFPtTZmZmlpTyamJXZcnOJdZfDmD0Vrx3yVdkbD2cmIsAt2J7p707oFjjAK3fZ8ZJxoijEDLWWln
4mzRiH2DC0ADVU4W1KfcFdBhxMKhcNp+wIHhYZy0ai1x2tXkPm1u//B98gTyZ0ij7KtxF3gAVr7d
5y4D+pRc/CuOizSgqQwuyJhzV5umwKmLWC9BW/QMG+RoyIFrHghvhOqhery+uDjrdM/OT//9K2yt
jx9LmTluifA+2V2WuT4lzIUApVTCTLiQZ4KPC9bP/+54+P9k9fk/nvnM5n/VulXN879twIKdgTDU
p/YVHSiDck0DqU1BF9o9hwYO/4OlSVRiBQk5Z85rCi4lYM6QhuPHHTCh3sChYB3nm/QBSJPo08TJ
iAjPWtDAwyPu2W7ksK7SPz2ZsrSkmNYiMIhdXNflQrqHMS3qbjE3P3Owef1HC/L+zn+reO6bvP/V
aFSsOtZ/GtV6vv+3AfdY/9FG4IGrP9kFnWT6T1NWZ936Dh4E/wD/G3gY3KhmV2gO3RE94V70Afo9
hyjptAMXL5kjAgoXpwG1XZa2j9dzDjFTPLeuudrO0dnRyTqVnTgabVLWge5lx+tn13XUvIuFkk0q
JK7ZV/RD2Pcb2AwVwftRr8x85s4EwDhX5hHZjEDAWM/FycvGqMRL835JvDym7paDP2DP0iLKrSTh
DyOp+iVlkLWp2qhesprmHXKk1MWFJIXwMeEQerNr5sGViAZDwkMMximRoh+Cu/WZ5zDPjonwZpmE
Qk6VDlBrvdJIqZobduEsDshVETUeo/FBFKhEFnwx9BqBfuKyhSRDes1wDUmFxTEXRIUaqnEYI+pB
4LGY18xJCkaAjxpBb2d3duTTVXzdSbdro/p3glNI2B3hEFFaavELK8mSxax0P4GBIi00Ho+lILl2
ge/B6pRZ+ysvUq4uYyHlcKVy5pkwXDWnpZuP32LavYF2km//HMfai/tu7ULoZHqV288iteaxShYK
P1yB0kzLL5Up5J4D5H077w3+CmXXLyW/9Uq79yq/BKc5Xz9bQ4CPupL8SEWYVqvvVYYp0rsK8bFV
x8H1mF9ncRy11uEB+sd1w9JHWiifgvXH6chlZrsCN/RuLumwXpeql4bXoMolHR+W0rI1c0uJBdj2
u2su9xjGPe7iq5p3VW9E2dTTtTNL+aonxFYsCGkfsm6g5fTluvRPmrPfYLv1TIPs6rBtMSqeCyc3
OtmYX3uq/LA8T4QbLzHh2GQL3XW1pE0WcG1MQbr6u9R/1qn/4V76nI+A1/z+R3//v4ff/+5btfz7
n63A2vK/+/HPyvOfat2aP/+p7u/n9d9twEx6jfZFG/Lxl55kHE03x1fwMAnam+lFgUz5s/wz0b8O
pPv//Ojwxc9H5sh5gDlW7P96rVqb//sfjb38/Hcr0OoFpHxQaPmEunzgtYs2w5OW4gHs6NawPv8U
q3/pYcSZS+OeEFet8rAOGMr+QaHQclgIuYNU77K2i/hTo5LRaESD+OBCBbyijyEVZlqyVU6bsJtw
D1SM03L5QYuSYcD67eIO7YkoNCCUNpKSfPHgEB+RC4iuz/SjVpketMowbDw+SSEmaIbixnCEwY1I
MgPr5EZfBDM1bllMRxHyWtwQR5Bjog9hIM6C3mSm9z/SKWBuPe3MAiYzuxwYKFnx4ERfLC520hdT
UIokPtcX031bZWRQq5xwGRi+s0MWWFG4wNUmrMLf1xxSYxIK4eLhEA2JjPzx2ZPDfFfE+M4PiuVy
acT7bjdNU29ubrLT0afAKyydJRpikmOYChFIQtURBGw1VVvzBVZDkJ/Mc/QNdUbcw1yMQp4vx+d9
zIFLdRgxongztVocDsQ5ka2PJyalOz8KIDdi0hzr6pUnbiBlHTB1FiJB5QAXrNXWGRr7QEe+q84C
IOgf4SvlLr9ibkw8Bh1DAcE9rJD6ob7r85DEIgqm35gyC4Vnz2B/XFtkCNRyPLe8wVOTPrc5qExs
JFwHFJczBytAhM2cCMid8NkR9uq837i2ZtTXGEQg6fLTZ89MonRgXCFXx4Uq1Uk+udN6oGaWUh18
6HOihGzVqr8dQsXR+j/BplI/xSuXDkif0RBWT5JTMXVeqxhhKv1cayMVqiZ5BUuwXeFpmag5YGrF
5xl+ecLRVZT379+rqp26+YYMxuNTLsKTYdQzIS9LGJjBR61VJnRP8RZq5jgJPIvDofDq6YkZKPGA
gWLHoJ0js1A3YZOEkQ/5uZQ3InBc5Gin81rzba4/PqSg0LYtIi/UfEZ1kRGwCJ7CWLPQMMl55JH3
iXM2/MTSEgPEfQ26JoK43dJ4uxrvwXfQCAwO2q2AjUTIunhzQNKhGLq/1/JIbFDhEEiD9V7pMzw/
DvhgqE3CW4+r9DKMlaUecpsOBGwmGKA6SYJpKXDO0RgTS1U401/8OTxA04GsSw3N7xFuTZA00v8+
efrPiX7D0r60J/w6IY3/0mq43R/c+xwr4r9qBWK+2fivXsvzv+3AZfrHnd7p927edI5/OjnqPj99
8/L4VVN7kSknh3VVrkI4Zf1DlpwKp59kJafygOlmCP5b+0pwLtrsc4wJXiQTYpsdBQFi1RYDrJqp
X415KQJw9024Gs/Xhks3YuRHNYf6gwJgyoQ9fjdhqL22DHfl08LETJrl8XWhoKocXSykttUl4jiM
0CRfC+6oN2fG1p4FAbgpLLuha+yDNZOkR+0rdAPqm+se98q+6px4BkBW0sa3lHoHcA0MyZhx6+O9
Bm4p3X+66FmGEBDYBmFJl/r4lgWYanzzDmIhSK/hJ5arbazMx+YwHLmF6Sa9ljbGSkjXC4GvB6l3
jkhJXnHA55SIepevAFjQMXSTx13knQQWA5UyT9u/Jkj1b7xJHmCOVfW/irU/b/+re/n3v1uBy/FH
tO8K1dq+WYF/1fGxYRImg4Vtq365afh/g3T/T+cJ9z3Hyv2/N1//q1sNK9//2wBDxU2yidkavnmI
UdH4mHFZrpybgBxyyCGHHHLIIYcccsghhxxyyCGHHHLIIYcccsghhxxyeLTwP8hgMs4AeAAA
EOF

RUN <<EOF
    set -e
    /usr/bin/python3 -m venv /venv
    /venv/bin/pip install --upgrade pip
    # Install wheel to avoid the warning that setup.py is being used when
    # installing Ansible
    /venv/bin/pip install wheel
    /venv/bin/pip install ansible
    cat /ansible.64 | base64 -d | (cd /; tar zxf -)
EOF

ARG GLOBUS_ANSIBLE_OPTIONS

# Modifying this arg value on the build command line will cause RUN to reinstall
# Globus instead of using the previous, cached iteration (if it exists). Useful
# for speeding up re-runs to get newer Globus versions.
ARG CACHEBUST=1

RUN <<EOF
    (cd /ansible; /venv/bin/ansible-playbook playbook.yml ${GLOBUS_ANSIBLE_OPTIONS})
EOF

######################### STAGE 3 - Prepare GCS Image ##########################
LABEL maintainer="support@globus.org"

# This is the base64 compressed tar of entrypoint.sh
COPY <<EOF /entrypoint.64
H4sIAAAAAAAAA+1ZbXPbuBHO1+Ov2MieyJ6GlOSLk45bXye1dTnPxS9jO01v7joKREISThTIAqAU
Xa//vbsASJGSnJeJ005njA+WBCz2DbvPLmAujVrmmZAm0pNHX2d0cbw4PKTP3ovDbv2Tvj7vPu8+
6j17cfji2+fdbw+ePer2nnUPnz+C7lfSpzEKbZgCePQr05lkqbmL7mPr/6dj53FnKGRnyPQkCHbu
dwQ78Pbl9cXZxasjeM0KGU+EHMOrkxtYCDPJCgN6qQ2fJSA08Pc5V2LGpWFpBG80B2ZgmRUKsoUE
JfQ0Qn4n2SxnRgxTbnlYZofRs+ig94d71z4gA24nHHKm2IwbrjQsOEjOEzAZpNYiaMss4aC5KfI2
MEXUWiOFkDAXDLicC5VJsgu5zZkSDJXXaAvyh91Xry//+uZmcPL6rH9xOzg7hWP4c5wKpB6I5LtN
ipv+yXX/tkaleay4sZSn/avXlz+dE9mP/Z+IhsvEpvYg4XmaLUmJwZQvLfXF5Wkf2d2+uRq8vH51
g+RZbgSFOFox1jDKVNO2Pf4+gjAUeciSRHGt92vq3Zz+OOhf/O3s+vKCFKhzS/icp1lOwhveCMQI
fobwN2hteKEF/wjMhMsAcPB4kkHrXGhN0VPjUHkT2usM2hH03wtjcEfUclzwJ/SCkbhbrvPtF8p2
TD5RfvPEPltyc/sHZd53buzAzW3/CnpHmJFyJMYFBj7qDjZgKHRepdmw0DBcgiqkJBvqwfR1cvUi
UzOWpsun0B5b8WGcScljE2qu5lxBPZwXIk0hL/BPQgBTKt/WXnXkF3vTGEUyMJmUOY9CEAZizAGm
lpBmMYY5iRA4FcEP2QJDXj0FPLqYE2QgLCC7Raam5AimsgJ5kcQCYS4brWBQQqYSVBThZcLmuFFC
IXMl5iLlYwQV1MgwIZE58eOOyBLLJLUngAyRV64BkVPzdF5BjYNdVDye8Hhqz4g0wBhBetIT9TAT
BOKRSC3PGZsiL3ewOC3IIwwn8jxTBnXJU2aQyyyCc6LEUGMwsnsy3IHgjfrFaIDXzfsHmXgn1hRU
MwhHYAuRc0Vs0iCVEGo3aVTB15eR0RVWECoQK3QDRDf0ImrPnB2LCUcDGjhGOinOUANhgiYwHrc6
q4kQJ6Jfsei3ApuM6/j6Hew2dwfxZJYl8Lzb3VgJPhaPlK7wi83aMGzqsM7Mk60DuMeV3b9AKDl0
N7GkJmzE0DeJw4v/JlwclH2ATaZZJoXBMCwzh8Ifi1pRy4ivgBOkzc5OqQdlxTmTbMyVXbKuajeb
Fb/eLhsCmww2eV5enUGuMgICF/IIDNlCU9tCGcSSmZCUXj7VfDXeRBbqKzAz8ZMV2Bgp8RvJRnBQ
JV8MYhaTHFqwXVGNW2FnScStYlKPeOVTn/slvvD3PC4Menoc68HMmRXpLJ5yY08EWwlGyx3E7M46
DaCmKBjZDfmEpaMIzgw5oqBuh+AkzmazQorYGTXkZsE5GpdjqvHOxJg8sUJIz5pbqauz8oiXzBA2
lDC2vmHtQB0WfAjULI4nBCwYoZS/ROeUtey8CcIgoIwi17Upjjrxp4RCs2zeoNsjNXKRWIjYtyeF
uDaERChMzgwhnQjGYm4VPSeoRZ3KE4iIu7To5jTAzctZKuS0splkZakzV/KFrRDkFI0aIDd3pHW/
kE3aEDqPhHeR0zUKgtkU9do4EgQbKlvOQUfeTxtEHkPXpjv2OLceMkWLTw2rhA8juOEIwKkYegBO
/Gdzv0f4PYsmcQId7AE7Dvk6eoIx3EEl/2RXUTaFN4RFecbhuPoWNnYS7I8prjIlPfY5mKR6Shny
DD4+fgm+CcNcYSPK8FhyMWB5/vENCeMIUp/AvtyAuibHqOv7o+0+31QJo3CDFCeDfTqJtwzjvazU
ZcBiTRN4PFqMsbvGiCpsVI6K1BfWANeR6md4bIvqFuZYG5LMOlKnnOfQjQ5xQvKgRjdAuuN3GLZb
ObwLbLu1wGaCyTGnKxqexETkrouoMq1sBVyw2zCnlkcYStJPiinLp1ZZO9j+bvWtb6vR4kLjDEWN
k3pQL4U7cMqHgsnOm2EhTeGaaWmwB7Exa3NqsVjgyRt2VH75gFCeau4ZX/METe2cYJm+vOl8z5NM
sa38nVpH3id38/aFeL1cvcQioA0j5L+jYFUUVLJcwSqrlF7KuOxw16pQCV7UJ2gL7rZd1Jz63myM
nGbU8I6xPiBiapPQBd7FIpWnQhfUe+MZI1QbAu+y6hAKamrOMmrMXDlChihCIgFLnlJBa1tRZQuL
yytp9qLfTigSFK3oNnaMn4kfW9svVvoJnjRCv5q3SbD7ONg4h5fu7Cx4bz2GOkE7+MLY9IVWs5Ft
zCmD3Hbqg2nnOlucB3rWMnYVjSDcOK4izcsuPyPCm08NZEtjzXHwwk3cyaeiY1LdibkyumOvQ5NM
myhWBu2jDZWNToJjDX/EK1GBZdLeYnBTSg8rE9tbKVfwq26/3GstRcygTsbVzlDrNBzTDUZ57TBv
nJiVM9Bleo3bymfuFLd6yi65v9ZLlJINeN31W+6EVLt3BaYl/bvN1FYi+f72antSuzVETIrb9sei
32QFMrRGELxuDX6Cm7CEmzHyH5mcbhvByi9+X7nok8ZfUm7KL7GLAU8VEaaUSyfNpaScL33mYG+b
FOvsbYXsLuK7S5ojXS9nd/F5F3yNy49tRymF40IpjH2ESZmVV2lb4C/PTk/WX0Wj+7/9jDCiLNgL
PfAlYcBSbHT39oN/WfdNCfNDvMH28IKLt+F5R9IbycF3T3rBv2sM7CtCyaPavUP7QrhgsxJMdg/w
99XZaeCAY00sLq8ApXZ13cAMd4VF5nRJpdeHQtKDcYxf02WrIlN4vcUusVfHAT/XJfX1pLAPZAN6
8znu1sxJOZNFXhni5N14cvtEFEX+ntxk4mQZxXI09LZ/fV7/3f/72W1QbSL6Qa3QoALbnbLWh8GT
J9v392rO20YAIf8n9O725y1XeENlZu2mC3skdF2L/ZWbXZCQsRtUQUU0EkpjBcVi6vWk4VL6qPrt
k7Ycn+SKIV67psE3RL+3t7sSs79Pq84y6pzJKjzaumFYPSmAWm53TcNuTSPJ19xU5zBhuozBVhll
LtTvMU9d6rzlqIy7Epf3gLIQGH/Pt60Y3rvzlBse3bsetVS49q+49hXJZwtUKfGB5y1PS9lnk6Lc
a1OlMWOTxc602/DDm6vq+9kFJtHqKKpH0NrdBxHVvZLRsZR1Y7eRqTYZuqtC0UAwaNU7thbsVnUb
fv99a8avba/FSGszaj+bx6qHX+PW6E238V2DhKb5W7GgPCF72GUbaDHLltIKTG1m/K//X/kwHsbD
eBgP42E8jIfxML5s/Aebis1+ACgAAA==
EOF

RUN <<EOF
    cat /entrypoint.64 | base64 -d | tar zxf - > /entrypoint.sh
EOF

# These are the default ports in use by GCSv5.4. Currently, they can not be changed.
#   443 : HTTPD service for GCS Manager API and HTTPS access to collections
#  50000-51000 : Default port range for incoming data transfer tasks
EXPOSE 443/tcp 50000-51000/tcp

# Default command unless overridden with 'docker run --entrypoint'
ENTRYPOINT ["/entrypoint.sh"]
# Default options to ENTRYPOINT unless overridden with 'docker run arg1...'
CMD []
