# syntax=docker/dockerfile:1.3-labs

############## STAGE 1 - Prepare the image for GCS installation ################
FROM ubuntu:24.04

# Prereqs
RUN <<EOF
    set -e
    apt update
    # Resolves: "debconf: (Can't locate Term/ReadLine.pm in @INC" from python install
    apt install -y libterm-readline-gnu-perl
    apt install -y coreutils gzip python3 python3-venv sudo tar
EOF

##################### STAGE 2 - Install GCS using Ansible ######################
# This is the base64 compressed tar of the ansible repo directory
COPY <<EOF /ansible.64
H4sIAAAAAAAAA+0ca3PbNjKf9Stw8nXkpEdST7tlLd+5ieN4zo09ttO5ji+nQCQkoaYIliDtqEn+
++0CJPWkJTm2krbcNhJFAIvFvrCLh6kveddj1pNHhCrAbqulvgFmv9VzrVVr1bHWTvNJtVarVxtP
SOsxiUohlhENCXkSChHdVW9Z+R8UaCL/88ODFz8dmkP3EfpAAe80m3nyb9Rr9Rn515s71Sek+gi0
zMFfXP573ZBY+6W9gFCP9/122WF+xMLyfomQvUFj9u3R8wtyoFWGnHl01BXies8aNACDFeyXSnsu
iyj3JBEBg2b4qVHJeDik4Wj/kmJT0SPPBWD0I7lnpUVYTXj4BQ8e39+jZBCyXru8RbsijoxowIwg
FL8yJyrvH+ArcjkAMvSrPYvu71nQLGuvHuAxQzMQt4YrDG7EkgE2Lo2eCA3ugwZ4Ho248GU5bUXI
K3FLXEGOCdQmWJtAbTJV+59pF9C37naKgHHPHgcGSlbeP9EP88SO6zrAGIpDfK4fJuvuWcigPSvh
MjB8a4vMsaJ0idQmrMLvG+4ySSIhQDDRgEZExkEgwgh+MOKywBOjIcgCxXJ15IluLFE8Pra+YOEN
C99uD6IokLZl3d7emn1VxRRh39KPhqNrPwVecb+faohJjqErRCAJhf8JmlqEFQLBoTvkJ/Nd/YO6
Q+5zGYU0EqEEPoO+MRkxFx4JjSMxpPhjglpsDoNzYweFQeBXBA0U+jgMhGTSzHT12he3HnP7jHCk
BVQOcAGtDlM8YO/pMPCAzFvueWQoZEQ8fs28EfEZVIwE6TKgkAaR/tXjERmJGMm/4aHwkR6zVHr2
DOzjpkUGMFoegRHcAlm9Hnc4qMzISLgOKK4m1QgH4TA3huGO+ewKR+Yz2lBcDY2b1pT6Gv0YJG09
ffbMJEoHkkIWgibD6HwRkRAYSNWwaaR7lsARH9gcIW+SYavSOHCB56g4Wv/H2ACJ0LzyaJ/0GI2A
enjrMQpsRz1SjDCVfq5kSKWaSY6ABMcTvpaJ6gO6Vnye4pcvXKYM5927d3LAPE/9+DvpZ+1TLsKb
Qdw1HTFMGJjDR61VJlRP8ZbqoL26U3I2igbCbxDoGgkDJe4zUOwRaOfQLDVMMJIoDkgAenUrQtdD
jl5cvNJ8m6mPLykotOOI2I80n1FdZAwsgrfQ1iw1TXIe++RdMjkbQeJpiQHivgFdE+GovafxdjTe
/X9AITA4bO+FbCgi1sEf+yRtao6G3jstj8QHlQ5gaEDvNYrdEcEo5P2BdglvfA5ckTwaKU894A7t
CzAmaKAqSRCO4pyrMSaeqnSm5E9cHqLrQNaljua3GE0TJI3jf5e8/ddYv4G0Lz0T/jUhjf+Sb9Pp
9R+8jyXxX61ab87Ef4367k4R/20CrlzWo7EXybelrRLEEq8vjn88Oew8P3398vjI1rPIxCRHbmjI
VQinvH/E8AM8RqI+4EcglvNdwHQ7gPlbz5UwuWi3zzEmeJF0iGVOHIaIVXsM8GomUAGNX4oQpnsb
nrL+2vDoxYz8oPqARljvRDh6SgA3NdCztoy25dPS2E2aVvZcKoUCnHMnoNGgrR4Rx0GMLvlGcFeq
oaTenoUhTFMwDB+nxh54M0m61LnGacCKZWh1uW8FqnIyMwCyina+lXR2gKmB4TCmpvXM1mBaSu3P
w5k2siAEBLZBWNKhAcTOLrhqaalYKAgZfHZcLh0BznlkDqKhV5os0rS0MVbCcb0QfgVneAyIKvKa
Az63ApORvJYlwIITQyd53UHeSWAxjBImhi+tkwVsDlL9y4zkEfpY4v+r1dburP+v7bQK/78JuPLA
hXpo/29LtfquWYX/aqk77yRhMnjYtqpXuIY/G6T2P5knPHQfS+1/Z3b9r9GC6oX9bwAMFTdJG7M1
yH1VVGSrJNggC3PlwgX8qSC1fyX4R9oFWn//pw4JYLH/swmYlv9Ci/9srVhf/jstqF7IfwOwivzT
JYL7KsLa8q9XG/BVyH8DsJb8h5T79wgQl8d/OzPyBwUo8r+NwBZuyoECfIz95CHZRPsYhMzQr0p9
R3ZwO8ZOKhcx4J8GVrF/tWb4GVHAyv4for76TgPm/90dXP8v/P/jw+ryv6fzf7Lc/zd2Zuf/WqNV
nP/ZCBjEp0NmZ3vdeMAnoM417TNZIrj9kiwHdKDcd2no8t9Zp0eH3BvZ2VmZc+a+opFNQuYOaJS9
vlC7Dy712FzRC9bl1LeJq77HLWIJdSV8wivuO17sso7SP90ZbiHZpJwcB+h8+LCIrqt0+VLI5M1b
8ukT6m65mLlmYHX7T3muJbaOJ1hi/00we23/tVoTfUG13mjs7Bb2vwnYWhtKW8pSj19fXB6cnBxc
Hp++Ji9Pz8mbbuxHsaUNu3QPvHoDOtlI7lEnUgeJ0oNgtiomc6Ztk7THcaGL58h4N8aNi86Q/irC
jjrPIsDh1KrkI6nV8OM7+Kjjz3o9t3VypskmYBdACFTuxp4n2YjhI9TgDjz0cHMEvn+lw+EIvq+5
zyLu5GFNaYaammu46z3riXEvGr0xBt6S49YcOMse97k6RwPesMscgQ1GylPTINIuEuzTnthvvvU9
Qd3lZ8ks9KXYV4f7Pf6eyas06kfnaWVnv6SF7yAn7KZ4VCO9f92BKiYUKUKgQQTkBXhWCLfr0wEe
+mpDX41v0WFDApSkfUPXYwZwNj/s5DibHjpu7NvEYpFjATssKeLQYdLEQwGmm3P0a7oz/HmXHuA8
guhUdyHrs/eBTSr/2/qvfAbDJpXkvaaJVNJ3eIogW1VPe/tbm5R1PlVeVDTOv8pj3r3gcgnzdJMJ
rXl4luku7smqHE5tkZV5tboijVl4Fz/w7FtqOuBn1mTGuI+1GOLo4882+ZjEPjj8K8n7PnON7qit
TpjIAQ3ZpJlZR2dHxr8PfzH0eI16td40+0H/bWbw3Zh709a+hgvQ40DbJsvHooYA7/NE1s7T4XXE
FoTi/RoSg38mkNVDaQEdaesF7D5wfot5yGwbGWfbqqZtz3EPtE4417I1ANYmnkJVhfGXf1h15ONi
3ZZL7cmZO2bKG3XWVjHl4OySONQZsHwfr0/mdlQtXbh4+ljE3nysGsFC1Wg1F7n0Lx28FPDZsH78
j8nZeusAy+L/3epOFv/vVncx/q816kX8vwm4d/w/nwCcnh2+vnhzcUheHJ4f/wzvfz68MB8+ESDb
6WHT7OgSMYbpbGWiC4+4b0o8k/80P2vAlYaVc4bWsvygbJNmbp0ETxkRmbnVbHVnSjHwhNFAH4Q9
Hmb3dI5OTn98c0Gu2YhAKOVxh0feCF051fcqWMay30dBANPoULgx/MKbH3gSFM+FGlzhA8SARh13
HZFbOkpb4Jne3Dzk/OynyVwE6djG+OPpfIAZDDtQrCcVfLhPOpLEIhN5B5K8KAD67NRJj35yDnz0
9AlYNBnXGTp9Mn1BQ2dgQumi6faO2PiBkoVFGdacYeGNG02EM3RtUh6rG++NFEWG4SZdJ2JKujV0
t0bLuMhCowdLjZaGlentsIcfLfPvHOyl7jh3tBgvRuM6DzTcdENv8+N948u7xYsDjv0HF/CidG/R
mBemDzhOZZsyN9VrTSR7JlZdnFpc5fHlDFprxX+bVMWBtRcPpkWgOtHVk9pdmGji0Gs/ZK6Hjggj
Oisv4UsmL3Rif0cC0EFZCUE9yj28jDBk0UC47SDkwPBolJRqLXHbteR3Wtz+/rvkDWSukMA411kV
eAFevq1W+S1LySW45kikAUUWTEHGoglg3Qw02+xYKT+anx7WSJHI5O0ZjePV5eXZRefs/PQ/v4B9
ffhQyU0xK4T3yPaixPEpYR7M+pUKJqKlz0jE1o//9UbOw63/16o76f0vtf9bw/i/WSvW/zcCDxj/
603AR47+8wP6pPuPE7uOq8b3uBHwPe4I4GZAE/cGmrk7AjY58Ib0hPvxe6j3HKz69AIeXjJXhBQe
TkPqeCwtz4g6BxsfzRA3E+Afnh2erBLej+LharG9Cu2htuX6vfzYXnU7H9yvE9V7Zk8NP/mTA2rW
CeKuxQLmTTlt7GtymVSJ96qSL5sKRs8z/v2OxlAdwwctDIwsXNaN+33w3gQw43Q1ueY2x4U7FomB
jQsThDuHjh9GkiEmIf76o18rKVidN6Anh0rPPLzmzTNW4H3PG4b3GUXcHyR/FYASKXoR/vEF5rvM
d0bpXfiMbageqbYCaq2Qk5f2wYancUBkpm+eQ77Uj0MVtuHfIZDAdaIIF5IM6A1DGpJ8wjXnhIe6
rXEYQ+rT/oIJfEZ20MJI7qluT7d8uozBW6mdN2vf4j1U9RcjogGibCni5yhZIpRZeX/EP4WxB+jz
k9oN5+Er57WPlp7nmV6Rmy/P3nDk8KSixKnTPKo4zVg+fIOB5n3UlHzzKTu7M2+JKy8EjOlQYe00
0tYsVskiEURLUJpp+lGdQO5DEqux/9GWHb64IFdb43hQQSY4zdlEcgVJftVLKl+7LNP1mwcVZor0
vtL82taLYFYy/5rLRai+Lg9x6lw7mP2a15AmDBGGp+20oqN7vRBzd3ANSlrR0WElXZ1hXiUx8k2f
kPC4zzDY8eaP+dxXcRGlrbtr565YqZoQULEwor0I867D05erjn9cnH9O4s6lO7KdkJMuWn4kyd2l
7YqO4kA0nz7NR8ozIaaSfM4iHwExk2+negHdmPqZkZ2oQQ6mVDe+6LGKVdb/0DA+5xLoyvc/svuf
u61Gtbj/sQlYWf73v/6x9P5HrdGavf9RK/7+12ZgKi9GH6idcXbTj2RBr509wcsktrbThxKZmJOK
a4IFFFBAAQUUUEABBRRQQAEFFFBAAQUUUEABBRRQQAEFFFBAAZuH/wNL9cRDAHgAAA==
EOF

RUN <<EOF
    set -e
    /usr/bin/python3 -m venv /venv
    /venv/bin/pip install --upgrade pip
    # Install wheel to avoid the warning that setup.py is being used when
    # installing Ansible
    /venv/bin/pip install wheel
    /venv/bin/pip install ansible
    cat /ansible.64 | base64 -d | (cd /; tar zxf -)
EOF

# Modifying this arg value on the build command line will cause RUN to reinstall
# Globus instead of using the previous, cached iteration (if it exists). Useful
# for speeding up re-runs to get newer Globus versions.
ARG CACHEBUST=1
ARG GCS_PROXY
ARG GCS_REPO

RUN <<EOF
    ANSIBLE_CMD="/venv/bin/ansible-playbook playbook.yml"
    if [ -n "$GCS_REPO" ]; then ANSIBLE_CMD="${ANSIBLE_CMD} -e gcs_repo=${GCS_REPO}"; fi
    # Pass on proxy support if requested. Used for the pre-stable repo
    if [ -n "$GCS_PROXY" ]; then ANSIBLE_CMD="${ANSIBLE_CMD} -e gcs_proxy=${GCS_PROXY}"; fi
    (cd /ansible; ${ANSIBLE_CMD})
EOF

######################### STAGE 3 - Prepare GCS Image ##########################
LABEL maintainer="support@globus.org"

# This is the base64 compressed tar of entrypoint.sh
COPY <<EOF /entrypoint.64
H4sIAAAAAAAAA+1Z63PbuBHP1+NfsZE9kT0NKckT5zpunU5q63Keix9jO01v7joKREISThTIAqAU
3eN/7y4AUqQk5zFx2umM8cGSgMW+sPvbBcylUcs8E9JEevLo64wujm8PD+mz9+1ht/5JX593n3cf
9Q57hwdE9fzZo27vWRfJofuV9GmMQhumAB79wnQmWWruovvY+v/p2HncGQrZGTI9CYKd+x3BDrx9
eX1xdvHqCF6zQsYTIcfw6uQGFsJMssKAXmrDZwkIDfx9zpWYcWlYGsEbzYEZWGaFgmwhQQk9jZDf
STbLmRHDlFseltlh9Cw66P3p3rUPyIDbCYecKTbjhisNCw6S8wRMBqm1CNoySzhoboq8DUwRtdZI
ISTMBQMu50JlkuxCbnOmBEPlNdqC/GH31evLv7+5GZy8Putf3A7OTuEY/hqnAqkHInmxSXHTP7nu
39aoNI8VN5bytH/1+vLHcyL7of8j0XCZ2NQeJDxPsyUpMZjypaW+uDztI7vbN1eDl9evbpA8y42g
EEcrxhpGmWratsffRxCGIg9Zkiiu9X5NvZvTHwb9i3+cXV9ekAJ1bgmf8zTLSXjDG4EYwU8Q/gqt
DS+04F+BmXAZAA4eTzJonQutKXpqHCpvQnudQTuC/nthDO6IWo4L/oReMBJ3y3W+/ULZjsknym+e
2GdLbm7/oMz7zo0duLntX0HvCDNSjsS4wMBH3cEGDIXOqzQbFhqGS1CFlGRDPZi+Tq5eZGrG0nT5
FNpjKz6MMyl5bELN1ZwrqIfzQqQp5AX+SQhgSuXb2quO/GJvGqNIBiaTMudRCMJAjDnA1BLSLMYw
JxECpyL4PltgyKungEcXc4IMhAVkt8jUlBzBVFYgL5JYIMxloxUMSshUgooivEzYHDdKKGSuxFyk
fIygghoZJiQyJ37cEVlimaT2BJAh8so1IHJqns4rqHGwi4rHEx5P7RmRBhgjSE96oh5mgkA8Eqnl
OWNT5OUOFqcFeYThRJ5nyqAuecoMcplFcE6UGGoMRnZPhjsQvFG/GA3wunn/IBPvxJqCagbhCGwh
cq6ITRqkEkLtJo0q+PoyMrrCCkIFYoVugOiGXkTtmbNjMeFoQAPHSCfFGWogTNAExuNWZzUR4kT0
Cxb9VmCTcR1fX8Buc3cQT2ZZAs+73Y2V4GPxSOkKP9usDcOmDuvMPNk6gHtc2f0bhJJDdxNLasJG
DH2TOLz4b8LFQdkH2GSaZVIYDMMycyj8sagVtYz4CjhB2uzslHpQVpwzycZc2SXrqnazWfHr7bIh
sMlgk+fl1RnkKiMgcCGPwJAtNLUtlEEsmQlJ6eVTzVfjTWShvgIzEz9ZgY2REr+SbAQHVfLFIGYx
yaEF2xXVuBV2lkTcKib1iFc+9blf4gt/z+PCoKfHsR7MnFmRzuIpN/ZEsJVgtNxBzO6s0wBqioKR
3ZBPWDqK4MyQIwrqdghO4mw2K6SInVFDbhaco3E5phrvTIzJEyuE9Ky5lbo6K494yQxhQwlj6xvW
DtRhwYdAzeJ4QsCCEUr5S3ROWcvOmyAMAsoocl2b4qgTf0ooNMvmDbo9UiMXiYWIfXtSiGtDSITC
5MwQ0olgLOZW0XOCWtSpPIGIuEuLbk4D3LycpUJOK5tJVpY6cyVf2ApBTtGoAXJzR1r3C9mkDaHz
SHgXOV2jIJhNUa+NI0GwobLlHHTk/bRB5DF0bbpjj3PrIVO0+NSwSvgwghuOAJyKoQfgxH8293uE
37NoEifQwR6w45CvoycYwx1U8i92FWVTeENYlGccjqtvYWMnwf6Y4ipT0mOfg0mqp5Qhz+Dj4+fg
mzDMFTaiDI8lFwOW5x/fkDCOIPUJ7MsNqGtyjLq+P9ru802VMAo3SHEy2KeTeMsw3stKXQYs1jSB
x6PFGLtrjKjCRuWoSH1hDXAdqX6Cx7aobmGOtSHJrCN1ynkO3egQJyQPanQDpDt+h2G7lcO7wLZb
C2wmmBxzuqLhSUxE7rqIKtPKVsAFuw1zanmEoST9pJiyfGqVtYPt71bf+rYaLS40zlDUOKkH9VK4
A6d8KJjsvBkW0hSumZYGexAbszanFosFnrxhR+WXDwjlqeae8TVP0NTOCZbpy5vOdzzJFNvK36l1
5H1yN29fiNfL1UssAtowQv47ClZFQSXLFayySumljMsOd60KleBFfYK24G7bRc2p783GyGlGDe8Y
6wMipjYJXeBdLFJ5KnRBvTeeMUK1IfAuqw6hoKbmLKPGzJUjZIgiJBKw5CkVtLYVVbawuLySZi/6
7YQiQdGKbmPH+Jn4sbX9YqWf4Ekj9Kt5mwS7j4ONc3jpzs6C99ZjqBO0gy+MTV9oNRvZxpwyyG2n
Pph2rrPFeaBnLWNX0QjCjeMq0rzs8jMivPnUQLY01hwHL9zEnXwqOibVnZgrozv2OjTJtIliZdA+
2lDZ6CQ41vBnvBIVWCbtLQY3pfSwMrG9lXIFv+r2y73WUsQM6mRc7Qy1TsMx3WCU1w7zxolZOQNd
pte4rXzmTnGrp+yS+2u9RCnZgNddv+VOSLV7V2Ba0r/bTG0lku9ur7YntVtDxKS4bX8s+k1WIENr
BMHr1uAnuAlLuBkj/5HJ6bYRrPzi95WLPmn8JeWm/BK7GPBUEWFKuXTSXErK+dJnDva2SbHO3lbI
7iK+u6Q50vVydhefd8HXuPzYdpRSOC6UwthHmJRZeZW2Bf7y7PRk/VU0uv/bzwgjyoK90ANfEgYs
xUZ3bz/4zbpvSpgf4g22hxdcvA3PO5LeSA5ePOkFf9QY2FeEkke1e4f2hXDBZiWY7B7g76uz08AB
x5pYXF4BSu3quoEZ7gqLzOmSSq8PhaQH4xi/pstWRabweotdYq+OA36uS+rrSWEfyAb05nPcrZmT
ciaLvDLEybvx5PaJKIr8PbnJxMkyiuVo6G3/+rz+u//Ps9ug2kT0g1qhQQW2O2WtD4MnT7bv79Wc
t40AQv5v6N3tz1uu8IbKzNpNF/ZI6LoW+ys3uyAhYzeogopoJJTGCorF1OtJw6X0UfXbJ205PskV
Q7x2TYNviH5vb3clZn+fVp1l1DmTVXi0dcOwelIAtdzumobdmkaSr7mpzmHCdBmDrTLKXKjfY566
1HnLURl3JS7vAWUhMP6eb1sxvHfnKTc8unc9aqlw7V9x7SuSzxaoUuIDz1uelrLPJkW516ZKY8Ym
i51pt+H7N1fV97MLTKLVUVSPoLW7DyKqeyWjYynrxm4jU20ydFeFooFg0Kp3bC3Yreo2/P771oxf
216LkdZm1H42j1UPv8at0Ztu47sGCU3zt2JBeUL2sMs20GKWLaUVmNrM+F//v/JhPIyH8TAexsN4
GA/jYXzZ+A+PyzdmACgAAA==
EOF

RUN <<EOF
    cat /entrypoint.64 | base64 -d | tar zxf - > /entrypoint.sh
EOF

# These are the default ports in use by GCSv5.4. Currently, they can not be changed.
#   443 : HTTPD service for GCS Manager API and HTTPS access to collections
#  50000-51000 : Default port range for incoming data transfer tasks
EXPOSE 443/tcp 50000-51000/tcp

# Default command unless overridden with 'docker run --entrypoint'
ENTRYPOINT ["/entrypoint.sh"]
# Default options to ENTRYPOINT unless overridden with 'docker run arg1...'
CMD []
