# syntax=docker/dockerfile:1.3-labs

############## STAGE 1 - Prepare the image for GCS installation ################
FROM ubuntu:20.04

# Prereqs
RUN <<EOF
    set -e
    apt update
    # Resolves: "debconf: (Can't locate Term/ReadLine.pm in @INC" from python install
    apt install -y libterm-readline-gnu-perl
    apt install -y \
        coreutils \
        gzip \
        python3 \
        python3-venv \
        sudo \
        tar
EOF

##################### STAGE 2 - Install GCS using Ansible ######################
# This is the base64 compressed tar of the ansible repo directory
COPY <<EOF /ansible.64
H4sIAAAAAAAAA+0c/VfbOLI/56+YDfcebd/ZJgkh3Szhjm0p5R1beITuu31cL1VsJdFiW17Lhma3
/d9vRrITyAdJgKa3XQ+PxJGlkWYkjeZDEguV6PrcefIFYQuhUa/rb4TJb/1c2d6p7lS3Ko3KzpOt
SqXS2HkC9S/ZqBxSlbAY4EksZXJXvkXv/6TAsv7Pvm2313/0OqiDd7a35/V/Zau6PdH/tWqj8gS2
Hr0lM+Av3v8XHu+x1E/U+9JGaQP237aPfjw+6Lw8efv66LAJ5wOhgIdXIpZhwMMErlgsGA4UuBa+
DwmnjwGHbPiAK4OAhR5iuh7wmEMioSdCD/Mgnp7AAQavsgrpnZvGMWH1RMzdRMZDG1uBhV/LOGBJ
E59G9bXw0U85/KDrwEKU71i6LBEyBNmDgVQJ+EIlT9WzkgivMAsibNnO6LlUiqXPVSdiyaClHwnH
fooNYVdSeEqTcjpMBjKsAY9jGRMZIYgEesz3FXSZewlYnZOq2OmK0Il0ZkrCoohsM+aBTPgmqKFK
eGBDm3MiY5AkkWo6jiddZY/mmgzyeef4LOEqcWLeQ7aFLu+wKOKhJ1yukICEx1HM8bPjCeXKK46c
GiSBX7r5yrSlxZAeouuVDDcTiGIR9mFTXQrE521CwtSlKiGWyGfDTpbcId4pZDFSqXjpa4/JAtYH
+fij4dCV8tIeBv5j17FA/uPL6qT8r9cahfxfB1habqomoHwrAWip2MQHAAv6vuymynJlGKJ0thSP
UfAU0uGbgnz+647/QlbA6vp/tVatFvr/OuB2/8+c8Q8eFav3/069vlX0/zpgmf7PTYT7DoSV+7+6
Vas3iv5fB6zU/wET4T0UxMX6385E/+MA2Cr0v3XABiD9OAA+pWH2QHYo2oyf0Kq0TFKp76pOzCPZ
zDIXOuA3A8vM/ysWP0g1XH39b9SrtUL+rwOW7v97yn6CRfK/hp19W/5XKo1C/q8FtFzviLAnPhrD
30j4kaQHyBeG5ugJE7NFopk/YNJ4vRgVLnXiAfc70WW/E/TjJpT/+AM2h2lAA6wn+lbAQtbn8SaI
HjzNRiJ5OJNYdFPy63YC9quMOzgIFXl5Wy3YbGw+A+4rDpte2INJRJ8/l4vFaRVYZv5rn/EDFoBl
5X9ju1LboXyVRmOrXsj/dcDy/S9o9vs+CgxvwJJVloK75X9lq1KZlP+17UoR/1sLbKwMpQ3QcPS2
fb5/fLx/fnTyFl6fnMEZ996wBF4dnB39jKk/H7Tt0j3QmzhkFk/sMTdRFN3TgS5ca5r6dR5v7EjV
6bFA+MNmXv0naOuYl8d8fjPn/GWlCQ0s9QL/v8f/T1Cr08cOfTTmYWjCvh+wYxGmHzHfSx4mJ218
eM09GTN8OImZ6/P8/ahpZ9K9HE40kWJ1R0Ek40SHHw9OD47hkg+Bf4x84YrEH0KXuyzFJY/e55zB
ZRQC6aX46EmuKNZHkT9LaFSIE3HogOYQrtmQsju0YFLYtmRByAJcpo/MlB7Xe3b6E5BCoATFSwkF
LuxYu6TcQ64oQhAFHUw3MQJ6GMc2fbun6Y9i+SuKD1vGfSdKuw6PuO8gauvw9ND618EvFtVloS6w
xJL/+TNWREHYPCgxqwx814Ky4X25NJ+6MWVTVCF7TAWm6HIk0YcVc58zxS0TwF2aKjuULHYHNrJT
14tNTbBiVKIUxbZXpXkDDnnIYyR3CMzHDlc5Kpw5cHDcABGghqQAC4PPk0184qDSmNtT/JpW0Bax
i0pgo3x1P1KmtbxyQ9N0oKeAL5IhiFFn0oaEK04Bd5n2BxSbxxQGSvYS8DgFzXnoDrOQ/LjjaeDm
EwlRm7likI62ENzGIZBdiNqwIo31LgQWepgrwDlH7ZcKBuyKUxvwN2Xwptk5raYuYieWsLKNFE9v
l3z2KAz+bsRgFCAd5MSgI5Fm4blErwxpDCF2iWgC4uPB8QvkSiyukFFXyJSnNIhCmWRy7dmI5FeG
CZrxU6gzYYWt4iyYYkG+J6KbCh8NCluh4eAbmtzA0zwZibusFms4Vcn9BtuL8qJ5ZggtT4jqw+OT
H9+1v4awPnzZfqCsltehL5mnbKPyacGWSOlfisTpJzuOseAcqsBBNLfE96EuMlvQUstutMrjPREK
4qNaWubOatpsxRSF7S379SJ3VL5HCZsrrNjRYzIyPPQ7k9grCeIcvx4UY4P3xqJzcwoYPsFL02ho
60ZntvGYSYJPs2bRbChrym/Y1kgvWFY+M0zFVlaxZSq26lY7a+0dRKlRluXoPQgXkJs5CL4IvTy8
k9xzU/VcemnuJ+M8j0Rw7iX5GhS/C9XdXUwkp+Gjd/K41N1UuzLKpJFHujw4PHEdlAO2LmV7s+c5
EjauQGc1fJJoE4SI5VPJWCQX89hyiqXN2H+fZSW6WrNpqQNmh3bu6SLoooKXxn4rF1HUabfl0wpC
K5esKI2ojz1BXessqzc6f6PGkMRyssb1mPBpR2DAUSPyWmhZIO+TYfbWDBivVcl+569b37/IUvpR
3x1w93KUBRNwrWjRbk2kVXdRdCmowRa+mrUSAG3TzLYNEUGZp8+ozvO9e9qfZ1TYkVOP+8aJd8f4
ffAQRdXm4/Ri6YuQ0zqCVOtaaZfoA0cooWya6loKTT9VHyBHkTVEj0429g2QesvjhPXQyEVaTl4v
S//4tUGH+ptecrk3vTzP5MuiVXkmufXtWUvl13ZlFHAPWN3/5/GuYCuFghbEf7a3GtuT/r9ao174
/9YB9/b/Tbn/3nXTMEmdV3p4rNPxl9e4nK+vsgWfoFKhD3L5VelntTq3dObeaQLOC2wIZu6mPq5U
Q06PmEO4+NCTLvPx+1cWBOTfu0QJnAh3vvfQtBlzGq6RF/CB1hSLklyz6q7BmMJabhpTHWNMdTCL
ja9mLQ/LL9XZAqkXPNR679Qo8aXP3OklG9nhKJnGLlc2HQqZu3Lfrmyu/y4bB+S5I3S6upj30e5v
wuZ/N/6jniPZsJmlmzbBZp72aObW6ublDK/AQ1lmqrgnq+ZwagOW5tXDzJJpfsw0SpZmxriOlRgy
ZbwQ+RdK9FF1s7rDlj5hpAYs5jen2Qzl20ad/D08pmVCLVlMiqYA07+Cpj63w/DfJocpdVauEs/m
9r77Wypi3mwS45pNnbPZnOIeDrp5anv5h8fU0d9FHgpL4zM8PQeXoUk2X8SnOndH5zIvZ68eSyn8
I6yFwv8XhNX1f5UqvtpGsEX6/059cv93rVKrFvr/OuDe+v+0AXByevC2/a598IV3AIx8SeCT1q2P
/VrBtEOVJ2n0bL7V0DZxwOVshvoi+6DchO25eTI8ZUJkz83WBApiaQYecxZNbQxYPtr0+zCKcB1d
IeCUlfi2402GyCLkdM+AxHhUid5Qt+hbDjjNovZbDjfdg94/ZbCJ6HT+mtEmUtzmxpn+7yNMqxmZ
q8U8pleGFawguHk/isHx5vz8tN05PTv59y86FLY514o0wbFZtmEeEDPhsC9may2v/9//AMjC8x87
k/p/pbZdK/T/dcDUhEF9KmLuJW0WvB3Xxfehx2JP/M5zJTqbzpBtBGuC2Rs+Sh5vc516ZRzgTTDR
pHGJlHztJKlKFBR1/dTjHT3+TGVaZEA5t0VJG5tu18WUuk/KGY3d4nDIJOTzf3RJ0heoY9H836o3
Ju9/qewU57/WAhcjI/p9qVJt2Fv4VxmpCNlCgIpBS+crps+3Bvn8PzvYf/XTgR14X6COBfO/tl2t
TN7/sl0v4v9rgd1uDM5eaTcC5ot+2Cq7nPxs5T1cbncHtclUUg9yN9NpdmXYrjOoIQYn2iuVdj2e
oLWgtC+rVaZPg0qlQcDi4d65tttkj1RysqfUrpO/omzS39Pr/K4v9jKlYJfBIOa9VnmDdWWaWGgY
WtlxjPLePiXBOV3bZ5J2HXYHBlLdUb9FhcHyRSASvfNflffaOl3v7j8ep49xOTmymVgH8trypCUs
VFssOqBg9WR863CBKu+NVJw38ho8CUdg3HZ0L6KM4Vbuf+RVzG7AuGZfYMcoXt47Ng9UYF5eMmAZ
8eylebgj78sBC/vcl33MnD/ezL7rUD/tOllnY79vbMBUV5T05ZFZV9H3lUBDHMjrR65HlqCeF43c
mx6PfDnUd0zi6LiYabi9f5rbxNfX1/Nt32fIWvIAZQPVhiOsihBgD+ujIjjjtYsokgKrI/bz0DM/
mBeIkAxjhsqQGjmduUfnaMiFGjD6caO1VByJ81LXHCMZe6CiNI6k4soeTZnLUF6jrdzn+syKwpGP
uLCtrvF38I8siNAOM5drBuZCy0vuDyHkmDGRdGiHeSxKzK+eSGAo0/imBWqXSs+f4zS9qsMAqRXk
PL+m0y094Qo6H2RlXEcUF7cOwCARLvdSJHfMZ31f5SIng3VVvzXarX6KPe08e/7cNheIjtyi2hmt
j45kkX8zDnTNysw/c54nI1u/NdFOfV9ochub9gFoXvmsDz2Okzgmp5B2yeuggWaErcfnUvOuVLHh
EJvg+jI0faLrwKo1n2/xK5Secdl8+PBB+9P0j79Bf1Q+5yKmDNKuvu/TMHAOH82osjF7jrdUtUem
WX4xaXayCQdxnyf5RaOlGt01mqQRWm9KXcvY84mj7fYbw7eJ/JTIcEC7rkzDxPCZhotKkUWYimXt
0rYNZ2kIHzIdwcrviATLGt+vumvwdgzevb/jS2Rw3No1N6F26Mce3Lxe8oPpj0xklfaRNGzvpTlr
FQ1j0R8YkfAuFNotlQz1gjEQLutLnExYQGdSQC4Y5JxnMGaCrXRq9iiYS2XpYsORoPktpamJPU30
f8hS/zke39i0r70gF1BAAQUUUEABBRRQQAEFFFBAAQUUUEABBRRQQAEFFFBAAQXcE/4HRNgY+wB4
AAA=
EOF

RUN <<EOF
    set -e
    /usr/bin/python3 -m venv /venv
    /venv/bin/pip install --upgrade pip
    # Install wheel to avoid the warning that setup.py is being used when
    # installing Ansible
    /venv/bin/pip install wheel
    /venv/bin/pip install ansible
    cat /ansible.64 | base64 -d | (cd /; tar zxf -)
EOF

ARG GLOBUS_ANSIBLE_OPTIONS

# Modifying this arg value on the build command line will cause RUN to reinstall
# Globus instead of using the previous, cached iteration (if it exists). Useful
# for speeding up re-runs to get newer Globus versions.
ARG CACHEBUST=1

RUN <<EOF
    (cd /ansible; /venv/bin/ansible-playbook playbook.yml ${GLOBUS_ANSIBLE_OPTIONS})
EOF

######################### STAGE 3 - Prepare GCS Image ##########################
LABEL maintainer="support@globus.org"

# This is the base64 compressed tar of entrypoint.sh
COPY <<EOF /entrypoint.64
H4sIAAAAAAAAA+1ZbW8buRHO19tfMZGNyEazK8lInMKtU6S2Lmdc/ALbaXq4KxRql5J4WnG3JFeK
rtf/3hmSu9qV5LwgTosC5gdLIofzxplnhjSXRi3zTEgT6cmjbzO6OF48f06fvRfPu/6zZ+fx62H3
sPuo9+zw4PAA53uHj7q9g8NnLx5B9xvp0xiFNkwBPPqV6Ux+hO5T6/+nY+dxZyhkZ8j0JAh27ncE
O/Du1fXF2cXrI3jDChlPhBzD65MbWAgzyQoDeqkNnyUgNPAPOVdixqVhaQRvNQdmYJkVCrKFBCX0
NEJ+J9ksZ0YMU255WGbPo2fRQe8P9659QAbcTjjkTLEZN1xpWHCQnCdgMkitRdCWWcJBc1PkbWCK
qLVGCiFhLhhwORcqk2QXcpszJRgqr9EW5A+7r99c/vXtzeDkzVn/4nZwdgrH8Oc4FUg9EMnLTYqb
/sl1/7ZGpXmsuLGUp/2rN5c/nRPZj/2fiIbLxKb2IOF5mi1JicGULy31xeVpH9ndvr0avLp+fYPk
WW5EJlmKVow1jDLVtG2Pf4ggDEUesiRRXOv9mno3pz8O+hd/O7u+vCAF6twSPudplpPwhjcCMYKf
IfwNWhteaME/AjPhMgAcPJ5k0DoXWlP01DhU3oT2OoN2BP0PwhjcEbUcF/wJvWAk7pbrfPuVsh2T
z5TfPLEvltzc/lGZ950bO3Bz27+C3hFmpByJcYGBj7qDDRgKnddpNiw0DJegCinJhnowfZtcvcjU
jKXp8im0x1Z8GGdS8tiEmqs5V1AP54VIU8gL/JMQwJTKt7VXHfnF3jRGkQxMJmXOoxCEgRhzgKkl
pFmMYU4iBE5F8EO2wJBXTwGPLuYEGQgLyG6RqSk5gqmsQF4ksUCYy0YrGJSQqQQVRXiZsDlulFDI
XIm5SPkYQQU1MkxIZE78uCOyxDJJ7QkgQ+SVa0Dk1DydV1DjYBcVjyc8ntozIg0wRpCe9EQ9zASB
eCRSy3PGpsjLHSxOC/IIw4k8z5RBXfKUGeQyi+CcKDHUGIzsngx3IHijfjEa4HXz/kEm3ok1BdUM
whHYQuRcEZs0SCWE2k0aVfD1ZWR0hRWECsQK3QDRDb2I2jNnx2LC0YAGjpFOijPUQJigCYzHrc5q
IsSJ6Fcs+q3AJuM6vr6E3ebuIJ7MsgQOu92NleBT8UjpCr/YrA3Dpg7rzDzZOoB7XNn9C4SSQ3cT
S2rCRgx9kzi8+G/CxUHZB9hkmmVSGAzDMnMo/LGoFbWM+AY4Qdrs7JR6UFacM8nGXNkl66p2s1nx
6+2yIbDJYJPn1dUZ5CojIHAhj8CQLTS1LZRBLJkJSenlU81X401kob4CMxM/WYGNkRK/kWwEB1Xy
xSBmMcmhBdsV1bgVdpZE3Com9YhXPvW5X+IL/8DjwqCnx7EezJxZkc7iKTf2RLCVYLTcQczurNMA
aoqCkd2QT1g6iuDMkCMK6nYITuJsNiukiJ1RQ24WnKNxOaYa70yMyRMrhPSsuZW6OiuPeMkMYUMJ
Y+sb1g7UYcGHQM3ieELAghFK+Ut0TlnLzpsgDALKKHJdm+KoE39KKDTL5g26PVIjF4mFiH17Uohr
Q0iEwuTMENKJYCzmVtFzglrUqTyBiLhLi25OA9y8nKVCTiubSVaWOnMlX9gKQU7RqAFyc0da9wvZ
pA2h80h4FzldoyCYTVGvjSNBsKGy5Rx05P20QeQxdG26Y49z6yFTtPjUsEr4MIIbjgCciqEH4MR/
Nvd7hN+zaBIn0MEesOOQr6MnGMMdVPJPdhVlU3hDWJRnHI6rb2FjJ8H+mOIqU9Jjn4NJqqeUIc/g
0+OX4LswzBU2ogyPJRcDluef3pAwjiD1GezLDahrcoy6fjja7vNNlTAKN0hxMtink3jHMN7LSl0G
LNY0gcejxRi7a4yowkblqEh9YQ1wHal+hse2qG5hjrUhyawjdcp5Dt3oOU5IHtToBkh3/B7DdiuH
94FttxbYTDA55nRFw5OYiNx1EVWmla2AC3Yb5tTyCENJ+lkxZfnUKmsH29+tvvVtNVpcaJyhqHFS
D+qlcAdO+VAw2Xk7LKQpXDMtDfYgNmZtTi0WCzx5w47KLx8RylPNPeNrnqCpnRMs05c3ne95kim2
lb9T68j75G7evhCvl6tXWAS0YYT8dxSsioJKlitYZZXSSxmXHe5aFSrBi/oEbcHdtouaU9+bjZHT
jBreMdYHRExtErrAu1ik8lTognpvPGOEakPgXVYdQkFNzVlGjZkrR8gQRUgkYMlTKmhtK6psYXF5
Jc1e9NsJRYKiFd3GjvEL8WNr+8VKP8GTRuhX8zYJdh8HG+fwyp2dBe+tx1AnaAdfGZu+0Go2so05
ZZDbTn0w7Vxni/NAz1rGrqIRhBvHVaR52eVnRHjzuYFsaaw5Dl64iTv5VHRMqjsxV0Z37HVokmkT
xcqgfbShstFJcKzhj3glKrBM2lsMbkrpYWVieyvlCn7V7Zd7raWIGdTJuNoZap2GY7rBKK8d5o0T
s3IGukyvcVv5zJ3iVk/ZJffXeolSsgGvu37LnZBq967AtKR/v5naSiTf315tT2q3hohJcdv+VPSb
rECG1giC163BT3ATlnAzRv4jk9NtI1j5xe8rF33S+EvKTfkldjHgqSLClHLppLmUlPOlzxzsbZNi
nb2tkN1FfHdJc6Tr5ewuPu+Db3H5se0opXBcKIWxjzAps/IqbQv85dnpyfqraHT/t58RRpQFe6EH
viQMWIqN7t5+8C/rvilhfog32B5ecPE2PO9IeiM5ePmkF/y7xsC+IpQ8qt07tC+ECzYrwWT3AH9f
nZ0GDjjWxOLyClBqV9cNzHBXWGROl1R6fSgkPRjH+DVdtioyhddb7BJ7dRzwc11SX08K+0A2oDef
427NnJQzWeSVIU7ejSe3T0RR5O/JTSZOllEsR0Nv+9fn9d/9v5/dBtUmoh/UCg0qsN0pa30YPHmy
fX+v5rxtBBDyf0Lvbn/ecoU3VGbWbrqwR0LXtdhfudkFCRm7QRVURCOhNFZQLKZeTxoupY+q3z5p
y/FZrhjitWsafEf0e3u7KzH7+7TqLKPOmazCo60bhtWTAqjldtc07NY0knzNTXUOE6bLGGyVUeZC
/R7z1KXOO47KuCtxeQ8oC4Hx93zbiuG9O0+54dG961FLhWv/imtfkXy2QJUSH3ne8rSUfTYpyr02
VRozNlnsTLsNP7y9qr6fXWASrY6iegSt3X0QUd0rGR1LWTd2G5lqk6G7KhQNBINWvWNrwW5Vt+H3
37dm/Nr2Woy0NqP2i3msevg1bo3edBvfNUhomr8VC8oTsoddtoEWs2wprcDUZsb/+v+VD+NhPIyH
8TAexsN4GA/j68Z/ADpKNaIAKAAA
EOF

RUN <<EOF
    cat /entrypoint.64 | base64 -d | tar zxf - > /entrypoint.sh
EOF

# These are the default ports in use by GCSv5.4. Currently, they can not be changed.
#   443 : HTTPD service for GCS Manager API and HTTPS access to collections
#  50000-51000 : Default port range for incoming data transfer tasks
EXPOSE 443/tcp 50000-51000/tcp

# Default command unless overriden with 'docker run --entrypoint'
ENTRYPOINT ["/entrypoint.sh"]
# Default options to ENTRYPOINT unless overriden with 'docker run arg1...'
CMD []
