# syntax=docker/dockerfile:1.3-labs
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# ubuntu:bionic needs this set
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN <<EOF1
    apt update
    apt install -y python3 python3-venv sudo
EOF1

