# syntax=docker/dockerfile:1.3-labs
FROM fedora:37

ARG VENV=/venv

RUN <<EOF
yum install -y docker
/usr/bin/python3 -m venv ${VENV}
. ${VENV}/bin/activate
${VENV}/bin/pip install --upgrade pip
${VENV}/bin/pip install ansible
mkdir -p /ansible
EOF

COPY <<EOF /ansible/playbook.yml
- hosts: all
  roles:
    - globus-connect-server
EOF
